namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string Dashboard = """
en|Applies the complete selected profile: MMCSS, processor power policy, BCD/timer, TCP/QoS and RSC. Competitive and Optimized Gaming use Ultimate Performance; Balanced uses the Windows Balanced plan.|Every apply operation requires confirmation and Administrator rights. Game DVR remains independently controlled from Gaming Tweaks. Restart Windows after a profile change.
id|Menerapkan seluruh profil yang dipilih: MMCSS, kebijakan daya prosesor, BCD/timer, TCP/QoS, dan RSC. Competitive Gaming dan Optimized Gaming menggunakan Ultimate Performance; Balanced menggunakan rencana daya Balanced Windows.|Setiap penerapan memerlukan konfirmasi dan hak Administrator. Game DVR tetap diatur secara terpisah melalui Gaming Tweaks. Mulai ulang Windows setelah mengganti profil.
de|Wendet das gesamte ausgewählte Profil an: MMCSS, Prozessor-Energierichtlinie, BCD/Timer, TCP/QoS und RSC. Competitive Gaming und Optimized Gaming verwenden Ultimate Performance; Balanced verwendet den ausgewogenen Windows-Energiesparplan.|Jede Anwendung erfordert eine Bestätigung und Administratorrechte. Game DVR wird weiterhin unabhängig über Gaming Tweaks gesteuert. Starten Sie Windows nach einem Profilwechsel neu.
fr|Applique le profil sélectionné complet : MMCSS, stratégie d'alimentation du processeur, BCD/minuterie, TCP/QoS et RSC. Competitive Gaming et Optimized Gaming utilisent Ultimate Performance ; Balanced utilise le mode d'alimentation équilibré de Windows.|Chaque application exige une confirmation et des droits administrateur. Game DVR reste géré séparément dans Gaming Tweaks. Redémarrez Windows après un changement de profil.
ar|يطبق ملف الأداء المحدد بالكامل: MMCSS وسياسة طاقة المعالج وBCD/المؤقت وTCP/QoS وRSC. يستخدم Competitive Gaming وOptimized Gaming خطة Ultimate Performance؛ ويستخدم Balanced خطة Windows المتوازنة.|يتطلب كل تطبيق تأكيدًا وصلاحيات المسؤول. يظل التحكم في Game DVR مستقلاً من خلال Gaming Tweaks. أعد تشغيل Windows بعد تغيير ملف الأداء.
tl|Inilalapat ang buong napiling profile: MMCSS, patakaran sa power ng processor, BCD/timer, TCP/QoS at RSC. Gumagamit ang Competitive Gaming at Optimized Gaming ng Ultimate Performance; ginagamit ng Balanced ang Windows Balanced plan.|Kailangan ng kumpirmasyon at mga karapatan ng Administrator ang bawat paglalapat. Hiwalay pa ring kinokontrol ang Game DVR sa Gaming Tweaks. I-restart ang Windows matapos magpalit ng profile.
vi|Áp dụng toàn bộ cấu hình đã chọn: MMCSS, chính sách nguồn bộ xử lý, BCD/bộ hẹn giờ, TCP/QoS và RSC. Competitive Gaming và Optimized Gaming dùng Ultimate Performance; Balanced dùng gói nguồn Cân bằng của Windows.|Mỗi lần áp dụng đều cần xác nhận và quyền quản trị viên. Game DVR vẫn được điều khiển riêng trong Gaming Tweaks. Khởi động lại Windows sau khi đổi cấu hình.
zh-CN|应用完整的所选配置：MMCSS、处理器电源策略、BCD/计时器、TCP/QoS 和 RSC。Competitive Gaming 和 Optimized Gaming 使用 Ultimate Performance；Balanced 使用 Windows 平衡电源计划。|每次应用都需要确认和管理员权限。Game DVR 仍通过 Gaming Tweaks 独立控制。更改配置后请重启 Windows。
zh-TW|套用完整的所選設定：MMCSS、處理器電源原則、BCD/計時器、TCP/QoS 和 RSC。Competitive Gaming 和 Optimized Gaming 使用 Ultimate Performance；Balanced 使用 Windows 平衡電源計劃。|每次套用都需要確認和系統管理員權限。Game DVR 仍透過 Gaming Tweaks 獨立控制。變更設定後請重新啟動 Windows。
th|ใช้โปรไฟล์ที่เลือกทั้งหมด: MMCSS นโยบายพลังงานโปรเซสเซอร์ BCD/ตัวจับเวลา TCP/QoS และ RSC โดย Competitive Gaming และ Optimized Gaming ใช้ Ultimate Performance ส่วน Balanced ใช้แผนพลังงานแบบสมดุลของ Windows|การใช้ทุกครั้งต้องยืนยันและมีสิทธิ์ผู้ดูแลระบบ Game DVR ยังคงควบคุมแยกต่างหากผ่าน Gaming Tweaks รีสตาร์ต Windows หลังเปลี่ยนโปรไฟล์
ru|Применяет выбранный профиль целиком: MMCSS, политику питания процессора, BCD/таймер, TCP/QoS и RSC. Competitive Gaming и Optimized Gaming используют Ultimate Performance; Balanced использует сбалансированную схему Windows.|Каждое применение требует подтверждения и прав администратора. Game DVR по-прежнему управляется отдельно в Gaming Tweaks. Перезапустите Windows после смены профиля.
uk|Застосовує вибраний профіль повністю: MMCSS, політику живлення процесора, BCD/таймер, TCP/QoS та RSC. Competitive Gaming і Optimized Gaming використовують Ultimate Performance; Balanced використовує збалансовану схему Windows.|Кожне застосування потребує підтвердження та прав адміністратора. Game DVR і далі керується окремо в Gaming Tweaks. Перезапустіть Windows після зміни профілю.
pt|Aplica o perfil selecionado completo: MMCSS, política de energia do processador, BCD/temporizador, TCP/QoS e RSC. Competitive Gaming e Optimized Gaming utilizam Ultimate Performance; Balanced utiliza o plano Equilibrado do Windows.|Cada aplicação requer confirmação e direitos de administrador. O Game DVR continua a ser controlado separadamente em Gaming Tweaks. Reinicie o Windows após alterar o perfil.
ja|選択したプロファイル全体を適用します：MMCSS、プロセッサの電源ポリシー、BCD/タイマー、TCP/QoS、RSC。Competitive Gaming と Optimized Gaming は Ultimate Performance を使用し、Balanced は Windows のバランス電源プランを使用します。|適用するたびに確認と管理者権限が必要です。Game DVR は引き続き Gaming Tweaks で個別に制御されます。プロファイル変更後は Windows を再起動してください。
ko|선택한 전체 프로필을 적용합니다: MMCSS, 프로세서 전원 정책, BCD/타이머, TCP/QoS 및 RSC. Competitive Gaming과 Optimized Gaming은 Ultimate Performance를 사용하며, Balanced는 Windows 균형 조정 전원 관리 옵션을 사용합니다.|적용할 때마다 확인과 관리자 권한이 필요합니다. Game DVR은 Gaming Tweaks에서 계속 별도로 제어됩니다. 프로필 변경 후 Windows를 다시 시작하세요.
ur|منتخب مکمل پروفائل لاگو کرتا ہے: MMCSS، پروسیسر کی توانائی پالیسی، BCD/ٹائمر، TCP/QoS اور RSC۔ Competitive Gaming اور Optimized Gaming میں Ultimate Performance استعمال ہوتا ہے؛ Balanced میں Windows کا متوازن پاور پلان استعمال ہوتا ہے۔|ہر اطلاق کے لیے تصدیق اور منتظم کے حقوق ضروری ہیں۔ Game DVR کا کنٹرول Gaming Tweaks میں الگ رہتا ہے۔ پروفائل تبدیل کرنے کے بعد Windows دوبارہ شروع کریں۔
ta|தேர்ந்தெடுத்த முழு சுயவிவரத்தையும் பயன்படுத்துகிறது: MMCSS, செயலியின் மின்சக்திக் கொள்கை, BCD/நேரங்காட்டி, TCP/QoS மற்றும் RSC. Competitive Gaming மற்றும் Optimized Gaming ஆகியவை Ultimate Performance-ஐப் பயன்படுத்தும்; Balanced ஆனது Windows சமநிலை மின்திட்டத்தைப் பயன்படுத்தும்.|ஒவ்வொரு பயன்பாட்டிற்கும் உறுதிப்படுத்தலும் நிர்வாகி உரிமைகளும் தேவை. Game DVR தொடர்ந்து Gaming Tweaks மூலம் தனியாகக் கட்டுப்படுத்தப்படுகிறது. சுயவிவரத்தை மாற்றிய பின் Windows-ஐ மறுதொடக்கம் செய்யவும்.
hi|चयनित पूरा प्रोफ़ाइल लागू करता है: MMCSS, प्रोसेसर पावर नीति, BCD/टाइमर, TCP/QoS और RSC। Competitive Gaming और Optimized Gaming में Ultimate Performance उपयोग होता है; Balanced में Windows का संतुलित पावर प्लान उपयोग होता है।|हर बार लागू करने के लिए पुष्टि और व्यवस्थापक अधिकार आवश्यक हैं। Game DVR का नियंत्रण Gaming Tweaks में अलग रहता है। प्रोफ़ाइल बदलने के बाद Windows पुनः प्रारंभ करें।
ms|Menggunakan keseluruhan profil yang dipilih: MMCSS, dasar kuasa pemproses, BCD/pemasa, TCP/QoS dan RSC. Competitive Gaming dan Optimized Gaming menggunakan Ultimate Performance; Balanced menggunakan pelan kuasa Seimbang Windows.|Setiap penggunaan memerlukan pengesahan dan hak pentadbir. Game DVR kekal dikawal secara berasingan melalui Gaming Tweaks. Mulakan semula Windows selepas menukar profil.
jv|Nerapake profil sing dipilih kanthi lengkap: MMCSS, kabijakan daya prosesor, BCD/timer, TCP/QoS lan RSC. Competitive Gaming lan Optimized Gaming nganggo Ultimate Performance; Balanced nganggo rencana daya Balanced Windows.|Saben nerapake mbutuhake konfirmasi lan hak Administrator. Game DVR tetep diatur dhewe saka Gaming Tweaks. Wiwiti maneh Windows sawise ngganti profil.
ban|Nerapang profil sane kapilih kanthi jangkep: MMCSS, kabijakan daya prosesor, BCD/timer, TCP/QoS miwah RSC. Competitive Gaming miwah Optimized Gaming nganggen Ultimate Performance; Balanced nganggen rencana daya Balanced Windows.|Sabilang penerapan mabuat konfirmasi miwah hak Administrator. Game DVR tetep kaatur kapisah ring Gaming Tweaks. Uripang malih Windows sasampun ngentos profil.
sv|Tillämpar hela den valda profilen: MMCSS, processorns energipolicy, BCD/timer, TCP/QoS och RSC. Competitive Gaming och Optimized Gaming använder Ultimate Performance; Balanced använder Windows balanserade energischema.|Varje tillämpning kräver bekräftelse och administratörsbehörighet. Game DVR styrs fortfarande separat via Gaming Tweaks. Starta om Windows efter ett profilbyte.
es|Aplica el perfil seleccionado completo: MMCSS, directiva de energía del procesador, BCD/temporizador, TCP/QoS y RSC. Competitive Gaming y Optimized Gaming usan Ultimate Performance; Balanced usa el plan Equilibrado de Windows.|Cada aplicación requiere confirmación y permisos de administrador. Game DVR sigue controlándose por separado desde Gaming Tweaks. Reinicie Windows después de cambiar de perfil.
""";
}
