namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string AppExpansion = """
en|Uninstall recommendation|Recommended|Optional|Not Recommended|Remove if unused. Personal data and later Store availability are not guaranteed.|Keep unless you understand the impact on hardware, security, gaming, media support or saved data.|Personal choice: keep this app if you use its features. Back up local data before removal.|Disable BitLocker automatic device encryption|BitLocker Automatic Device Encryption
id|Rekomendasi penghapusan|Direkomendasikan|Opsional|Tidak Direkomendasikan|Hapus jika tidak digunakan. Data pribadi dan ketersediaan Store di kemudian hari tidak dijamin.|Pertahankan kecuali Anda memahami dampaknya pada perangkat keras, keamanan, gaming, dukungan media atau data tersimpan.|Pilihan pribadi: pertahankan jika fiturnya digunakan. Cadangkan data lokal sebelum menghapus.|Nonaktifkan enkripsi perangkat otomatis BitLocker|Enkripsi Perangkat Otomatis BitLocker
de|Deinstallationsempfehlung|Empfohlen|Optional|Nicht empfohlen|Bei Nichtgebrauch entfernen. Persönliche Daten und spätere Store-Verfügbarkeit sind nicht garantiert.|Behalten, sofern die Folgen für Hardware, Sicherheit, Spiele, Medien oder gespeicherte Daten nicht bekannt sind.|Persönliche Entscheidung: bei Nutzung behalten. Lokale Daten vor dem Entfernen sichern.|Automatische BitLocker-Geräteverschlüsselung deaktivieren|Automatische BitLocker-Geräteverschlüsselung
fr|Conseil de désinstallation|Recommandé|Facultatif|Déconseillé|Supprimez si inutilisé. Les données personnelles et la disponibilité future du Store ne sont pas garanties.|À conserver sauf si vous comprenez les conséquences sur le matériel, la sécurité, les jeux, les médias ou les données.|Choix personnel : conservez cette application si vous l’utilisez. Sauvegardez les données locales avant suppression.|Désactiver le chiffrement automatique de l’appareil BitLocker|Chiffrement automatique de l’appareil BitLocker
ar|توصية إلغاء التثبيت|موصى به|اختياري|غير موصى به|أزل التطبيق إن لم تستخدمه. لا ضمان للبيانات الشخصية أو توفره مستقبلاً في Store.|احتفظ به ما لم تفهم التأثير على الأجهزة والأمان والألعاب والوسائط والبيانات المحفوظة.|اختيار شخصي: احتفظ بالتطبيق إن كنت تستخدمه. انسخ البيانات المحلية احتياطياً قبل الإزالة.|تعطيل تشفير الجهاز التلقائي بواسطة BitLocker|تشفير الجهاز التلقائي بواسطة BitLocker
tl|Rekomendasyon sa pag-uninstall|Inirerekomenda|Opsyonal|Hindi inirerekomenda|Alisin kung hindi ginagamit. Walang garantiya sa personal na data at pagkakaroon sa Store sa hinaharap.|Panatilihin maliban kung nauunawaan ang epekto sa hardware, seguridad, laro, media o naka-save na data.|Personal na pagpili: panatilihin kung ginagamit. I-back up ang lokal na data bago alisin.|I-disable ang awtomatikong device encryption ng BitLocker|Awtomatikong Device Encryption ng BitLocker
vi|Khuyến nghị gỡ cài đặt|Khuyến nghị|Tùy chọn|Không khuyến nghị|Gỡ nếu không dùng. Không đảm bảo dữ liệu cá nhân và khả năng cài lại từ Store sau này.|Giữ lại trừ khi hiểu tác động đến phần cứng, bảo mật, trò chơi, đa phương tiện hoặc dữ liệu đã lưu.|Tùy nhu cầu: giữ ứng dụng nếu dùng tính năng của nó. Sao lưu dữ liệu cục bộ trước khi gỡ.|Tắt mã hóa thiết bị tự động của BitLocker|Mã hóa thiết bị tự động của BitLocker
zh-CN|卸载建议|推荐|可选|不推荐|不使用时可卸载。无法保证个人数据及今后在 Store 中的可用性。|除非了解对硬件、安全、游戏、媒体支持或已保存数据的影响，否则请保留。|按个人需要选择：使用其功能时请保留。卸载前备份本地数据。|禁用 BitLocker 自动设备加密|BitLocker 自动设备加密
zh-TW|解除安裝建議|建議|可選|不建議|不使用時可解除安裝。無法保證個人資料及日後在 Store 中的可用性。|除非了解對硬體、安全、遊戲、媒體支援或已儲存資料的影響，否則請保留。|依個人需求選擇：使用其功能時請保留。移除前備份本機資料。|停用 BitLocker 自動裝置加密|BitLocker 自動裝置加密
th|คำแนะนำในการถอนการติดตั้ง|แนะนำ|ทางเลือก|ไม่แนะนำ|ลบได้หากไม่ได้ใช้ ไม่รับประกันข้อมูลส่วนตัวหรือการดาวน์โหลดจาก Store ในอนาคต|ควรเก็บไว้ เว้นแต่เข้าใจผลกระทบต่อฮาร์ดแวร์ ความปลอดภัย เกม สื่อ หรือข้อมูลที่บันทึก|เลือกตามการใช้งาน เก็บไว้หากใช้คุณสมบัติของแอป สำรองข้อมูลในเครื่องก่อนลบ|ปิดการเข้ารหัสอุปกรณ์อัตโนมัติของ BitLocker|การเข้ารหัสอุปกรณ์อัตโนมัติของ BitLocker
ru|Рекомендация по удалению|Рекомендуется|По желанию|Не рекомендуется|Удаляйте, если не используете. Сохранность личных данных и доступность в Store в будущем не гарантируются.|Сохраните, если не понимаете последствий для оборудования, безопасности, игр, мультимедиа или сохранённых данных.|Личный выбор: сохраните приложение, если используете его. Перед удалением скопируйте локальные данные.|Отключить автоматическое шифрование устройства BitLocker|Автоматическое шифрование устройства BitLocker
uk|Рекомендація щодо видалення|Рекомендовано|За бажанням|Не рекомендовано|Видаляйте, якщо не користуєтеся. Збереження особистих даних і майбутня доступність у Store не гарантовані.|Залиште, якщо не розумієте наслідків для обладнання, безпеки, ігор, медіа чи збережених даних.|Особистий вибір: залиште програму, якщо користуєтеся нею. Перед видаленням збережіть локальні дані.|Вимкнути автоматичне шифрування пристрою BitLocker|Автоматичне шифрування пристрою BitLocker
pt|Recomendação de desinstalação|Recomendado|Opcional|Não recomendado|Remova se não utilizar. Os dados pessoais e a disponibilidade futura na Store não são garantidos.|Mantenha salvo se compreender o impacto no hardware, segurança, jogos, multimédia ou dados guardados.|Escolha pessoal: mantenha se utilizar as funcionalidades. Copie os dados locais antes de remover.|Desativar a encriptação automática do dispositivo BitLocker|Encriptação automática do dispositivo BitLocker
ja|アンインストールの推奨度|推奨|任意|非推奨|使用しない場合に削除してください。個人データと将来の Store での提供は保証されません。|ハードウェア、安全性、ゲーム、メディア機能、保存データへの影響を理解していない場合は保持してください。|利用状況に応じて選択してください。使用する場合は保持し、削除前にローカルデータをバックアップしてください。|BitLocker の自動デバイス暗号化を無効にする|BitLocker の自動デバイス暗号化
ko|제거 권장 수준|권장|선택 사항|권장하지 않음|사용하지 않으면 제거하세요. 개인 데이터와 향후 Store 제공 여부는 보장되지 않습니다.|하드웨어, 보안, 게임, 미디어 지원 또는 저장된 데이터에 미치는 영향을 모르면 유지하세요.|개인 선택: 기능을 사용하면 유지하세요. 제거 전에 로컬 데이터를 백업하세요.|BitLocker 자동 장치 암호화 사용 안 함|BitLocker 자동 장치 암호화
ur|ان انسٹال کرنے کی سفارش|تجویز کردہ|اختیاری|تجویز نہیں کیا جاتا|استعمال نہ ہو تو ہٹائیں۔ ذاتی ڈیٹا اور مستقبل میں Store پر دستیابی کی ضمانت نہیں۔|برقرار رکھیں جب تک ہارڈویئر، سکیورٹی، گیمنگ، میڈیا یا محفوظ ڈیٹا پر اثرات نہ سمجھتے ہوں۔|ذاتی انتخاب: خصوصیات استعمال کرتے ہیں تو برقرار رکھیں۔ ہٹانے سے پہلے مقامی ڈیٹا کا بیک اپ لیں۔|BitLocker کی خودکار ڈیوائس انکرپشن بند کریں|BitLocker کی خودکار ڈیوائس انکرپشن
ta|நிறுவல் நீக்கப் பரிந்துரை|பரிந்துரைக்கப்படுகிறது|விருப்பத்தேர்வு|பரிந்துரைக்கப்படவில்லை|பயன்படுத்தவில்லை என்றால் நீக்கவும். தனிப்பட்ட தரவும் எதிர்கால Store கிடைக்கும் நிலையும் உறுதியில்லை.|வன்பொருள், பாதுகாப்பு, விளையாட்டுகள், ஊடக ஆதரவு அல்லது சேமித்த தரவு மீதான தாக்கம் தெரியாவிட்டால் வைத்திருக்கவும்.|தனிப்பட்ட தேர்வு: அம்சங்களைப் பயன்படுத்தினால் வைத்திருக்கவும். நீக்குமுன் உள்ளூர் தரவைக் காப்புப் பிரதி எடுக்கவும்.|BitLocker தானியங்கி சாதன மறைகுறியாக்கத்தை முடக்கு|BitLocker தானியங்கி சாதன மறைகுறியாக்கம்
hi|अनइंस्टॉल की सलाह|अनुशंसित|वैकल्पिक|अनुशंसित नहीं|उपयोग न हो तो हटाएँ। निजी डेटा और भविष्य में Store पर उपलब्धता की गारंटी नहीं है।|हार्डवेयर, सुरक्षा, गेमिंग, मीडिया समर्थन या सहेजे गए डेटा पर असर न समझते हों तो इसे रखें।|निजी चुनाव: सुविधाएँ इस्तेमाल करते हैं तो रखें। हटाने से पहले स्थानीय डेटा का बैकअप लें।|BitLocker का स्वचालित डिवाइस एन्क्रिप्शन बंद करें|BitLocker स्वचालित डिवाइस एन्क्रिप्शन
ms|Saranan nyahpasang|Disyorkan|Pilihan|Tidak disyorkan|Buang jika tidak digunakan. Data peribadi dan ketersediaan Store pada masa hadapan tidak dijamin.|Kekalkan kecuali anda memahami kesan terhadap perkakasan, keselamatan, permainan, media atau data tersimpan.|Pilihan peribadi: kekalkan jika menggunakan cirinya. Sandarkan data setempat sebelum membuang.|Lumpuhkan penyulitan peranti automatik BitLocker|Penyulitan Peranti Automatik BitLocker
jv|Saran kanggo mbusak aplikasi|Disaranake|Opsional|Ora disaranake|Busak yen ora dienggo. Data pribadi lan kasedhiyan ing Store mengko ora dijamin.|Tetep simpen kajaba wis ngerti pengaruhe marang piranti keras, keamanan, dolanan, media utawa data sing disimpen.|Pilihan pribadi: simpen yen fiture dienggo. Gawe serep data lokal sadurunge mbusak.|Pateni enkripsi piranti otomatis BitLocker|Enkripsi Piranti Otomatis BitLocker
ban|Saran ngapus aplikasi|Kasaranang|Pilihan|Nenten kasaranang|Apus yening nenten kaanggen. Data pribadi miwah kasayagian Store benjang nenten kajamin.|Tetep simpen kajaba sampun uning pangaruh ring piranti keras, keamanan, game, media utawi data kasimpen.|Pilihan pribadi: simpen yening fiturnyane kaanggen. Cadangang data lokal sadurung ngapus.|Pateni enkripsi piranti otomatis BitLocker|Enkripsi Piranti Otomatis BitLocker
sv|Avinstallationsrekommendation|Rekommenderas|Valfritt|Rekommenderas inte|Ta bort om den inte används. Personliga data och framtida tillgänglighet i Store garanteras inte.|Behåll om du inte förstår påverkan på maskinvara, säkerhet, spel, mediestöd eller sparade data.|Personligt val: behåll appen om du använder funktionerna. Säkerhetskopiera lokala data före borttagning.|Inaktivera automatisk enhetskryptering med BitLocker|Automatisk enhetskryptering med BitLocker
es|Recomendación de desinstalación|Recomendado|Opcional|No recomendado|Elimina si no la usas. No se garantizan los datos personales ni la disponibilidad futura en Store.|Conserva si no comprendes las consecuencias para el hardware, la seguridad, los juegos, los medios o los datos guardados.|Elección personal: conserva la aplicación si la usas. Haz una copia de los datos locales antes de eliminarla.|Desactivar el cifrado automático del dispositivo con BitLocker|Cifrado automático del dispositivo con BitLocker
""";
}
