namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    internal const string OperationOutcomes = """
en|Naufal Windows Powertoys is already running.|Verification did not match the requested state. Actual: {0}|{0} is now {1}.|{0} is now {1}. A reboot is recommended.|{0} is now {1}. Restart Windows before evaluating the result.|{0} is now {1} and all applicable child settings were verified.|APPLIED|RESTORED
id|Naufal Windows Powertoys sudah berjalan.|Hasil verifikasi tidak sesuai dengan kondisi yang diminta. Kondisi aktual: {0}|{0} sekarang {1}.|{0} sekarang {1}. Disarankan memulai ulang komputer.|{0} sekarang {1}. Mulai ulang Windows sebelum menilai hasilnya.|{0} sekarang {1} dan semua pengaturan terkait yang berlaku telah diverifikasi.|DITERAPKAN|DIPULIHKAN
de|Naufal Windows Powertoys wird bereits ausgeführt.|Die Überprüfung stimmt nicht mit dem angeforderten Zustand überein. Tatsächlich: {0}|{0} ist jetzt {1}.|{0} ist jetzt {1}. Ein Neustart wird empfohlen.|{0} ist jetzt {1}. Starten Sie Windows neu, bevor Sie das Ergebnis beurteilen.|{0} ist jetzt {1}; alle anwendbaren untergeordneten Einstellungen wurden überprüft.|ANGEWENDET|WIEDERHERGESTELLT
fr|Naufal Windows Powertoys est déjà en cours d’exécution.|La vérification ne correspond pas à l’état demandé. État réel : {0}|{0} : état actuel — {1}.|{0} : état actuel — {1}. Un redémarrage est recommandé.|{0} : état actuel — {1}. Redémarrez Windows avant d’évaluer le résultat.|{0} : état actuel — {1}. Tous les paramètres associés applicables ont été vérifiés.|APPLIQUÉ|RESTAURÉ
ar|Naufal Windows Powertoys قيد التشغيل بالفعل.|لم تتطابق نتيجة التحقق مع الحالة المطلوبة. الحالة الفعلية: {0}|أصبحت حالة {0}: {1}.|أصبحت حالة {0}: {1}. يُوصى بإعادة التشغيل.|أصبحت حالة {0}: {1}. أعد تشغيل Windows قبل تقييم النتيجة.|أصبحت حالة {0}: {1} وتم التحقق من جميع الإعدادات الفرعية القابلة للتطبيق.|مُطبَّق|مُستعاد
tl|Tumatakbo na ang Naufal Windows Powertoys.|Hindi tumugma ang beripikasyon sa hiniling na kalagayan. Aktuwal: {0}|Ang kalagayan ng {0} ngayon ay {1}.|Ang kalagayan ng {0} ngayon ay {1}. Inirerekomendang i-restart ang computer.|Ang kalagayan ng {0} ngayon ay {1}. I-restart ang Windows bago suriin ang resulta.|Ang kalagayan ng {0} ngayon ay {1} at napatunayan ang lahat ng naaangkop na kaugnay na setting.|NAILAPAT|NAIBALIK
vi|Naufal Windows Powertoys đang chạy.|Kết quả xác minh không khớp trạng thái yêu cầu. Thực tế: {0}|Trạng thái hiện tại của {0}: {1}.|Trạng thái hiện tại của {0}: {1}. Nên khởi động lại máy.|Trạng thái hiện tại của {0}: {1}. Khởi động lại Windows trước khi đánh giá kết quả.|Trạng thái hiện tại của {0}: {1}; tất cả cài đặt con áp dụng được đã được xác minh.|ĐÃ ÁP DỤNG|ĐÃ KHÔI PHỤC
zh-CN|Naufal Windows Powertoys 已在运行。|验证结果与请求的状态不一致。实际状态：{0}|{0} 的当前状态为 {1}。|{0} 的当前状态为 {1}。建议重新启动计算机。|{0} 的当前状态为 {1}。请重新启动 Windows 后再评估结果。|{0} 的当前状态为 {1}，且所有适用的子设置均已验证。|已应用|已还原
zh-TW|Naufal Windows Powertoys 已在執行。|驗證結果與要求的狀態不一致。實際狀態：{0}|{0} 的目前狀態為 {1}。|{0} 的目前狀態為 {1}。建議重新啟動電腦。|{0} 的目前狀態為 {1}。請重新啟動 Windows 後再評估結果。|{0} 的目前狀態為 {1}，且所有適用的子設定均已驗證。|已套用|已還原
th|Naufal Windows Powertoys กำลังทำงานอยู่แล้ว|ผลการตรวจสอบไม่ตรงกับสถานะที่ร้องขอ สถานะจริง: {0}|สถานะปัจจุบันของ {0} คือ {1}|สถานะปัจจุบันของ {0} คือ {1} แนะนำให้รีสตาร์ตคอมพิวเตอร์|สถานะปัจจุบันของ {0} คือ {1} โปรดรีสตาร์ต Windows ก่อนประเมินผล|สถานะปัจจุบันของ {0} คือ {1} และตรวจสอบการตั้งค่าย่อยที่ใช้ได้ทั้งหมดแล้ว|นำไปใช้แล้ว|คืนค่าแล้ว
ru|Naufal Windows Powertoys уже запущен.|Результат проверки не соответствует запрошенному состоянию. Фактическое состояние: {0}|Текущее состояние {0}: {1}.|Текущее состояние {0}: {1}. Рекомендуется перезагрузка.|Текущее состояние {0}: {1}. Перезапустите Windows перед оценкой результата.|Текущее состояние {0}: {1}; все применимые дочерние настройки проверены.|ПРИМЕНЕНО|ВОССТАНОВЛЕНО
uk|Naufal Windows Powertoys уже запущено.|Результат перевірки не відповідає запитаному стану. Фактичний стан: {0}|Поточний стан {0}: {1}.|Поточний стан {0}: {1}. Рекомендовано перезавантаження.|Поточний стан {0}: {1}. Перезапустіть Windows перед оцінюванням результату.|Поточний стан {0}: {1}; усі застосовні дочірні налаштування перевірено.|ЗАСТОСОВАНО|ВІДНОВЛЕНО
pt|Naufal Windows Powertoys já está em execução.|A verificação não correspondeu ao estado pedido. Estado real: {0}|Estado atual de {0}: {1}.|Estado atual de {0}: {1}. Recomenda-se reiniciar o computador.|Estado atual de {0}: {1}. Reinicie o Windows antes de avaliar o resultado.|Estado atual de {0}: {1}; todas as definições subordinadas aplicáveis foram verificadas.|APLICADO|RESTAURADO
ja|Naufal Windows Powertoys は既に実行中です。|検証結果が要求された状態と一致しません。実際の状態: {0}|{0} の現在の状態: {1}。|{0} の現在の状態: {1}。再起動をお勧めします。|{0} の現在の状態: {1}。結果を評価する前に Windows を再起動してください。|{0} の現在の状態: {1}。適用可能なすべての子設定を検証しました。|適用済み|復元済み
ko|Naufal Windows Powertoys가 이미 실행 중입니다.|검증 결과가 요청한 상태와 일치하지 않습니다. 실제 상태: {0}|{0}의 현재 상태: {1}.|{0}의 현재 상태: {1}. 다시 시작하는 것이 좋습니다.|{0}의 현재 상태: {1}. 결과를 평가하기 전에 Windows를 다시 시작하세요.|{0}의 현재 상태: {1}. 적용 가능한 모든 하위 설정을 검증했습니다.|적용됨|복원됨
ur|Naufal Windows Powertoys پہلے سے چل رہا ہے۔|تصدیق کا نتیجہ مطلوبہ حالت سے مطابقت نہیں رکھتا۔ اصل حالت: {0}|{0} کی موجودہ حالت: {1}۔|{0} کی موجودہ حالت: {1}۔ کمپیوٹر دوبارہ شروع کرنے کی تجویز ہے۔|{0} کی موجودہ حالت: {1}۔ نتیجہ جانچنے سے پہلے Windows دوبارہ شروع کریں۔|{0} کی موجودہ حالت: {1}، اور تمام قابلِ اطلاق ذیلی ترتیبات کی تصدیق ہو گئی ہے۔|لاگو شدہ|بحال شدہ
ta|Naufal Windows Powertoys ஏற்கனவே இயங்குகிறது.|சரிபார்ப்பு முடிவு கோரப்பட்ட நிலையுடன் பொருந்தவில்லை. உண்மையான நிலை: {0}|{0} இன் தற்போதைய நிலை: {1}.|{0} இன் தற்போதைய நிலை: {1}. கணினியை மறுதொடக்கம் செய்வது பரிந்துரைக்கப்படுகிறது.|{0} இன் தற்போதைய நிலை: {1}. முடிவை மதிப்பிடுவதற்கு முன் Windows ஐ மறுதொடக்கம் செய்யவும்.|{0} இன் தற்போதைய நிலை: {1}; பொருந்தக்கூடிய அனைத்து துணை அமைப்புகளும் சரிபார்க்கப்பட்டன.|பயன்படுத்தப்பட்டது|மீட்டமைக்கப்பட்டது
hi|Naufal Windows Powertoys पहले से चल रहा है।|सत्यापन का परिणाम अनुरोधित स्थिति से मेल नहीं खाता। वास्तविक स्थिति: {0}|{0} की वर्तमान स्थिति: {1}।|{0} की वर्तमान स्थिति: {1}। कंप्यूटर पुनः आरंभ करने की सलाह दी जाती है।|{0} की वर्तमान स्थिति: {1}। परिणाम का मूल्यांकन करने से पहले Windows पुनः आरंभ करें।|{0} की वर्तमान स्थिति: {1}; सभी लागू उप-सेटिंग्स सत्यापित कर ली गई हैं।|लागू किया गया|पुनर्स्थापित किया गया
ms|Naufal Windows Powertoys sudah berjalan.|Hasil pengesahan tidak sepadan dengan keadaan yang diminta. Keadaan sebenar: {0}|Keadaan semasa {0}: {1}.|Keadaan semasa {0}: {1}. Komputer disyorkan dimulakan semula.|Keadaan semasa {0}: {1}. Mulakan semula Windows sebelum menilai hasilnya.|Keadaan semasa {0}: {1}; semua tetapan berkaitan yang berkenaan telah disahkan.|DIGUNAKAN|DIPULIHKAN
jv|Naufal Windows Powertoys wis mlaku.|Asil verifikasi ora cocog karo kahanan sing dijaluk. Kahanan nyata: {0}|Kahanan {0} saiki: {1}.|Kahanan {0} saiki: {1}. Disaranake miwiti komputer maneh.|Kahanan {0} saiki: {1}. Wiwiti Windows maneh sadurunge mriksa asile.|Kahanan {0} saiki: {1}; kabeh setelan turunan sing bisa ditrapake wis diverifikasi.|DITRAPAKE|DIPULIHAKE
ban|Naufal Windows Powertoys sampun majalan.|Asil verifikasi nénten manut ring kawentenan sane katunas. Kawentenan nyata: {0}|Kawentenan {0} mangkin: {1}.|Kawentenan {0} mangkin: {1}. Kasaranang ngawitin komputer malih.|Kawentenan {0} mangkin: {1}. Wiwitin Windows malih sadurung nilain asilnyané.|Kawentenan {0} mangkin: {1}; samian setelan turunan sane prasida kalarap sampun kaverifikasi.|KALARAP|KAPULIHANG
sv|Naufal Windows Powertoys körs redan.|Verifieringen matchade inte det begärda tillståndet. Faktiskt tillstånd: {0}|Aktuellt tillstånd för {0}: {1}.|Aktuellt tillstånd för {0}: {1}. En omstart rekommenderas.|Aktuellt tillstånd för {0}: {1}. Starta om Windows innan du utvärderar resultatet.|Aktuellt tillstånd för {0}: {1}; alla tillämpliga underordnade inställningar har verifierats.|TILLÄMPAT|ÅTERSTÄLLT
es|Naufal Windows Powertoys ya se está ejecutando.|La verificación no coincide con el estado solicitado. Estado real: {0}|Estado actual de {0}: {1}.|Estado actual de {0}: {1}. Se recomienda reiniciar el equipo.|Estado actual de {0}: {1}. Reinicie Windows antes de evaluar el resultado.|Estado actual de {0}: {1}; se verificaron todos los ajustes secundarios aplicables.|APLICADO|RESTAURADO
""";
}
