namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string AvailabilityReasons = """
en|Reserved Storage control is not available on this Windows build.|NVIDIA ShadowPlay key is absent|This NVIDIA overlay registry target is not present on this PC.|The related application or startup entry is not present.|No matching service is installed|This service group is not installed on this PC.|Registry key absent|Classic context registry key present|12 registry policies, DiagTrack/WerSvc, and PowerShell telemetry opt-out match|CscService/DiagTrack disabled; MapsBroker/StorSvc manual; SharedAccess disabled; split threshold present|Windows Web Experience/Widgets packages are not registered for this user|SysMain is not installed.
id|Kontrol Reserved Storage tidak tersedia pada build Windows ini.|Kunci NVIDIA ShadowPlay tidak ada|Target registri overlay NVIDIA ini tidak ada di PC ini.|Aplikasi atau entri startup terkait tidak ada.|Tidak ada layanan yang cocok terinstal|Grup layanan ini tidak terinstal di PC ini.|Kunci registri tidak ada|Kunci registri menu konteks klasik ada|12 kebijakan registri, DiagTrack/WerSvc, dan penolakan telemetri PowerShell sesuai|CscService/DiagTrack dinonaktifkan; MapsBroker/StorSvc manual; SharedAccess dinonaktifkan; ambang pemisahan ada|Paket Windows Web Experience/Widgets tidak terdaftar untuk pengguna ini|SysMain tidak terinstal.
de|Die Steuerung von Reserved Storage ist in diesem Windows-Build nicht verfügbar.|Der Schlüssel für NVIDIA ShadowPlay fehlt|Dieser Registrierungszielpfad für das NVIDIA-Overlay ist auf diesem PC nicht vorhanden.|Die zugehörige Anwendung oder der Autostarteintrag ist nicht vorhanden.|Kein passender Dienst ist installiert|Diese Dienstgruppe ist auf diesem PC nicht installiert.|Registrierungsschlüssel fehlt|Registrierungsschlüssel für das klassische Kontextmenü vorhanden|12 Registrierungsrichtlinien, DiagTrack/WerSvc und die Deaktivierung der PowerShell-Telemetrie stimmen überein|CscService/DiagTrack deaktiviert; MapsBroker/StorSvc manuell; SharedAccess deaktiviert; Trennschwellenwert vorhanden|Windows Web Experience/Widgets-Pakete sind für diesen Benutzer nicht registriert|SysMain ist nicht installiert.
fr|Le contrôle de Reserved Storage n’est pas disponible dans cette version de Windows.|La clé NVIDIA ShadowPlay est absente|Cette cible de registre de la superposition NVIDIA n’est pas présente sur ce PC.|L’application ou l’entrée de démarrage associée est absente.|Aucun service correspondant n’est installé|Ce groupe de services n’est pas installé sur ce PC.|Clé de registre absente|Clé de registre du menu contextuel classique présente|12 stratégies de registre, DiagTrack/WerSvc et le refus de la télémétrie PowerShell correspondent|CscService/DiagTrack désactivés ; MapsBroker/StorSvc manuels ; SharedAccess désactivé ; seuil de séparation présent|Les packages Windows Web Experience/Widgets ne sont pas enregistrés pour cet utilisateur|SysMain n’est pas installé.
ar|التحكم في Reserved Storage غير متاح في هذا الإصدار من Windows.|مفتاح NVIDIA ShadowPlay غير موجود|هدف السجل الخاص بتراكب NVIDIA غير موجود على هذا الكمبيوتر.|التطبيق أو إدخال بدء التشغيل المرتبط غير موجود.|لا توجد خدمة مطابقة مثبتة|مجموعة الخدمات هذه غير مثبتة على هذا الكمبيوتر.|مفتاح السجل غير موجود|مفتاح سجل قائمة السياق الكلاسيكية موجود|تتطابق 12 سياسة سجل وDiagTrack/WerSvc وإلغاء الاشتراك في بيانات تتبع الاستخدام في PowerShell|CscService/DiagTrack معطّلان؛ MapsBroker/StorSvc يدويان؛ SharedAccess معطّل؛ حد الفصل موجود|حزم Windows Web Experience/Widgets غير مسجلة لهذا المستخدم|SysMain غير مثبت.
tl|Hindi available ang kontrol ng Reserved Storage sa build na ito ng Windows.|Wala ang key ng NVIDIA ShadowPlay|Wala sa PC na ito ang target sa registry para sa NVIDIA overlay.|Wala ang kaugnay na application o entry sa pagsisimula.|Walang naka-install na katugmang serbisyo|Hindi naka-install sa PC na ito ang pangkat ng mga serbisyong ito.|Wala ang registry key|Naroon ang registry key ng klasikong menu ng konteksto|Tugma ang 12 patakaran sa registry, DiagTrack/WerSvc, at pagtanggi sa telemetry ng PowerShell|Hindi pinagana ang CscService/DiagTrack; manwal ang MapsBroker/StorSvc; hindi pinagana ang SharedAccess; naroon ang hangganan ng paghahati|Hindi nakarehistro para sa user na ito ang mga package ng Windows Web Experience/Widgets|Hindi naka-install ang SysMain.
vi|Không có chức năng điều khiển Reserved Storage trên bản dựng Windows này.|Không có khóa NVIDIA ShadowPlay|Không có mục đăng ký đích của lớp phủ NVIDIA này trên PC này.|Không có ứng dụng hoặc mục khởi động liên quan.|Không có dịch vụ phù hợp nào được cài đặt|Nhóm dịch vụ này chưa được cài đặt trên PC này.|Không có khóa sổ đăng ký|Có khóa sổ đăng ký cho menu ngữ cảnh cổ điển|12 chính sách sổ đăng ký, DiagTrack/WerSvc và thiết lập từ chối dữ liệu đo từ xa của PowerShell đều khớp|CscService/DiagTrack bị vô hiệu hóa; MapsBroker/StorSvc ở chế độ thủ công; SharedAccess bị vô hiệu hóa; có ngưỡng tách|Các gói Windows Web Experience/Widgets chưa được đăng ký cho người dùng này|SysMain chưa được cài đặt.
zh-CN|此 Windows 版本不提供 Reserved Storage 控制功能。|NVIDIA ShadowPlay 键不存在|此电脑上不存在此 NVIDIA 叠加层注册表目标。|相关应用或启动项不存在。|未安装匹配的服务|此电脑上未安装此服务组。|注册表键不存在|经典上下文菜单的注册表键存在|12 项注册表策略、DiagTrack/WerSvc 和 PowerShell 遥测退出设置均匹配|CscService/DiagTrack 已禁用；MapsBroker/StorSvc 为手动；SharedAccess 已禁用；拆分阈值存在|尚未为此用户注册 Windows Web Experience/Widgets 程序包|未安装 SysMain。
zh-TW|此 Windows 組建不提供 Reserved Storage 控制功能。|NVIDIA ShadowPlay 機碼不存在|此電腦上不存在此 NVIDIA 覆疊的登錄目標。|相關應用程式或啟動項目不存在。|未安裝相符的服務|此電腦上未安裝此服務群組。|登錄機碼不存在|傳統快顯功能表的登錄機碼存在|12 項登錄原則、DiagTrack/WerSvc 與 PowerShell 遙測退出設定均相符|CscService/DiagTrack 已停用；MapsBroker/StorSvc 為手動；SharedAccess 已停用；分割閾值存在|尚未為此使用者註冊 Windows Web Experience/Widgets 套件|未安裝 SysMain。
th|ไม่มีการควบคุม Reserved Storage ใน Windows รุ่นนี้|ไม่มีคีย์ NVIDIA ShadowPlay|ไม่มีเป้าหมายรีจิสทรีของโอเวอร์เลย์ NVIDIA นี้บนพีซีเครื่องนี้|ไม่มีแอปพลิเคชันหรือรายการเริ่มต้นระบบที่เกี่ยวข้อง|ไม่มีบริการที่ตรงกันติดตั้งอยู่|ไม่ได้ติดตั้งกลุ่มบริการนี้บนพีซีเครื่องนี้|ไม่มีคีย์รีจิสทรี|มีคีย์รีจิสทรีของเมนูบริบทแบบคลาสสิก|นโยบายรีจิสทรี 12 รายการ, DiagTrack/WerSvc และการเลือกไม่ส่งข้อมูลการวัดและส่งข้อมูลทางไกลของ PowerShell ตรงกัน|CscService/DiagTrack ถูกปิดใช้งาน; MapsBroker/StorSvc เป็นแบบกำหนดเอง; SharedAccess ถูกปิดใช้งาน; มีค่าเกณฑ์การแยก|แพ็กเกจ Windows Web Experience/Widgets ไม่ได้ลงทะเบียนสำหรับผู้ใช้นี้|ไม่ได้ติดตั้ง SysMain
ru|Управление Reserved Storage недоступно в этой сборке Windows.|Раздел NVIDIA ShadowPlay отсутствует|Этот целевой раздел реестра оверлея NVIDIA отсутствует на этом ПК.|Связанное приложение или запись автозагрузки отсутствует.|Подходящая служба не установлена|Эта группа служб не установлена на этом ПК.|Раздел реестра отсутствует|Раздел реестра классического контекстного меню присутствует|12 политик реестра, DiagTrack/WerSvc и отказ от телеметрии PowerShell соответствуют ожидаемому состоянию|CscService/DiagTrack отключены; MapsBroker/StorSvc запускаются вручную; SharedAccess отключена; порог разделения присутствует|Пакеты Windows Web Experience/Widgets не зарегистрированы для этого пользователя|SysMain не установлена.
uk|Керування Reserved Storage недоступне в цій збірці Windows.|Розділ NVIDIA ShadowPlay відсутній|Цей цільовий розділ реєстру накладання NVIDIA відсутній на цьому ПК.|Пов’язана програма або запис автозапуску відсутні.|Відповідну службу не встановлено|Цю групу служб не встановлено на цьому ПК.|Розділ реєстру відсутній|Розділ реєстру класичного контекстного меню наявний|12 політик реєстру, DiagTrack/WerSvc і відмова від телеметрії PowerShell відповідають очікуваному стану|CscService/DiagTrack вимкнено; MapsBroker/StorSvc запускаються вручну; SharedAccess вимкнено; поріг розділення наявний|Пакети Windows Web Experience/Widgets не зареєстровані для цього користувача|SysMain не встановлено.
pt|O controle de Reserved Storage não está disponível nesta compilação do Windows.|A chave NVIDIA ShadowPlay está ausente|Este destino de registro da sobreposição NVIDIA não está presente neste PC.|O aplicativo ou a entrada de inicialização relacionada não está presente.|Nenhum serviço correspondente está instalado|Este grupo de serviços não está instalado neste PC.|Chave do registro ausente|Chave do registro do menu de contexto clássico presente|12 políticas do registro, DiagTrack/WerSvc e a recusa da telemetria do PowerShell correspondem|CscService/DiagTrack desativados; MapsBroker/StorSvc manuais; SharedAccess desativado; limite de divisão presente|Os pacotes Windows Web Experience/Widgets não estão registrados para este usuário|SysMain não está instalado.
ja|この Windows ビルドでは Reserved Storage を制御できません。|NVIDIA ShadowPlay キーがありません|この PC には、NVIDIA オーバーレイのこのレジストリ対象がありません。|関連するアプリまたはスタートアップ項目がありません。|該当するサービスがインストールされていません|この PC には、このサービスグループがインストールされていません。|レジストリキーがありません|従来のコンテキストメニューのレジストリキーがあります|12 個のレジストリポリシー、DiagTrack/WerSvc、および PowerShell テレメトリのオプトアウトが一致しています|CscService/DiagTrack は無効、MapsBroker/StorSvc は手動、SharedAccess は無効、分割しきい値は存在|このユーザーには Windows Web Experience/Widgets パッケージが登録されていません|SysMain がインストールされていません。
ko|이 Windows 빌드에서는 Reserved Storage를 제어할 수 없습니다.|NVIDIA ShadowPlay 키가 없음|이 PC에는 이 NVIDIA 오버레이 레지스트리 대상이 없습니다.|관련 앱 또는 시작 항목이 없습니다.|일치하는 서비스가 설치되어 있지 않음|이 PC에는 이 서비스 그룹이 설치되어 있지 않습니다.|레지스트리 키가 없음|클래식 상황에 맞는 메뉴의 레지스트리 키가 있음|레지스트리 정책 12개, DiagTrack/WerSvc 및 PowerShell 원격 분석 거부 설정이 일치함|CscService/DiagTrack 사용 안 함; MapsBroker/StorSvc 수동; SharedAccess 사용 안 함; 분할 임계값 있음|이 사용자에게 Windows Web Experience/Widgets 패키지가 등록되어 있지 않음|SysMain이 설치되어 있지 않습니다.
ur|Windows کی اس بلڈ میں Reserved Storage کا کنٹرول دستیاب نہیں ہے۔|NVIDIA ShadowPlay کی رجسٹری کلید موجود نہیں|اس PC پر NVIDIA اوورلے کا یہ رجسٹری ہدف موجود نہیں ہے۔|متعلقہ ایپلیکیشن یا آغاز کی اندراج موجود نہیں ہے۔|کوئی مماثل سروس انسٹال نہیں ہے|اس PC پر سروسز کا یہ گروپ انسٹال نہیں ہے۔|رجسٹری کلید موجود نہیں|کلاسیکی سیاقی مینو کی رجسٹری کلید موجود ہے|12 رجسٹری پالیسیاں، DiagTrack/WerSvc، اور PowerShell ٹیلی میٹری سے دستبرداری مطابقت رکھتے ہیں|CscService/DiagTrack غیر فعال؛ MapsBroker/StorSvc دستی؛ SharedAccess غیر فعال؛ تقسیم کی حد موجود|اس صارف کے لیے Windows Web Experience/Widgets پیکیجز رجسٹرڈ نہیں ہیں|SysMain انسٹال نہیں ہے۔
ta|இந்த Windows உருவாக்கத்தில் Reserved Storage கட்டுப்பாடு கிடைக்கவில்லை.|NVIDIA ShadowPlay விசை இல்லை|இந்தக் கணினியில் இந்த NVIDIA மேலடுக்குப் பதிவக இலக்கு இல்லை.|தொடர்புடைய பயன்பாடு அல்லது தொடக்கப் பதிவு இல்லை.|பொருந்தும் சேவை எதுவும் நிறுவப்படவில்லை|இந்தக் கணினியில் இந்தச் சேவைக் குழு நிறுவப்படவில்லை.|பதிவக விசை இல்லை|பழைய சூழல் மெனுவின் பதிவக விசை உள்ளது|12 பதிவகக் கொள்கைகள், DiagTrack/WerSvc மற்றும் PowerShell தொலைஅளவீட்டு விலகல் அமைப்பு பொருந்துகின்றன|CscService/DiagTrack முடக்கப்பட்டுள்ளன; MapsBroker/StorSvc கைமுறை; SharedAccess முடக்கப்பட்டுள்ளது; பிரிப்பு வரம்பு உள்ளது|இந்தப் பயனருக்கு Windows Web Experience/Widgets தொகுப்புகள் பதிவு செய்யப்படவில்லை|SysMain நிறுவப்படவில்லை.
hi|Windows के इस बिल्ड में Reserved Storage का नियंत्रण उपलब्ध नहीं है।|NVIDIA ShadowPlay कुंजी मौजूद नहीं है|इस PC पर NVIDIA ओवरले का यह रजिस्ट्री लक्ष्य मौजूद नहीं है।|संबंधित ऐप या स्टार्टअप प्रविष्टि मौजूद नहीं है।|कोई मेल खाती सेवा इंस्टॉल नहीं है|इस PC पर यह सेवा समूह इंस्टॉल नहीं है।|रजिस्ट्री कुंजी मौजूद नहीं है|क्लासिक संदर्भ मेनू की रजिस्ट्री कुंजी मौजूद है|12 रजिस्ट्री नीतियाँ, DiagTrack/WerSvc और PowerShell टेलीमेट्री से बाहर रहने की सेटिंग मेल खाती हैं|CscService/DiagTrack अक्षम; MapsBroker/StorSvc मैन्युअल; SharedAccess अक्षम; विभाजन सीमा मौजूद|इस उपयोगकर्ता के लिए Windows Web Experience/Widgets पैकेज पंजीकृत नहीं हैं|SysMain इंस्टॉल नहीं है।
ms|Kawalan Reserved Storage tidak tersedia pada binaan Windows ini.|Kunci NVIDIA ShadowPlay tiada|Sasaran daftaran tindanan NVIDIA ini tiada pada PC ini.|Aplikasi atau entri permulaan berkaitan tiada.|Tiada perkhidmatan sepadan dipasang|Kumpulan perkhidmatan ini tidak dipasang pada PC ini.|Kunci daftaran tiada|Kunci daftaran menu konteks klasik ada|12 dasar daftaran, DiagTrack/WerSvc dan penolakan telemetri PowerShell sepadan|CscService/DiagTrack dilumpuhkan; MapsBroker/StorSvc manual; SharedAccess dilumpuhkan; ambang pemisahan ada|Pakej Windows Web Experience/Widgets tidak didaftarkan untuk pengguna ini|SysMain tidak dipasang.
jv|Kontrol Reserved Storage ora kasedhiya ing build Windows iki.|Kunci NVIDIA ShadowPlay ora ana|Target registri overlay NVIDIA iki ora ana ing PC iki.|Aplikasi utawa entri wiwitan sing gegandhengan ora ana.|Ora ana layanan sing cocog sing dipasang|Klompok layanan iki ora dipasang ing PC iki.|Kunci registri ora ana|Kunci registri menu konteks klasik ana|12 kabijakan registri, DiagTrack/WerSvc, lan pilihan nolak telemetri PowerShell cocog|CscService/DiagTrack dipateni; MapsBroker/StorSvc manual; SharedAccess dipateni; wates pamisahan ana|Paket Windows Web Experience/Widgets ora kadhaptar kanggo pangguna iki|SysMain ora dipasang.
ban|Kontrol Reserved Storage nénten wénten ring build Windows puniki.|Kunci NVIDIA ShadowPlay nénten wénten|Target registri overlay NVIDIA puniki nénten wénten ring PC puniki.|Aplikasi utawi entri pangawit sané mapaiketan nénten wénten.|Nénten wénten layanan sané cocok sané sampun kapasang|Pupulan layanan puniki nénten kapasang ring PC puniki.|Kunci registri nénten wénten|Kunci registri menu konteks klasik wénten|12 kawicaksanan registri, DiagTrack/WerSvc, miwah pilihan nolak telemetri PowerShell sampun cocok|CscService/DiagTrack kamatiang; MapsBroker/StorSvc manual; SharedAccess kamatiang; wates pamisahan wénten|Paket Windows Web Experience/Widgets nénten kadaftar antuk panganggé puniki|SysMain nénten kapasang.
sv|Styrning av Reserved Storage är inte tillgänglig i denna Windows-version.|Nyckeln för NVIDIA ShadowPlay saknas|Det här registermålet för NVIDIA-överlägget finns inte på denna dator.|Den tillhörande appen eller autostartposten saknas.|Ingen matchande tjänst är installerad|Den här tjänstegruppen är inte installerad på denna dator.|Registernyckel saknas|Registernyckel för den klassiska snabbmenyn finns|12 registerprinciper, DiagTrack/WerSvc och avböjd PowerShell-telemetri stämmer överens|CscService/DiagTrack inaktiverade; MapsBroker/StorSvc manuella; SharedAccess inaktiverad; delningströskel finns|Windows Web Experience/Widgets-paketen är inte registrerade för den här användaren|SysMain är inte installerad.
es|El control de Reserved Storage no está disponible en esta compilación de Windows.|No existe la clave de NVIDIA ShadowPlay|Este destino del registro de la superposición de NVIDIA no está presente en este PC.|La aplicación o la entrada de inicio relacionada no está presente.|No hay ningún servicio coincidente instalado|Este grupo de servicios no está instalado en este PC.|No existe la clave del registro|Existe la clave del registro del menú contextual clásico|Coinciden las 12 directivas del registro, DiagTrack/WerSvc y la exclusión de la telemetría de PowerShell|CscService/DiagTrack deshabilitados; MapsBroker/StorSvc manuales; SharedAccess deshabilitado; umbral de división presente|Los paquetes de Windows Web Experience/Widgets no están registrados para este usuario|SysMain no está instalado.
""";
}
