namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    internal const string AboutDescription = "Naufal Windows Powertoys is an open-source Windows system utility designed to simplify system maintenance, troubleshooting, optimization, gaming configuration, driver management, runtime compatibility, and access to advanced Windows tools through a unified interface.";
    internal const string AboutPurpose = "The application brings commonly used repair, maintenance, configuration, diagnostic, and advanced Windows functions together in one place, with clear status information and guided controls for both everyday and advanced users.";
    internal const string AboutContent = """
en|About|Developed by|Open-Source Software|Licensed under the MIT License|Source Code|Version {0}|Naufal Windows Powertoys is an open-source Windows system utility designed to simplify system maintenance, troubleshooting, optimization, gaming configuration, driver management, runtime compatibility, and access to advanced Windows tools through a unified interface.|The application brings commonly used repair, maintenance, configuration, diagnostic, and advanced Windows functions together in one place, with clear status information and guided controls for both everyday and advanced users.
id|Tentang|Dikembangkan oleh|Perangkat Lunak Sumber Terbuka|Dilisensikan berdasarkan MIT License|Kode Sumber|Versi {0}|Naufal Windows Powertoys adalah utilitas sistem Windows sumber terbuka yang dirancang untuk mempermudah pemeliharaan sistem, pemecahan masalah, optimasi, konfigurasi game, pengelolaan driver, kompatibilitas runtime, dan akses ke alat Windows tingkat lanjut melalui satu antarmuka.|Aplikasi ini menyatukan fungsi perbaikan, pemeliharaan, konfigurasi, diagnostik, dan fungsi Windows tingkat lanjut yang umum digunakan, dengan informasi status yang jelas serta kontrol terpandu untuk pengguna sehari-hari maupun tingkat lanjut.
de|Über|Entwickelt von|Open-Source-Software|Lizenziert unter der MIT License|Quellcode|Version {0}|Naufal Windows Powertoys ist ein quelloffenes Windows-Systemwerkzeug, das Systemwartung, Fehlerbehebung, Optimierung, Spielekonfiguration, Treiberverwaltung, Laufzeitkompatibilität und den Zugriff auf erweiterte Windows-Werkzeuge über eine einheitliche Oberfläche vereinfacht.|Die Anwendung vereint häufig verwendete Reparatur-, Wartungs-, Konfigurations-, Diagnose- und erweiterte Windows-Funktionen an einem Ort. Klare Statusinformationen und geführte Bedienelemente unterstützen sowohl alltägliche als auch fortgeschrittene Nutzer.
fr|À propos|Développé par|Logiciel libre|Sous licence MIT License|Code source|Version {0}|Naufal Windows Powertoys est un utilitaire système Windows à code source ouvert conçu pour simplifier la maintenance, le dépannage, l’optimisation, la configuration des jeux, la gestion des pilotes, la compatibilité des environnements d’exécution et l’accès aux outils Windows avancés dans une interface unifiée.|L’application rassemble les fonctions courantes de réparation, maintenance, configuration, diagnostic et les fonctions Windows avancées, avec des informations d’état claires et des commandes guidées pour les utilisateurs occasionnels comme expérimentés.
ar|حول|طوّره|برنامج مفتوح المصدر|مرخّص بموجب MIT License|الشيفرة المصدرية|الإصدار {0}|Naufal Windows Powertoys أداة نظام Windows مفتوحة المصدر صُممت لتبسيط صيانة النظام واستكشاف الأخطاء وإصلاحها والتحسين وإعداد الألعاب وإدارة برامج التشغيل وتوافق بيئات التشغيل والوصول إلى أدوات Windows المتقدمة عبر واجهة موحدة.|يجمع التطبيق وظائف إصلاح Windows وصيانته وإعداده وتشخيصه ووظائفه المتقدمة الشائعة في مكان واحد، مع معلومات حالة واضحة وعناصر تحكم إرشادية للمستخدمين العاديين والمتقدمين.
tl|Tungkol dito|Binuo ni|Software na Bukas ang Source Code|Lisensiyado sa ilalim ng MIT License|Kodigo ng Programa|Bersyon {0}|Ang Naufal Windows Powertoys ay isang bukas ang source code na kasangkapang pangsistema para sa Windows na nagpapadali ng pagpapanatili, pag-aayos ng problema, pag-optimize, pagsasaayos ng laro, pamamahala ng driver, pagiging tugma ng runtime, at pag-access sa mga advanced na kasangkapan ng Windows sa iisang interface.|Pinagsasama ng app sa iisang lugar ang karaniwang pag-aayos, pagpapanatili, pagsasaayos, pagsusuri, at mga advanced na gawain ng Windows, na may malinaw na impormasyon sa kalagayan at mga gabay na kontrol para sa pang-araw-araw at bihasang gumagamit.
vi|Giới thiệu|Được phát triển bởi|Phần mềm mã nguồn mở|Được cấp phép theo MIT License|Mã nguồn|Phiên bản {0}|Naufal Windows Powertoys là tiện ích hệ thống Windows mã nguồn mở, được thiết kế để đơn giản hóa bảo trì hệ thống, khắc phục sự cố, tối ưu hóa, cấu hình trò chơi, quản lý trình điều khiển, khả năng tương thích môi trường chạy và truy cập các công cụ Windows nâng cao thông qua giao diện thống nhất.|Ứng dụng tập hợp các chức năng sửa chữa, bảo trì, cấu hình, chẩn đoán và chức năng Windows nâng cao thường dùng vào một nơi, với thông tin trạng thái rõ ràng và các thao tác có hướng dẫn cho cả người dùng thông thường và nâng cao.
zh-CN|关于|开发者|开源软件|根据 MIT License 授权|源代码|版本 {0}|Naufal Windows Powertoys 是一款开源 Windows 系统工具，通过统一界面简化系统维护、故障排查、优化、游戏配置、驱动程序管理、运行时兼容性处理以及高级 Windows 工具的访问。|本应用将常用的修复、维护、配置、诊断和高级 Windows 功能集中在一处，为日常用户和高级用户提供清晰的状态信息与引导式操作。
zh-TW|關於|開發者|開放原始碼軟體|依 MIT License 授權|原始碼|版本 {0}|Naufal Windows Powertoys 是一款開放原始碼的 Windows 系統工具，透過統一介面簡化系統維護、疑難排解、最佳化、遊戲設定、驅動程式管理、執行階段相容性處理，以及進階 Windows 工具的存取。|本應用程式將常用的修復、維護、設定、診斷和進階 Windows 功能集中於一處，為一般及進階使用者提供清楚的狀態資訊與引導式操作。
th|เกี่ยวกับ|พัฒนาโดย|ซอฟต์แวร์โอเพนซอร์ส|อนุญาตให้ใช้ภายใต้ MIT License|ซอร์สโค้ด|เวอร์ชัน {0}|Naufal Windows Powertoys เป็นเครื่องมือระบบ Windows แบบโอเพนซอร์สที่ออกแบบมาเพื่อช่วยให้การบำรุงรักษาระบบ การแก้ไขปัญหา การปรับประสิทธิภาพ การตั้งค่าเกม การจัดการไดรเวอร์ ความเข้ากันได้ของรันไทม์ และการเข้าถึงเครื่องมือ Windows ขั้นสูงทำได้ง่ายขึ้นผ่านอินเทอร์เฟซเดียวกัน|แอปรวมฟังก์ชันซ่อมแซม บำรุงรักษา ตั้งค่า วินิจฉัย และฟังก์ชัน Windows ขั้นสูงที่ใช้บ่อยไว้ในที่เดียว พร้อมข้อมูลสถานะที่ชัดเจนและตัวควบคุมที่มีคำแนะนำสำหรับทั้งผู้ใช้ทั่วไปและผู้ใช้ขั้นสูง
ru|О программе|Разработчик|Программное обеспечение с открытым исходным кодом|Лицензировано по MIT License|Исходный код|Версия {0}|Naufal Windows Powertoys — системная утилита Windows с открытым исходным кодом, которая упрощает обслуживание, устранение неполадок, оптимизацию, настройку игр, управление драйверами, обеспечение совместимости сред выполнения и доступ к расширенным инструментам Windows через единый интерфейс.|Приложение объединяет часто используемые функции восстановления, обслуживания, настройки, диагностики и расширенные функции Windows, предоставляя понятную информацию о состоянии и пошаговые элементы управления как обычным, так и опытным пользователям.
uk|Про програму|Розробник|Програмне забезпечення з відкритим кодом|Ліцензовано за MIT License|Вихідний код|Версія {0}|Naufal Windows Powertoys — системна утиліта Windows з відкритим кодом, створена для спрощення обслуговування, усунення несправностей, оптимізації, налаштування ігор, керування драйверами, забезпечення сумісності середовищ виконання та доступу до розширених засобів Windows через єдиний інтерфейс.|Програма об’єднує поширені функції відновлення, обслуговування, налаштування, діагностики та розширені функції Windows, надаючи зрозумілі відомості про стан і керовані підказками дії як звичайним, так і досвідченим користувачам.
pt|Sobre|Desenvolvido por|Software de código aberto|Licenciado sob a MIT License|Código-fonte|Versão {0}|Naufal Windows Powertoys é um utilitário de sistema Windows de código aberto, concebido para simplificar a manutenção, resolução de problemas, otimização, configuração de jogos, gestão de controladores, compatibilidade de ambientes de execução e acesso a ferramentas avançadas do Windows através de uma interface unificada.|A aplicação reúne num só lugar funções comuns de reparação, manutenção, configuração, diagnóstico e funções avançadas do Windows, com informações de estado claras e controlos orientados tanto para utilizadores comuns como avançados.
ja|このアプリについて|開発者|オープンソースソフトウェア|MIT License に基づくライセンス|ソースコード|バージョン {0}|Naufal Windows Powertoys は、統一されたインターフェイスを通じて、システムの保守、トラブルシューティング、最適化、ゲーム設定、ドライバー管理、ランタイムの互換性対応、高度な Windows ツールへのアクセスを簡単にするオープンソースの Windows システムユーティリティです。|よく使う修復、保守、設定、診断、高度な Windows 機能を一か所にまとめ、日常的なユーザーにも上級ユーザーにも、わかりやすい状態情報と案内付きの操作を提供します。
ko|정보|개발자|오픈 소스 소프트웨어|MIT License에 따라 사용 허가됨|소스 코드|버전 {0}|Naufal Windows Powertoys는 통합된 인터페이스를 통해 시스템 유지 관리, 문제 해결, 최적화, 게임 설정, 드라이버 관리, 런타임 호환성 처리 및 고급 Windows 도구 접근을 간소화하도록 설계된 오픈 소스 Windows 시스템 유틸리티입니다.|이 앱은 자주 사용하는 복구, 유지 관리, 설정, 진단 및 고급 Windows 기능을 한곳에 모아 일반 사용자와 고급 사용자 모두에게 명확한 상태 정보와 안내가 있는 조작 기능을 제공합니다.
ur|تعارف|تیار کنندہ|اوپن سورس سافٹ ویئر|MIT License کے تحت لائسنس یافتہ|ماخذ کوڈ|ورژن {0}|Naufal Windows Powertoys ایک اوپن سورس Windows نظامی سہولت ہے جو ایک متحد انٹرفیس کے ذریعے نظام کی دیکھ بھال، مسائل کا حل، کارکردگی میں بہتری، گیم کی ترتیب، ڈرائیور کا انتظام، رن ٹائم مطابقت اور جدید Windows ٹولز تک رسائی آسان بنانے کے لیے تیار کی گئی ہے۔|یہ ایپ عام مرمت، دیکھ بھال، ترتیب، تشخیص اور جدید Windows افعال کو ایک جگہ جمع کرتی ہے، اور عام و ماہر صارفین کے لیے واضح حالت کی معلومات اور رہنمائی والے کنٹرول فراہم کرتی ہے۔
ta|பற்றி|உருவாக்கியவர்|திறந்த மூல மென்பொருள்|MIT License இன் கீழ் உரிமம் பெற்றது|மூலக் குறியீடு|பதிப்பு {0}|Naufal Windows Powertoys என்பது திறந்த மூல Windows கணினிப் பயன்பாடாகும். ஒருங்கிணைந்த இடைமுகம் மூலம் கணினிப் பராமரிப்பு, சிக்கல் தீர்வு, மேம்படுத்தல், விளையாட்டு அமைப்பு, இயக்கி மேலாண்மை, இயக்கநேர இணக்கத்தன்மை மற்றும் மேம்பட்ட Windows கருவிகளுக்கான அணுகலை எளிதாக்க இது வடிவமைக்கப்பட்டுள்ளது.|அடிக்கடி பயன்படுத்தப்படும் பழுதுபார்ப்பு, பராமரிப்பு, அமைப்பு, கண்டறிதல் மற்றும் மேம்பட்ட Windows செயல்பாடுகளை இப்பயன்பாடு ஒரே இடத்தில் இணைக்கிறது. சாதாரண மற்றும் மேம்பட்ட பயனர்களுக்கு தெளிவான நிலைத் தகவலையும் வழிகாட்டப்பட்ட கட்டுப்பாடுகளையும் வழங்குகிறது.
hi|परिचय|विकसित किया|ओपन-सोर्स सॉफ़्टवेयर|MIT License के अंतर्गत लाइसेंस प्राप्त|स्रोत कोड|संस्करण {0}|Naufal Windows Powertoys एक ओपन-सोर्स Windows सिस्टम उपयोगिता है, जिसे एक एकीकृत इंटरफ़ेस से सिस्टम रखरखाव, समस्या निवारण, अनुकूलन, गेम कॉन्फ़िगरेशन, ड्राइवर प्रबंधन, रनटाइम संगतता और उन्नत Windows उपकरणों तक पहुँच आसान बनाने के लिए बनाया गया है।|यह ऐप सामान्य मरम्मत, रखरखाव, कॉन्फ़िगरेशन, निदान और उन्नत Windows कार्यों को एक जगह लाता है, जिसमें सामान्य और उन्नत दोनों उपयोगकर्ताओं के लिए स्पष्ट स्थिति जानकारी और मार्गदर्शन वाले नियंत्रण हैं।
ms|Perihal|Dibangunkan oleh|Perisian Sumber Terbuka|Dilesenkan di bawah MIT License|Kod Sumber|Versi {0}|Naufal Windows Powertoys ialah utiliti sistem Windows sumber terbuka yang direka untuk memudahkan penyelenggaraan sistem, penyelesaian masalah, pengoptimuman, konfigurasi permainan, pengurusan pemacu, keserasian masa jalan dan akses kepada alat Windows lanjutan melalui satu antara muka.|Aplikasi ini menghimpunkan fungsi pembaikan, penyelenggaraan, konfigurasi, diagnostik dan fungsi Windows lanjutan yang lazim digunakan di satu tempat, dengan maklumat status yang jelas serta kawalan berpandu untuk pengguna biasa dan lanjutan.
jv|Babagan|Digawe dening|Piranti Lunak Sumber Terbuka|Dilisensèkaké miturut MIT License|Kode Sumber|Versi {0}|Naufal Windows Powertoys iku piranti sistem Windows sumber terbuka sing dirancang kanggo nggampangake pangopènan sistem, ngrampungake masalah, optimasi, setelan game, pangelolaan driver, kecocokan runtime, lan akses piranti Windows tingkat lanjut liwat siji antarmuka.|Aplikasi iki nggabungake fungsi ndandani, pangopènan, setelan, diagnostik, lan fungsi Windows tingkat lanjut sing kerep dienggo ing siji papan, kanthi informasi status sing cetha lan kontrol mawa pandhuan kanggo pangguna saben dina lan tingkat lanjut.
ban|Indik Aplikasi|Kakembangang antuk|Piranti Lunak Sumber Terbuka|Kalisensiang manut MIT License|Kode Sumber|Versi {0}|Naufal Windows Powertoys inggih punika piranti sistem Windows sumber terbuka sane karancang antuk nggampil pangopènan sistem, ngarereh miwah ngentosin masalah, optimasi, pangaturan game, pangelolaan driver, kecocokan runtime, miwah akses piranti Windows tingkat lanjut nganggén asiki antarmuka.|Aplikasi puniki ngempulang fungsi ngentosin, pangopènan, pangaturan, diagnostik, miwah fungsi Windows tingkat lanjut sane sering kaanggén ring asiki genah, sareng informasi status sane terang miwah kontrol sane madaging pituduh antuk panganggé sadina-dina miwah tingkat lanjut.
sv|Om|Utvecklat av|Programvara med öppen källkod|Licensierat under MIT License|Källkod|Version {0}|Naufal Windows Powertoys är ett Windows-systemverktyg med öppen källkod som förenklar systemunderhåll, felsökning, optimering, spelkonfiguration, drivrutinshantering, kompatibilitet med körmiljöer och åtkomst till avancerade Windows-verktyg via ett gemensamt gränssnitt.|Programmet samlar vanliga reparations-, underhålls-, konfigurations-, diagnostik- och avancerade Windows-funktioner på ett ställe, med tydlig statusinformation och vägledda kontroller för både vanliga och avancerade användare.
es|Acerca de|Desarrollado por|Software de código abierto|Bajo la licencia MIT License|Código fuente|Versión {0}|Naufal Windows Powertoys es una utilidad de sistema Windows de código abierto diseñada para simplificar el mantenimiento, la resolución de problemas, la optimización, la configuración de juegos, la gestión de controladores, la compatibilidad de entornos de ejecución y el acceso a herramientas avanzadas de Windows mediante una interfaz unificada.|La aplicación reúne funciones habituales de reparación, mantenimiento, configuración, diagnóstico y funciones avanzadas de Windows en un solo lugar, con información de estado clara y controles guiados tanto para usuarios cotidianos como avanzados.
""";
}
