namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string OneDriveApps = """
en|Store apps affect this account only. OneDrive follows its installation scope; a shared installation affects all users.|Uninstalling OneDrive stops syncing. Finish syncing first. A shared installation is removed for all users. Your OneDrive files are not deleted by this tool.|OneDrive restore uses WinGet and the previous installation scope, or this account if no scope was saved. Internet and agreement acceptance are required. Sign in and choose sync folders again afterward.|Microsoft website|Microsoft website could not be opened.|Continuing allows WinGet to use its official source and accept the source agreements.
id|Aplikasi Store hanya memengaruhi akun ini. OneDrive mengikuti cakupan instalasinya; instalasi bersama memengaruhi semua pengguna.|Menghapus OneDrive menghentikan sinkronisasi. Selesaikan sinkronisasi terlebih dahulu. Instalasi bersama dihapus untuk semua pengguna. Alat ini tidak menghapus file OneDrive Anda.|Pemulihan OneDrive menggunakan WinGet dan cakupan instalasi sebelumnya, atau akun ini jika cakupan belum tersimpan. Internet dan persetujuan perjanjian diperlukan. Setelahnya, masuk dan pilih kembali folder sinkronisasi.|Situs Microsoft|Situs Microsoft tidak dapat dibuka.|Melanjutkan mengizinkan WinGet menggunakan sumber resminya dan menyetujui perjanjian sumber.
de|Store-Apps betreffen nur dieses Konto. OneDrive verwendet seinen Installationsumfang; eine gemeinsame Installation betrifft alle Benutzer.|Die Deinstallation von OneDrive stoppt die Synchronisierung. Schließen Sie diese zuerst ab. Eine gemeinsame Installation wird für alle Benutzer entfernt. Dieses Tool löscht keine OneDrive-Dateien.|Die OneDrive-Wiederherstellung verwendet WinGet und den früheren Installationsumfang oder dieses Konto, falls kein Umfang gespeichert wurde. Internet und die Zustimmung zu Vereinbarungen sind erforderlich. Melden Sie sich danach an und wählen Sie die Synchronisierungsordner erneut.|Microsoft-Website|Die Microsoft-Website konnte nicht geöffnet werden.|Wenn Sie fortfahren, darf WinGet seine offizielle Quelle verwenden und den Quellvereinbarungen zustimmen.
fr|Les applications Store concernent uniquement ce compte. OneDrive utilise sa portée d’installation ; une installation partagée concerne tous les utilisateurs.|Désinstaller OneDrive arrête la synchronisation. Terminez-la d’abord. Une installation partagée est supprimée pour tous les utilisateurs. Cet outil ne supprime pas vos fichiers OneDrive.|La restauration de OneDrive utilise WinGet et la portée d’installation précédente, ou ce compte si aucune portée n’a été enregistrée. Internet et l’acceptation des accords sont nécessaires. Ensuite, reconnectez-vous et choisissez à nouveau les dossiers à synchroniser.|Site Microsoft|Impossible d’ouvrir le site Microsoft.|Continuer autorise WinGet à utiliser sa source officielle et à accepter les accords de la source.
ar|تؤثر تطبيقات Store على هذا الحساب فقط. يتبع OneDrive نطاق تثبيته؛ والتثبيت المشترك يؤثر على جميع المستخدمين.|تؤدي إزالة OneDrive إلى إيقاف المزامنة. أكمل المزامنة أولاً. تتم إزالة التثبيت المشترك لجميع المستخدمين. لا تحذف هذه الأداة ملفات OneDrive الخاصة بك.|تستخدم استعادة OneDrive برنامج WinGet ونطاق التثبيت السابق، أو هذا الحساب إذا لم يُحفظ نطاق. يلزم الإنترنت وقبول الاتفاقيات. سجّل الدخول واختر مجلدات المزامنة مجددًا بعد ذلك.|موقع Microsoft|تعذر فتح موقع Microsoft.|تسمح المتابعة لبرنامج WinGet باستخدام مصدره الرسمي وقبول اتفاقيات المصدر.
tl|Ang mga Store app ay para lang sa account na ito. Sinusunod ng OneDrive ang saklaw ng pag-install nito; apektado ang lahat ng user sa nakabahaging pag-install.|Hihinto ang pag-sync kapag inalis ang OneDrive. Tapusin muna ang pag-sync. Aalisin ang nakabahaging pag-install para sa lahat ng user. Hindi buburahin ng tool na ito ang iyong mga OneDrive file.|Gumagamit ang pagpapanumbalik ng OneDrive ng WinGet at ng dating saklaw ng pag-install, o ng account na ito kung walang naitalang saklaw. Kailangan ang internet at pagtanggap sa mga kasunduan. Mag-sign in at piliing muli ang mga folder na isi-sync pagkatapos.|Website ng Microsoft|Hindi mabuksan ang website ng Microsoft.|Sa pagpapatuloy, pinapayagan ang WinGet na gamitin ang opisyal nitong source at tanggapin ang mga kasunduan ng source.
vi|Ứng dụng Store chỉ ảnh hưởng đến tài khoản này. OneDrive theo phạm vi cài đặt; cài đặt dùng chung ảnh hưởng đến mọi người dùng.|Gỡ OneDrive sẽ dừng đồng bộ. Hãy hoàn tất đồng bộ trước. Bản cài đặt dùng chung sẽ bị gỡ cho mọi người dùng. Công cụ này không xóa tệp OneDrive của bạn.|Khôi phục OneDrive dùng WinGet và phạm vi cài đặt trước đó, hoặc tài khoản này nếu chưa lưu phạm vi. Cần internet và chấp nhận các thỏa thuận. Sau đó hãy đăng nhập và chọn lại thư mục đồng bộ.|Trang web Microsoft|Không thể mở trang web Microsoft.|Tiếp tục cho phép WinGet dùng nguồn chính thức và chấp nhận các thỏa thuận của nguồn.
zh-CN|Store 应用仅影响此账户。OneDrive 遵循其安装范围；共享安装会影响所有用户。|卸载 OneDrive 将停止同步。请先完成同步。共享安装将为所有用户移除。本工具不会删除您的 OneDrive 文件。|OneDrive 恢复使用 WinGet 和之前的安装范围；如果未保存范围，则使用此账户。需要联网并接受协议。之后请重新登录并选择同步文件夹。|Microsoft 网站|无法打开 Microsoft 网站。|继续即允许 WinGet 使用其官方源并接受源协议。
zh-TW|Store 應用程式僅影響此帳戶。OneDrive 遵循其安裝範圍；共用安裝會影響所有使用者。|解除安裝 OneDrive 將停止同步。請先完成同步。共用安裝將為所有使用者移除。本工具不會刪除您的 OneDrive 檔案。|OneDrive 還原使用 WinGet 和先前的安裝範圍；如果未儲存範圍，則使用此帳戶。需要連線並接受合約。之後請重新登入並選擇同步資料夾。|Microsoft 網站|無法開啟 Microsoft 網站。|繼續即允許 WinGet 使用其官方來源並接受來源合約。
th|แอป Store มีผลเฉพาะบัญชีนี้ OneDrive ใช้ขอบเขตการติดตั้งเดิม การติดตั้งร่วมกันมีผลต่อผู้ใช้ทุกคน|การถอนการติดตั้ง OneDrive จะหยุดการซิงค์ โปรดซิงค์ให้เสร็จก่อน การติดตั้งร่วมกันจะถูกลบสำหรับผู้ใช้ทุกคน เครื่องมือนี้ไม่ลบไฟล์ OneDrive ของคุณ|การคืนค่า OneDrive ใช้ WinGet และขอบเขตการติดตั้งเดิม หรือบัญชีนี้หากไม่ได้บันทึกขอบเขตไว้ ต้องมีอินเทอร์เน็ตและยอมรับข้อตกลง จากนั้นให้ลงชื่อเข้าใช้และเลือกโฟลเดอร์ซิงค์อีกครั้ง|เว็บไซต์ Microsoft|ไม่สามารถเปิดเว็บไซต์ Microsoft ได้|การดำเนินการต่ออนุญาตให้ WinGet ใช้แหล่งข้อมูลทางการและยอมรับข้อตกลงของแหล่งข้อมูล
ru|Приложения Store затрагивают только эту учётную запись. OneDrive использует свою область установки; общая установка затрагивает всех пользователей.|Удаление OneDrive останавливает синхронизацию. Сначала завершите её. Общая установка удаляется для всех пользователей. Этот инструмент не удаляет ваши файлы OneDrive.|Восстановление OneDrive использует WinGet и прежнюю область установки, либо эту учётную запись, если область не сохранена. Нужны интернет и принятие соглашений. Затем войдите и заново выберите папки синхронизации.|Сайт Microsoft|Не удалось открыть сайт Microsoft.|Продолжение разрешает WinGet использовать официальный источник и принять соглашения источника.
uk|Програми Store впливають лише на цей обліковий запис. OneDrive використовує свою область інсталяції; спільна інсталяція впливає на всіх користувачів.|Видалення OneDrive зупиняє синхронізацію. Спочатку завершіть її. Спільна інсталяція видаляється для всіх користувачів. Цей інструмент не видаляє ваші файли OneDrive.|Відновлення OneDrive використовує WinGet і попередню область інсталяції або цей обліковий запис, якщо область не збережена. Потрібні інтернет і прийняття угод. Потім увійдіть і знову виберіть папки синхронізації.|Сайт Microsoft|Не вдалося відкрити сайт Microsoft.|Продовження дозволяє WinGet використовувати офіційне джерело та прийняти угоди джерела.
pt|As aplicações Store afetam apenas esta conta. O OneDrive segue o seu âmbito de instalação; uma instalação partilhada afeta todos os utilizadores.|Desinstalar o OneDrive interrompe a sincronização. Conclua-a primeiro. Uma instalação partilhada é removida para todos os utilizadores. Esta ferramenta não elimina os seus ficheiros OneDrive.|O restauro do OneDrive utiliza o WinGet e o âmbito de instalação anterior, ou esta conta se nenhum âmbito foi guardado. São necessários internet e aceitação dos contratos. Depois, inicie sessão e escolha novamente as pastas de sincronização.|Site da Microsoft|Não foi possível abrir o site da Microsoft.|Continuar permite ao WinGet utilizar a sua fonte oficial e aceitar os contratos da fonte.
ja|Store アプリはこのアカウントのみに影響します。OneDrive はインストール範囲に従い、共有インストールはすべてのユーザーに影響します。|OneDrive をアンインストールすると同期が停止します。先に同期を完了してください。共有インストールはすべてのユーザーから削除されます。このツールは OneDrive ファイルを削除しません。|OneDrive の復元には WinGet と以前のインストール範囲を使用し、範囲が保存されていない場合はこのアカウントを使用します。インターネット接続と契約への同意が必要です。その後、再度サインインして同期フォルダーを選択してください。|Microsoft のウェブサイト|Microsoft のウェブサイトを開けませんでした。|続行すると、WinGet による公式ソースの使用とソース契約への同意を許可します。
ko|Store 앱은 이 계정에만 영향을 줍니다. OneDrive는 설치 범위를 따르며 공유 설치는 모든 사용자에게 영향을 줍니다.|OneDrive를 제거하면 동기화가 중지됩니다. 먼저 동기화를 완료하세요. 공유 설치는 모든 사용자에게서 제거됩니다. 이 도구는 OneDrive 파일을 삭제하지 않습니다.|OneDrive 복원은 WinGet과 이전 설치 범위를 사용하며, 저장된 범위가 없으면 이 계정을 사용합니다. 인터넷과 계약 동의가 필요합니다. 이후 다시 로그인하고 동기화 폴더를 선택하세요.|Microsoft 웹사이트|Microsoft 웹사이트를 열 수 없습니다.|계속하면 WinGet이 공식 소스를 사용하고 소스 계약에 동의하도록 허용합니다.
ur|Store ایپس صرف اس اکاؤنٹ کو متاثر کرتی ہیں۔ OneDrive اپنی تنصیب کے دائرے کی پیروی کرتا ہے؛ مشترکہ تنصیب تمام صارفین کو متاثر کرتی ہے۔|OneDrive کو اَن انسٹال کرنے سے مطابقت پذیری رک جاتی ہے۔ پہلے مطابقت پذیری مکمل کریں۔ مشترکہ تنصیب تمام صارفین کے لیے ہٹائی جاتی ہے۔ یہ ٹول آپ کی OneDrive فائلیں حذف نہیں کرتا۔|OneDrive کی بحالی WinGet اور پچھلی تنصیب کا دائرہ استعمال کرتی ہے، یا اگر دائرہ محفوظ نہ ہو تو یہ اکاؤنٹ۔ انٹرنیٹ اور معاہدوں کی منظوری ضروری ہے۔ اس کے بعد سائن اِن کریں اور مطابقت پذیری کے فولڈر دوبارہ منتخب کریں۔|Microsoft ویب سائٹ|Microsoft ویب سائٹ نہیں کھل سکی۔|جاری رکھنے سے WinGet کو اپنا سرکاری ماخذ استعمال کرنے اور ماخذ کے معاہدے قبول کرنے کی اجازت ملتی ہے۔
ta|Store பயன்பாடுகள் இந்தக் கணக்கை மட்டுமே பாதிக்கும். OneDrive அதன் நிறுவல் வரம்பைப் பின்பற்றும்; பகிரப்பட்ட நிறுவல் எல்லா பயனர்களையும் பாதிக்கும்.|OneDrive ஐ நிறுவல் நீக்குவது ஒத்திசைவை நிறுத்தும். முதலில் ஒத்திசைவை முடிக்கவும். பகிரப்பட்ட நிறுவல் எல்லா பயனர்களுக்கும் நீக்கப்படும். இந்தக் கருவி உங்கள் OneDrive கோப்புகளை நீக்காது.|OneDrive மீட்டமைப்பு WinGet மற்றும் முந்தைய நிறுவல் வரம்பைப் பயன்படுத்தும்; வரம்பு சேமிக்கப்படாவிட்டால் இந்தக் கணக்கைப் பயன்படுத்தும். இணையமும் ஒப்பந்தங்களை ஏற்றுக்கொள்வதும் தேவை. பின்னர் உள்நுழைந்து ஒத்திசைவு கோப்புறைகளை மீண்டும் தேர்ந்தெடுக்கவும்.|Microsoft இணையதளம்|Microsoft இணையதளத்தைத் திறக்க முடியவில்லை.|தொடர்வது WinGet தனது அதிகாரப்பூர்வ மூலத்தைப் பயன்படுத்தவும் மூல ஒப்பந்தங்களை ஏற்கவும் அனுமதிக்கிறது.
hi|Store ऐप केवल इस खाते को प्रभावित करते हैं। OneDrive अपने इंस्टॉलेशन दायरे का पालन करता है; साझा इंस्टॉलेशन सभी उपयोगकर्ताओं को प्रभावित करता है।|OneDrive को अनइंस्टॉल करने से सिंक रुक जाता है। पहले सिंक पूरा करें। साझा इंस्टॉलेशन सभी उपयोगकर्ताओं के लिए हटाया जाता है। यह टूल आपकी OneDrive फ़ाइलें नहीं मिटाता।|OneDrive की बहाली WinGet और पिछले इंस्टॉलेशन दायरे का उपयोग करती है, या दायरा सहेजा न हो तो इस खाते का। इंटरनेट और अनुबंधों की स्वीकृति आवश्यक है। बाद में साइन इन करें और सिंक फ़ोल्डर दोबारा चुनें।|Microsoft वेबसाइट|Microsoft वेबसाइट नहीं खोली जा सकी।|जारी रखने से WinGet को आधिकारिक स्रोत इस्तेमाल करने और स्रोत अनुबंध स्वीकार करने की अनुमति मिलती है।
ms|Aplikasi Store hanya mempengaruhi akaun ini. OneDrive mengikut skop pemasangannya; pemasangan bersama mempengaruhi semua pengguna.|Menyahpasang OneDrive menghentikan penyegerakan. Selesaikan penyegerakan dahulu. Pemasangan bersama dibuang untuk semua pengguna. Alat ini tidak memadam fail OneDrive anda.|Pemulihan OneDrive menggunakan WinGet dan skop pemasangan terdahulu, atau akaun ini jika tiada skop disimpan. Internet dan penerimaan perjanjian diperlukan. Selepas itu, log masuk dan pilih semula folder penyegerakan.|Laman Microsoft|Laman Microsoft tidak dapat dibuka.|Meneruskan membenarkan WinGet menggunakan sumber rasminya dan menerima perjanjian sumber.
jv|Aplikasi Store mung mengaruhi akun iki. OneDrive manut cakupan instalasine; instalasi bebarengan mengaruhi kabeh pangguna.|Mbusak OneDrive mandhegake sinkronisasi. Rampungna sinkronisasi dhisik. Instalasi bebarengan dibusak kanggo kabeh pangguna. Piranti iki ora mbusak file OneDrive sampeyan.|Mulihake OneDrive nggunakake WinGet lan cakupan instalasi sadurunge, utawa akun iki yen ora ana cakupan sing disimpen. Mbutuhake internet lan sarujuk marang perjanjian. Sawise kuwi, mlebu lan pilih maneh folder sinkronisasi.|Situs Microsoft|Situs Microsoft ora bisa dibukak.|Nerusake ngidini WinGet nggunakake sumber resmine lan nyarujuki perjanjian sumber.
ban|Aplikasi Store wantah mangaruhin akun puniki. OneDrive manut cakupan instalasinipun; instalasi sareng mangaruhin makasami pangangge.|Ngapus OneDrive ngaryanin sinkronisasi mandeg. Puputang sinkronisasi dumun. Instalasi sareng kaapus ring makasami pangangge. Piranti puniki nenten ngapus file OneDrive ragane.|Pamulihaan OneDrive nganggen WinGet lan cakupan instalasi sane sadurungipun, utawi akun puniki yening cakupan durung kasimpen. Perlu internet lan nyarengin perjanjian. Sasampunipun, mlebet lan pilih malih folder sinkronisasi.|Situs Microsoft|Situs Microsoft nenten prasida kabuka.|Nerusang ngicenin WinGet nganggen sumber resmi lan nyarengin perjanjian sumber.
sv|Store-appar påverkar bara detta konto. OneDrive följer sitt installationsomfång; en delad installation påverkar alla användare.|Om OneDrive avinstalleras stoppas synkroniseringen. Slutför den först. En delad installation tas bort för alla användare. Verktyget raderar inte dina OneDrive-filer.|Återställning av OneDrive använder WinGet och det tidigare installationsomfånget, eller detta konto om inget omfång sparats. Internet och godkännande av avtal krävs. Logga sedan in och välj synkroniseringsmappar igen.|Microsofts webbplats|Microsofts webbplats kunde inte öppnas.|Om du fortsätter får WinGet använda sin officiella källa och godkänna källavtalen.
es|Las aplicaciones Store afectan solo a esta cuenta. OneDrive sigue su ámbito de instalación; una instalación compartida afecta a todos los usuarios.|Desinstalar OneDrive detiene la sincronización. Complétela primero. Una instalación compartida se elimina para todos los usuarios. Esta herramienta no elimina sus archivos de OneDrive.|La restauración de OneDrive usa WinGet y el ámbito de instalación anterior, o esta cuenta si no se guardó ningún ámbito. Requiere internet y aceptar los acuerdos. Después, inicie sesión y elija de nuevo las carpetas de sincronización.|Sitio web de Microsoft|No se pudo abrir el sitio web de Microsoft.|Continuar permite a WinGet usar su fuente oficial y aceptar los acuerdos de la fuente.
""";
}
