namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string Titles = """
en|Taskbar End Task|Classic Context Menu|Windows Consumer Features|Delivery Optimization|Hibernation|Location Tracking|Windows Telemetry|Service Startup|File Explorer Home & Gallery|Windows AI|Windows Recommendations|Advertising ID & Personalization|Taskbar Buttons|File Explorer Discovery|Kernel & Boot Debugging|Boot Driver Messages|Boot Processor Configuration|Boot Manager Timeout|Icon Cache Size|Temporary Files|Lock Pages in Memory|GPU Shader Cache|System Restore Point|Explorer Network Discovery|Task View Button|Accessibility Keyboard Shortcuts|File Extensions
id|Akhiri Tugas di Taskbar|Menu Konteks Klasik|Fitur Konsumen Windows|Pengoptimalan Pengiriman|Hibernasi|Pelacakan Lokasi|Telemetri Windows|Startup Layanan|Beranda & Galeri File Explorer|AI Windows|Rekomendasi Windows|ID Iklan & Personalisasi|Tombol Taskbar|Penemuan File Explorer|Debug Kernel & Boot|Pesan Driver Boot|Konfigurasi Prosesor Boot|Batas Waktu Boot Manager|Ukuran Cache Ikon|Berkas Sementara|Kunci Halaman dalam Memori|Cache Shader GPU|Titik Pemulihan Sistem|Penemuan Jaringan Explorer|Tombol Tampilan Tugas|Pintasan Keyboard Aksesibilitas|Ekstensi Berkas
de|Task über Taskleiste beenden|Klassisches Kontextmenü|Windows-Verbraucherfunktionen|Übermittlungsoptimierung|Ruhezustand|Standortverfolgung|Windows-Telemetrie|Dienststart|Explorer-Startseite & Katalog|Windows-KI|Windows-Empfehlungen|Werbe-ID & Personalisierung|Taskleistenschaltflächen|Explorer-Erkennung|Kernel- & Startdebugging|Starttreibermeldungen|Prozessorkonfiguration beim Start|Zeitlimit des Start-Managers|Symbolcachegröße|Temporäre Dateien|Speicherseiten sperren|GPU-Shadercache|Systemwiederherstellungspunkt|Explorer-Netzwerkerkennung|Schaltfläche Taskansicht|Tastenkombinationen für Barrierefreiheit|Dateierweiterungen
fr|Fin de tâche dans la barre des tâches|Menu contextuel classique|Fonctionnalités grand public Windows|Optimisation de la distribution|Veille prolongée|Suivi de localisation|Télémétrie Windows|Démarrage des services|Accueil et Galerie de l'Explorateur|IA Windows|Recommandations Windows|Identifiant publicitaire et personnalisation|Boutons de la barre des tâches|Découverte de l'Explorateur|Débogage du noyau et du démarrage|Messages des pilotes de démarrage|Configuration du processeur au démarrage|Délai du gestionnaire de démarrage|Taille du cache d'icônes|Fichiers temporaires|Verrouillage des pages en mémoire|Cache des shaders GPU|Point de restauration système|Découverte réseau de l'Explorateur|Bouton Vue Tâches|Raccourcis clavier d'accessibilité|Extensions de fichiers
ar|إنهاء المهمة من شريط المهام|قائمة السياق التقليدية|ميزات Windows للمستهلكين|تحسين التسليم|الإسبات|تتبع الموقع|بيانات تتبع Windows|بدء تشغيل الخدمات|الصفحة الرئيسية والمعرض في مستكشف الملفات|ذكاء Windows الاصطناعي|توصيات Windows|معرّف الإعلانات والتخصيص|أزرار شريط المهام|اكتشاف مستكشف الملفات|تصحيح أخطاء النواة والإقلاع|رسائل برامج تشغيل الإقلاع|إعداد المعالج عند الإقلاع|مهلة مدير الإقلاع|حجم ذاكرة الأيقونات المؤقتة|الملفات المؤقتة|قفل الصفحات في الذاكرة|ذاكرة تظليل GPU المؤقتة|نقطة استعادة النظام|اكتشاف الشبكة في المستكشف|زر عرض المهام|اختصارات لوحة مفاتيح إمكانية الوصول|امتدادات الملفات
tl|Tapusin ang Gawain sa Taskbar|Klasikong Context Menu|Mga Consumer Feature ng Windows|Pag-optimize ng Paghahatid|Hibernation|Pagsubaybay sa Lokasyon|Telemetry ng Windows|Pagsisimula ng Serbisyo|Home at Gallery ng File Explorer|AI ng Windows|Mga Rekomendasyon ng Windows|Advertising ID at Pag-personalize|Mga Button ng Taskbar|Pagtuklas ng File Explorer|Pag-debug ng Kernel at Boot|Mga Mensahe ng Boot Driver|Konfigurasyon ng Processor sa Boot|Timeout ng Boot Manager|Laki ng Icon Cache|Mga Pansamantalang File|Pag-lock ng mga Pahina sa Memory|GPU Shader Cache|System Restore Point|Pagtuklas ng Network sa Explorer|Button ng Task View|Mga Keyboard Shortcut sa Accessibility|Mga Extension ng File
vi|Kết thúc tác vụ trên thanh tác vụ|Menu ngữ cảnh cổ điển|Tính năng tiêu dùng Windows|Tối ưu hóa phân phối|Ngủ đông|Theo dõi vị trí|Đo từ xa Windows|Khởi động dịch vụ|Trang chủ và Bộ sưu tập File Explorer|AI Windows|Đề xuất Windows|ID quảng cáo và cá nhân hóa|Nút trên thanh tác vụ|Khám phá của File Explorer|Gỡ lỗi nhân và khởi động|Thông báo trình điều khiển khởi động|Cấu hình bộ xử lý khi khởi động|Thời gian chờ trình quản lý khởi động|Kích thước bộ nhớ đệm biểu tượng|Tệp tạm thời|Khóa trang trong bộ nhớ|Bộ nhớ đệm shader GPU|Điểm khôi phục hệ thống|Khám phá mạng trong Explorer|Nút Chế độ xem tác vụ|Phím tắt trợ năng|Phần mở rộng tệp
zh-CN|任务栏结束任务|经典右键菜单|Windows 消费者功能|传递优化|休眠|位置跟踪|Windows 遥测|服务启动|文件资源管理器主页和图库|Windows AI|Windows 推荐|广告 ID 和个性化|任务栏按钮|文件资源管理器发现|内核和启动调试|启动驱动程序消息|启动处理器配置|启动管理器超时|图标缓存大小|临时文件|锁定内存页|GPU 着色器缓存|系统还原点|资源管理器网络发现|任务视图按钮|辅助功能键盘快捷键|文件扩展名
zh-TW|工作列結束工作|傳統快顯功能表|Windows 消費者功能|傳遞最佳化|休眠|位置追蹤|Windows 遙測|服務啟動|檔案總管首頁和圖庫|Windows AI|Windows 建議|廣告識別碼和個人化|工作列按鈕|檔案總管探索|核心和開機偵錯|開機驅動程式訊息|開機處理器設定|開機管理員逾時|圖示快取大小|暫存檔案|鎖定記憶體分頁|GPU 著色器快取|系統還原點|檔案總管網路探索|工作檢視按鈕|協助工具鍵盤快速鍵|副檔名
th|จบงานจากแถบงาน|เมนูคลิกขวาแบบคลาสสิก|คุณลักษณะผู้บริโภคของ Windows|การเพิ่มประสิทธิภาพการนำส่ง|ไฮเบอร์เนต|การติดตามตำแหน่ง|ข้อมูลการวัดและส่งข้อมูลของ Windows|การเริ่มต้นบริการ|หน้าแรกและแกลเลอรีของ File Explorer|AI ของ Windows|คำแนะนำของ Windows|รหัสโฆษณาและการปรับแต่งส่วนบุคคล|ปุ่มบนแถบงาน|การค้นพบของ File Explorer|การดีบักเคอร์เนลและการบูต|ข้อความไดรเวอร์ขณะบูต|การกำหนดค่าโปรเซสเซอร์ขณะบูต|ระยะหมดเวลาของตัวจัดการบูต|ขนาดแคชไอคอน|ไฟล์ชั่วคราว|การล็อกเพจในหน่วยความจำ|แคชเชดเดอร์ GPU|จุดคืนค่าระบบ|การค้นพบเครือข่ายของ Explorer|ปุ่มมุมมองงาน|แป้นพิมพ์ลัดการช่วยสำหรับการเข้าถึง|นามสกุลไฟล์
ru|Завершение задачи с панели задач|Классическое контекстное меню|Потребительские функции Windows|Оптимизация доставки|Гибернация|Отслеживание местоположения|Телеметрия Windows|Запуск служб|Главная и Галерея Проводника|ИИ Windows|Рекомендации Windows|Рекламный идентификатор и персонализация|Кнопки панели задач|Обнаружение в Проводнике|Отладка ядра и загрузки|Сообщения загрузочных драйверов|Конфигурация процессоров при загрузке|Время ожидания диспетчера загрузки|Размер кэша значков|Временные файлы|Блокировка страниц в памяти|Кэш шейдеров GPU|Точка восстановления системы|Обнаружение сети в Проводнике|Кнопка представления задач|Сочетания клавиш специальных возможностей|Расширения файлов
uk|Завершення завдання з панелі завдань|Класичне контекстне меню|Споживчі функції Windows|Оптимізація доставки|Гібернація|Відстеження розташування|Телеметрія Windows|Запуск служб|Головна та Галерея Провідника|ШІ Windows|Рекомендації Windows|Рекламний ідентифікатор і персоналізація|Кнопки панелі завдань|Виявлення в Провіднику|Налагодження ядра та завантаження|Повідомлення завантажувальних драйверів|Конфігурація процесорів під час завантаження|Час очікування диспетчера завантаження|Розмір кешу піктограм|Тимчасові файли|Блокування сторінок у пам'яті|Кеш шейдерів GPU|Точка відновлення системи|Виявлення мережі в Провіднику|Кнопка подання завдань|Сполучення клавіш спеціальних можливостей|Розширення файлів
pt|Terminar tarefa na barra de tarefas|Menu de contexto clássico|Funcionalidades de consumo do Windows|Otimização da Entrega|Hibernação|Rastreio de localização|Telemetria do Windows|Arranque dos serviços|Início e Galeria do Explorador de Ficheiros|IA do Windows|Recomendações do Windows|ID de publicidade e personalização|Botões da barra de tarefas|Deteção do Explorador de Ficheiros|Depuração do kernel e do arranque|Mensagens dos controladores de arranque|Configuração do processador no arranque|Tempo limite do gestor de arranque|Tamanho da cache de ícones|Ficheiros temporários|Bloquear páginas na memória|Cache de shaders da GPU|Ponto de restauro do sistema|Deteção de rede do Explorador|Botão Vista de Tarefas|Atalhos de teclado de acessibilidade|Extensões de ficheiros
ja|タスクバーからタスクを終了|従来のコンテキスト メニュー|Windows コンシューマー機能|配信の最適化|休止状態|位置情報の追跡|Windows テレメトリ|サービスの起動|エクスプローラーのホームとギャラリー|Windows AI|Windows のおすすめ|広告 ID と個人用設定|タスクバーのボタン|エクスプローラーの検出|カーネルとブートのデバッグ|ブート ドライバーのメッセージ|起動時のプロセッサ構成|ブート マネージャーのタイムアウト|アイコン キャッシュのサイズ|一時ファイル|メモリ内のページのロック|GPU シェーダー キャッシュ|システムの復元ポイント|エクスプローラーのネットワーク検出|タスク ビュー ボタン|アクセシビリティのキーボード ショートカット|ファイルの拡張子
ko|작업 표시줄에서 작업 끝내기|기존 상황에 맞는 메뉴|Windows 소비자 기능|배달 최적화|최대 절전 모드|위치 추적|Windows 원격 분석|서비스 시작|파일 탐색기 홈 및 갤러리|Windows AI|Windows 추천|광고 ID 및 개인 설정|작업 표시줄 단추|파일 탐색기 검색|커널 및 부팅 디버깅|부팅 드라이버 메시지|부팅 시 프로세서 구성|부팅 관리자 제한 시간|아이콘 캐시 크기|임시 파일|메모리 페이지 잠금|GPU 셰이더 캐시|시스템 복원 지점|탐색기 네트워크 검색|작업 보기 단추|접근성 바로 가기 키|파일 확장명
ur|ٹاسک بار سے کام ختم کرنا|پرانا سیاقی مینو|Windows کی صارف خصوصیات|ترسیل کی بہتری|ہائبرنیشن|مقام کی نگرانی|Windows ٹیلی میٹری|خدمات کا آغاز|فائل ایکسپلورر ہوم اور گیلری|Windows AI|Windows کی تجاویز|اشتہاری شناخت اور ذاتی تخصیص|ٹاسک بار بٹن|فائل ایکسپلورر دریافت|کرنل اور بوٹ ڈیبگنگ|بوٹ ڈرائیور پیغامات|بوٹ پروسیسر کی ترتیب|بوٹ منیجر کا وقت ختم ہونا|آئیکن کیش کا حجم|عارضی فائلیں|میموری میں صفحات مقفل کرنا|GPU شیڈر کیش|سسٹم بحالی نقطہ|ایکسپلورر نیٹ ورک دریافت|ٹاسک ویو بٹن|رسائی کے کی بورڈ شارٹ کٹس|فائل ایکسٹینشنز
ta|பணிப்பட்டியில் பணியை முடித்தல்|பழைய சூழல் மெனு|Windows நுகர்வோர் அம்சங்கள்|விநியோக மேம்படுத்தல்|உறக்கநிலை|இருப்பிடக் கண்காணிப்பு|Windows தொலைஅளவீடு|சேவை தொடக்கம்|கோப்பு எக்ஸ்ப்ளோரர் முகப்பு மற்றும் கேலரி|Windows AI|Windows பரிந்துரைகள்|விளம்பர ID மற்றும் தனிப்பயனாக்கம்|பணிப்பட்டி பொத்தான்கள்|கோப்பு எக்ஸ்ப்ளோரர் கண்டறிதல்|கர்னல் மற்றும் துவக்கப் பிழைத்திருத்தம்|துவக்க இயக்கி செய்திகள்|துவக்கச் செயலி உள்ளமைவு|துவக்க மேலாளர் காலக்கெடு|சின்னத் தேக்கக அளவு|தற்காலிக கோப்புகள்|நினைவகப் பக்கங்களைப் பூட்டுதல்|GPU ஷேடர் தேக்ககம்|கணினி மீட்டமைப்புப் புள்ளி|எக்ஸ்ப்ளோரர் வலைப்பின்னல் கண்டறிதல்|பணிக் காட்சி பொத்தான்|அணுகல்தன்மை விசைப்பலகைக் குறுக்குவழிகள்|கோப்பு நீட்டிப்புகள்
hi|टास्कबार से कार्य समाप्ति|पुराना संदर्भ मेनू|Windows उपभोक्ता सुविधाएँ|डिलीवरी ऑप्टिमाइज़ेशन|हाइबरनेशन|स्थान ट्रैकिंग|Windows टेलीमेट्री|सेवा स्टार्टअप|फ़ाइल एक्सप्लोरर होम और गैलरी|Windows AI|Windows अनुशंसाएँ|विज्ञापन ID और वैयक्तिकरण|टास्कबार बटन|फ़ाइल एक्सप्लोरर खोज|कर्नेल और बूट डिबगिंग|बूट ड्राइवर संदेश|बूट प्रोसेसर कॉन्फ़िगरेशन|बूट प्रबंधक टाइमआउट|आइकन कैश आकार|अस्थायी फ़ाइलें|मेमोरी में पृष्ठ लॉक करना|GPU शेडर कैश|सिस्टम पुनर्स्थापना बिंदु|एक्सप्लोरर नेटवर्क खोज|टास्क व्यू बटन|सुलभता कीबोर्ड शॉर्टकट|फ़ाइल एक्सटेंशन
ms|Tamatkan Tugas pada Bar Tugas|Menu Konteks Klasik|Ciri Pengguna Windows|Pengoptimuman Penghantaran|Hibernasi|Penjejakan Lokasi|Telemetri Windows|Permulaan Perkhidmatan|Laman Utama dan Galeri File Explorer|AI Windows|Cadangan Windows|ID Pengiklanan dan Pemperibadian|Butang Bar Tugas|Penemuan File Explorer|Penyahpepijatan Kernel dan But|Mesej Pemacu But|Konfigurasi Pemproses But|Had Masa Pengurus But|Saiz Cache Ikon|Fail Sementara|Kunci Halaman dalam Memori|Cache Shader GPU|Titik Pemulihan Sistem|Penemuan Rangkaian Explorer|Butang Paparan Tugas|Pintasan Papan Kekunci Kebolehcapaian|Sambungan Fail
jv|Mungkasi Tugas ing Taskbar|Menu Konteks Klasik|Fitur Konsumen Windows|Optimalisasi Pangiriman|Hibernasi|Pelacakan Lokasi|Telemetri Windows|Wiwitan Layanan|Ngarep lan Galeri File Explorer|AI Windows|Rekomendasi Windows|ID Iklan lan Personalisasi|Tombol Taskbar|Panemuan File Explorer|Debug Kernel lan Boot|Pesen Driver Boot|Konfigurasi Prosesor Boot|Wates Wektu Boot Manager|Ukuran Cache Ikon|Berkas Sauntara|Kunci Kaca ing Memori|Cache Shader GPU|Titik Pamulihan Sistem|Panemuan Jaringan Explorer|Tombol Tampilan Tugas|Trabasan Keyboard Aksesibilitas|Ekstensi Berkas
ban|Muputang Tugas ring Taskbar|Menu Konteks Klasik|Fitur Konsumen Windows|Optimalisasi Pangiriman|Hibernasi|Pelacakan Lokasi|Telemetri Windows|Wiwitan Layanan|Kaca Utama miwah Galeri File Explorer|AI Windows|Rekomendasi Windows|ID Iklan miwah Personalisasi|Tombol Taskbar|Panemuan File Explorer|Debug Kernel miwah Boot|Pesen Driver Boot|Konfigurasi Prosesor Boot|Wates Waktu Boot Manager|Ukuran Cache Ikon|Berkas Samentara|Kunci Kaca ring Memori|Cache Shader GPU|Titik Pamulihan Sistem|Panemuan Jaringan Explorer|Tombol Tampilan Tugas|Pintasan Keyboard Aksesibilitas|Ekstensi Berkas
sv|Avsluta aktivitet från aktivitetsfältet|Klassisk snabbmeny|Windows-konsumentfunktioner|Leveransoptimering|Viloläge|Platsspårning|Windows-telemetri|Tjänststart|Utforskarens Hem och Galleri|Windows-AI|Windows-rekommendationer|Annons-ID och anpassning|Knappar i aktivitetsfältet|Utforskarens identifiering|Kernel- och startfelsökning|Meddelanden från startdrivrutiner|Processorkonfiguration vid start|Starthanterarens tidsgräns|Storlek på ikoncache|Temporära filer|Lås sidor i minnet|GPU-shadercache|Systemåterställningspunkt|Utforskarens nätverksidentifiering|Knappen Aktivitetsvy|Kortkommandon för hjälpmedel|Filnamnstillägg
es|Finalizar tarea desde la barra de tareas|Menú contextual clásico|Características de consumidor de Windows|Optimización de distribución|Hibernación|Seguimiento de ubicación|Telemetría de Windows|Inicio de servicios|Inicio y Galería del Explorador|IA de Windows|Recomendaciones de Windows|ID de publicidad y personalización|Botones de la barra de tareas|Detección del Explorador|Depuración del kernel y del arranque|Mensajes de controladores de arranque|Configuración del procesador al arrancar|Tiempo de espera del administrador de arranque|Tamaño de caché de iconos|Archivos temporales|Bloquear páginas en memoria|Caché de sombreadores GPU|Punto de restauración del sistema|Detección de redes del Explorador|Botón Vista de tareas|Métodos abreviados de accesibilidad|Extensiones de archivo
""";
}
