namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string CopilotConsent = """
en|Microsoft Store source agreement|Agree and continue|Read Microsoft Store terms|To check Microsoft Copilot, WinGet must use the Microsoft Store source.|Choosing Agree and continue accepts the Microsoft Store source terms and allows WinGet to send this PC's two-letter region code to Microsoft. WinGet may remember that acceptance.|Cancel stops this operation before any changes. Checking the source does not buy or install apps.
id|Persetujuan sumber Microsoft Store|Setuju dan lanjutkan|Baca ketentuan Microsoft Store|Untuk memeriksa Microsoft Copilot, WinGet harus menggunakan sumber Microsoft Store.|Memilih Setuju dan lanjutkan berarti menerima ketentuan sumber Microsoft Store dan mengizinkan WinGet mengirim kode wilayah dua huruf PC ini ke Microsoft. WinGet dapat menyimpan persetujuan tersebut.|Batal menghentikan operasi ini sebelum ada perubahan. Pemeriksaan sumber tidak membeli atau menginstal aplikasi.
de|Vereinbarung zur Microsoft Store-Quelle|Zustimmen und fortfahren|Microsoft Store-Bedingungen lesen|Zum Prüfen von Microsoft Copilot muss WinGet die Microsoft Store-Quelle verwenden.|Mit Zustimmen und fortfahren akzeptieren Sie die Bedingungen der Microsoft Store-Quelle und erlauben WinGet, den zweistelligen Regionscode dieses PCs an Microsoft zu senden. WinGet kann diese Zustimmung speichern.|Abbrechen beendet diesen Vorgang vor jeder Änderung. Beim Prüfen der Quelle werden keine Apps gekauft oder installiert.
fr|Accord de la source Microsoft Store|Accepter et continuer|Lire les conditions du Microsoft Store|Pour vérifier Microsoft Copilot, WinGet doit utiliser la source Microsoft Store.|Accepter et continuer accepte les conditions de la source Microsoft Store et autorise WinGet à envoyer à Microsoft le code régional à deux lettres de ce PC. WinGet peut mémoriser cet accord.|Annuler arrête cette opération avant toute modification. Vérifier la source n’achète ni n’installe d’applications.
ar|اتفاقية مصدر Microsoft Store|أوافق وأتابع|قراءة شروط Microsoft Store|للتحقق من Microsoft Copilot، يجب أن يستخدم WinGet مصدر Microsoft Store.|اختيار أوافق وأتابع يعني قبول شروط مصدر Microsoft Store والسماح لـ WinGet بإرسال رمز منطقة هذا الكمبيوتر المكوّن من حرفين إلى Microsoft. قد يحفظ WinGet هذه الموافقة.|يلغي زر إلغاء هذه العملية قبل أي تغييرات. التحقق من المصدر لا يشتري تطبيقات ولا يثبّتها.
tl|Kasunduan sa source ng Microsoft Store|Sumang-ayon at magpatuloy|Basahin ang mga tuntunin ng Microsoft Store|Para suriin ang Microsoft Copilot, kailangang gamitin ng WinGet ang Microsoft Store source.|Ang pagpili sa Sumang-ayon at magpatuloy ay pagtanggap sa mga tuntunin ng Microsoft Store source at pagpapahintulot sa WinGet na ipadala sa Microsoft ang dalawang-letrang region code ng PC na ito. Maaaring tandaan ng WinGet ang pagtanggap na iyon.|Ihihinto ng Kanselahin ang operasyong ito bago magkaroon ng pagbabago. Walang bibilhin o i-install na app sa pagsusuri ng source.
vi|Thỏa thuận nguồn Microsoft Store|Đồng ý và tiếp tục|Đọc điều khoản Microsoft Store|Để kiểm tra Microsoft Copilot, WinGet phải sử dụng nguồn Microsoft Store.|Chọn Đồng ý và tiếp tục là chấp nhận điều khoản nguồn Microsoft Store và cho phép WinGet gửi mã vùng hai chữ cái của PC này tới Microsoft. WinGet có thể ghi nhớ sự chấp nhận đó.|Hủy sẽ dừng thao tác này trước khi có thay đổi. Kiểm tra nguồn không mua hoặc cài đặt ứng dụng.
zh-CN|Microsoft Store 源协议|同意并继续|阅读 Microsoft Store 条款|要检查 Microsoft Copilot，WinGet 必须使用 Microsoft Store 源。|选择“同意并继续”即接受 Microsoft Store 源条款，并允许 WinGet 将此电脑的两字母地区代码发送给 Microsoft。WinGet 可能会记住此次同意。|取消会在任何更改前停止此操作。检查源不会购买或安装应用。
zh-TW|Microsoft Store 來源協議|同意並繼續|閱讀 Microsoft Store 條款|若要檢查 Microsoft Copilot，WinGet 必須使用 Microsoft Store 來源。|選擇「同意並繼續」即接受 Microsoft Store 來源條款，並允許 WinGet 將此電腦的兩字母地區代碼傳送給 Microsoft。WinGet 可能會記住此次同意。|取消會在任何變更前停止此操作。檢查來源不會購買或安裝應用程式。
th|ข้อตกลงแหล่ง Microsoft Store|ยอมรับและดำเนินการต่อ|อ่านข้อกำหนดของ Microsoft Store|เพื่อตรวจสอบ Microsoft Copilot นั้น WinGet ต้องใช้แหล่ง Microsoft Store|การเลือกยอมรับและดำเนินการต่อเป็นการยอมรับข้อกำหนดแหล่ง Microsoft Store และอนุญาตให้ WinGet ส่งรหัสภูมิภาคสองตัวอักษรของพีซีนี้ไปยัง Microsoft ทั้งนี้ WinGet อาจจดจำการยอมรับนี้|ยกเลิกจะหยุดการดำเนินการนี้ก่อนมีการเปลี่ยนแปลง การตรวจสอบแหล่งจะไม่ซื้อหรือติดตั้งแอป
ru|Соглашение источника Microsoft Store|Принять и продолжить|Прочитать условия Microsoft Store|Для проверки Microsoft Copilot программе WinGet необходим источник Microsoft Store.|Выбирая Принять и продолжить, вы принимаете условия источника Microsoft Store и разрешаете WinGet отправить Microsoft двухбуквенный код региона этого ПК. WinGet может запомнить это согласие.|Отмена останавливает операцию до внесения изменений. Проверка источника не покупает и не устанавливает приложения.
uk|Угода джерела Microsoft Store|Прийняти й продовжити|Прочитати умови Microsoft Store|Для перевірки Microsoft Copilot програма WinGet має використовувати джерело Microsoft Store.|Вибираючи Прийняти й продовжити, ви приймаєте умови джерела Microsoft Store та дозволяєте WinGet надіслати Microsoft дволітерний код регіону цього ПК. WinGet може запам’ятати цю згоду.|Скасування зупиняє операцію до внесення змін. Перевірка джерела не купує та не встановлює програм.
pt|Acordo da origem Microsoft Store|Aceitar e continuar|Ler os termos da Microsoft Store|Para verificar o Microsoft Copilot, o WinGet tem de usar a origem Microsoft Store.|Escolher Aceitar e continuar aceita os termos da origem Microsoft Store e permite ao WinGet enviar à Microsoft o código de região de duas letras deste PC. O WinGet pode guardar essa aceitação.|Cancelar interrompe esta operação antes de qualquer alteração. Verificar a origem não compra nem instala aplicações.
ja|Microsoft Store ソースの契約|同意して続行|Microsoft Store の条件を読む|Microsoft Copilot を確認するには、WinGet が Microsoft Store ソースを使用する必要があります。|「同意して続行」を選ぶと、Microsoft Store ソースの条件に同意し、WinGet がこの PC の2文字の地域コードを Microsoft に送信することを許可します。WinGet はこの同意を記憶する場合があります。|キャンセルすると、変更を行う前にこの操作を停止します。ソースの確認でアプリを購入またはインストールすることはありません。
ko|Microsoft Store 원본 계약|동의하고 계속|Microsoft Store 약관 읽기|Microsoft Copilot을 확인하려면 WinGet이 Microsoft Store 원본을 사용해야 합니다.|동의하고 계속을 선택하면 Microsoft Store 원본 약관에 동의하고 WinGet이 이 PC의 두 글자 지역 코드를 Microsoft에 전송하도록 허용합니다. WinGet은 이 동의를 기억할 수 있습니다.|취소하면 변경 전에 이 작업을 중지합니다. 원본 확인은 앱을 구매하거나 설치하지 않습니다.
ur|Microsoft Store ماخذ کا معاہدہ|اتفاق کریں اور جاری رکھیں|Microsoft Store کی شرائط پڑھیں|Microsoft Copilot کی جانچ کے لیے WinGet کو Microsoft Store ماخذ استعمال کرنا ہوگا۔|اتفاق کریں اور جاری رکھیں منتخب کرنے سے Microsoft Store ماخذ کی شرائط قبول ہوتی ہیں اور WinGet کو اس PC کا دو حرفی علاقائی کوڈ Microsoft کو بھیجنے کی اجازت ملتی ہے۔ WinGet یہ منظوری محفوظ کر سکتا ہے۔|منسوخ کرنے سے کسی بھی تبدیلی سے پہلے یہ کارروائی رک جاتی ہے۔ ماخذ کی جانچ ایپس خریدتی یا انسٹال نہیں کرتی۔
ta|Microsoft Store மூல ஒப்பந்தம்|ஏற்று தொடரவும்|Microsoft Store விதிமுறைகளைப் படிக்கவும்|Microsoft Copilot ஐச் சரிபார்க்க WinGet Microsoft Store மூலத்தைப் பயன்படுத்த வேண்டும்.|ஏற்று தொடரவும் என்பதைத் தேர்ந்தெடுத்தால் Microsoft Store மூல விதிமுறைகள் ஏற்கப்பட்டு, இந்த PC இன் இரண்டெழுத்து பிராந்தியக் குறியீட்டை Microsoft க்கு அனுப்ப WinGet அனுமதிக்கப்படும். இந்த ஏற்பை WinGet நினைவில் வைத்திருக்கலாம்.|ரத்துசெய்வது மாற்றங்களுக்கு முன்பே இச்செயலை நிறுத்தும். மூலத்தைச் சரிபார்ப்பது செயலிகளை வாங்கவோ நிறுவவோ செய்யாது.
hi|Microsoft Store स्रोत समझौता|सहमत होकर जारी रखें|Microsoft Store की शर्तें पढ़ें|Microsoft Copilot की जाँच के लिए WinGet को Microsoft Store स्रोत का उपयोग करना होगा।|सहमत होकर जारी रखें चुनने पर Microsoft Store स्रोत की शर्तें स्वीकार होती हैं और WinGet को इस PC का दो-अक्षरीय क्षेत्र कोड Microsoft को भेजने की अनुमति मिलती है। WinGet इस स्वीकृति को याद रख सकता है।|रद्द करने से किसी भी बदलाव से पहले यह कार्रवाई रुक जाती है। स्रोत की जाँच ऐप खरीदती या इंस्टॉल नहीं करती।
ms|Perjanjian sumber Microsoft Store|Setuju dan teruskan|Baca syarat Microsoft Store|Untuk menyemak Microsoft Copilot, WinGet mesti menggunakan sumber Microsoft Store.|Memilih Setuju dan teruskan menerima syarat sumber Microsoft Store dan membenarkan WinGet menghantar kod rantau dua huruf PC ini kepada Microsoft. WinGet mungkin menyimpan persetujuan itu.|Batal menghentikan operasi ini sebelum sebarang perubahan. Menyemak sumber tidak membeli atau memasang aplikasi.
jv|Persetujuan sumber Microsoft Store|Sarujuk lan terusake|Waca syarat Microsoft Store|Kanggo mriksa Microsoft Copilot, WinGet kudu nganggo sumber Microsoft Store.|Milih Sarujuk lan terusake tegese nampa syarat sumber Microsoft Store lan ngidini WinGet ngirim kode wilayah rong aksara PC iki menyang Microsoft. WinGet bisa nyimpen persetujuan iki.|Batal mungkasi operasi iki sadurunge ana owah-owahan. Mriksa sumber ora tuku utawa masang aplikasi.
ban|Persetujuan sumber Microsoft Store|Setuju lan lanturang|Waca syarat Microsoft Store|Anggen mriksa Microsoft Copilot, WinGet patut nganggen sumber Microsoft Store.|Milih Setuju lan lanturang maartos nampi syarat sumber Microsoft Store miwah ngicen izin WinGet ngirim kode wilayah kalih aksara PC puniki ring Microsoft. WinGet prasida nyimpen persetujuan puniki.|Batal ngendegang operasi puniki sadurung wenten pangowahan. Mriksa sumber nenten numbas utawi masang aplikasi.
sv|Avtal för Microsoft Store-källan|Godkänn och fortsätt|Läs Microsoft Stores villkor|För att kontrollera Microsoft Copilot måste WinGet använda Microsoft Store-källan.|Genom att välja Godkänn och fortsätt accepterar du Microsoft Store-källans villkor och tillåter att WinGet skickar datorns regionkod på två bokstäver till Microsoft. WinGet kan komma ihåg godkännandet.|Avbryt stoppar åtgärden innan några ändringar görs. Kontroll av källan köper eller installerar inga appar.
es|Acuerdo de la fuente Microsoft Store|Aceptar y continuar|Leer los términos de Microsoft Store|Para comprobar Microsoft Copilot, WinGet debe usar la fuente Microsoft Store.|Al elegir Aceptar y continuar, aceptas los términos de la fuente Microsoft Store y permites que WinGet envíe a Microsoft el código regional de dos letras de este PC. WinGet puede recordar esa aceptación.|Cancelar detiene esta operación antes de cualquier cambio. Comprobar la fuente no compra ni instala aplicaciones.
""";
}
