using System;
using System.Collections.Generic;

namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    // Aliases are wording variants with the same meaning. Do not alias warnings
    // to generic messages or drop the distinction between OFF and Restore.
    private static readonly Dictionary<string, string> WorkflowAliases = new(StringComparer.Ordinal)
    {
        ["Administrator rights required"] = "Administrator rights are required.",
        ["Select at least one available item."] = "Select one or more available items first."
    };

    private const string WorkflowResults = """
en|Actual: {0}|Before: {0}|After: {0}|Result: {0}|PARTIAL|Applied {0}/{1}|Not applicable {0}|Apply completed for {0} item(s). See the progress window for details.|Restore completed for {0} item(s). See the progress window for details.|Apply completed with {0} failure(s). See the progress window for details.|Restore completed with {0} failure(s). See the progress window for details.|Processed {0}/{1}: {2}|Current states loaded; {0} item(s) are unavailable on this PC and their Select and ON/OFF controls remain disabled.|Checking {0} current setting(s)... You can review and resize this window while the checks finish.|Applied and verified {0} change(s). Restart Windows for settings marked as reboot-sensitive.|Restored and verified {0} item(s).|Unable to load the catalog state: {0}|{0}% complete
id|Aktual: {0}|Sebelum: {0}|Sesudah: {0}|Hasil: {0}|SEBAGIAN|Diterapkan {0}/{1}|Tidak berlaku {0}|Penerapan selesai untuk {0} item. Lihat rincian di jendela progres.|Pemulihan selesai untuk {0} item. Lihat rincian di jendela progres.|Penerapan selesai dengan {0} kegagalan. Lihat rincian di jendela progres.|Pemulihan selesai dengan {0} kegagalan. Lihat rincian di jendela progres.|Diproses {0}/{1}: {2}|Keadaan saat ini dimuat; {0} item tidak tersedia di PC ini dan kontrol Pilih serta AKTIF/NONAKTIF-nya tetap dinonaktifkan.|Memeriksa {0} pengaturan saat ini... Anda dapat meninjau dan mengubah ukuran jendela selama pemeriksaan berlangsung.|{0} perubahan diterapkan dan diverifikasi. Mulai ulang Windows untuk pengaturan yang ditandai memerlukan mulai ulang.|{0} item dipulihkan dan diverifikasi.|Tidak dapat memuat keadaan katalog: {0}|{0}% selesai
de|Tatsächlich: {0}|Vorher: {0}|Nachher: {0}|Ergebnis: {0}|TEILWEISE|Angewendet {0}/{1}|Nicht anwendbar {0}|Anwendung für {0} Einträge abgeschlossen. Details stehen im Fortschrittsfenster.|Wiederherstellung für {0} Einträge abgeschlossen. Details stehen im Fortschrittsfenster.|Anwendung mit {0} Fehlern abgeschlossen. Details stehen im Fortschrittsfenster.|Wiederherstellung mit {0} Fehlern abgeschlossen. Details stehen im Fortschrittsfenster.|Verarbeitet {0}/{1}: {2}|Aktuelle Zustände geladen; {0} Einträge sind auf diesem PC nicht verfügbar. Auswahl und EIN/AUS-Steuerung bleiben deaktiviert.|Prüfung von {0} aktuellen Einstellungen... Währenddessen können Sie dieses Fenster ansehen und seine Größe ändern.|{0} Änderungen angewendet und überprüft. Windows für Einstellungen neu starten, die als neustartabhängig markiert sind.|{0} Einträge wiederhergestellt und überprüft.|Katalogzustand konnte nicht geladen werden: {0}|{0}% abgeschlossen
fr|État réel : {0}|Avant : {0}|Après : {0}|Résultat : {0}|PARTIEL|Appliqué {0}/{1}|Non applicable {0}|Application terminée pour {0} éléments. Consultez les détails dans la fenêtre de progression.|Restauration terminée pour {0} éléments. Consultez les détails dans la fenêtre de progression.|Application terminée avec {0} échecs. Consultez les détails dans la fenêtre de progression.|Restauration terminée avec {0} échecs. Consultez les détails dans la fenêtre de progression.|Traité {0}/{1} : {2}|États actuels chargés ; {0} éléments sont indisponibles sur ce PC et leurs commandes de sélection et d’activation restent désactivées.|Vérification de {0} paramètres actuels... Vous pouvez consulter et redimensionner cette fenêtre pendant les vérifications.|{0} modifications appliquées et vérifiées. Redémarrez Windows pour les paramètres indiqués comme nécessitant un redémarrage.|{0} éléments restaurés et vérifiés.|Impossible de charger l’état du catalogue : {0}|{0}% terminé
ar|الحالة الفعلية: {0}|قبل: {0}|بعد: {0}|النتيجة: {0}|جزئي|طُبّق {0}/{1}|غير قابل للتطبيق {0}|اكتمل التطبيق لـ {0} عناصر. راجع نافذة التقدم للتفاصيل.|اكتملت استعادة {0} عناصر. راجع نافذة التقدم للتفاصيل.|اكتمل التطبيق مع {0} إخفاقات. راجع نافذة التقدم للتفاصيل.|اكتملت الاستعادة مع {0} إخفاقات. راجع نافذة التقدم للتفاصيل.|عولج {0}/{1}: {2}|حُمّلت الحالات الحالية؛ {0} عناصر غير متاحة على هذا الحاسوب وتظل أدوات تحديدها وتشغيلها أو إيقافها معطلة.|جارٍ فحص {0} إعدادات حالية... يمكنك مراجعة هذه النافذة وتغيير حجمها أثناء الفحص.|طُبّقت {0} تغييرات وتم التحقق منها. أعد تشغيل Windows للإعدادات التي تتطلب ذلك.|استُعيدت {0} عناصر وتم التحقق منها.|تعذر تحميل حالة الفهرس: {0}|اكتمل {0}%
tl|Aktuwal: {0}|Bago: {0}|Pagkatapos: {0}|Resulta: {0}|BAHAGYA|Nailapat {0}/{1}|Hindi naaangkop {0}|Tapos na ang paglalapat sa {0} item. Tingnan ang mga detalye sa bintana ng pag-usad.|Tapos na ang pagpapanumbalik sa {0} item. Tingnan ang mga detalye sa bintana ng pag-usad.|Tapos na ang paglalapat na may {0} pagkabigo. Tingnan ang mga detalye sa bintana ng pag-usad.|Tapos na ang pagpapanumbalik na may {0} pagkabigo. Tingnan ang mga detalye sa bintana ng pag-usad.|Naproseso {0}/{1}: {2}|Na-load ang kasalukuyang mga kalagayan; hindi magagamit ang {0} item sa PC na ito at mananatiling naka-disable ang pagpili at ON/OFF na kontrol ng mga ito.|Sinusuri ang {0} kasalukuyang setting... Maaari mong tingnan at baguhin ang laki ng bintanang ito habang sinusuri.|Nailapat at napatunayan ang {0} pagbabago. I-restart ang Windows para sa mga setting na minarkahang nangangailangan ng pag-restart.|Naibalik at napatunayan ang {0} item.|Hindi ma-load ang kalagayan ng katalogo: {0}|{0}% tapos na
vi|Thực tế: {0}|Trước: {0}|Sau: {0}|Kết quả: {0}|MỘT PHẦN|Đã áp dụng {0}/{1}|Không áp dụng {0}|Đã áp dụng xong cho {0} mục. Xem chi tiết trong cửa sổ tiến độ.|Đã khôi phục xong cho {0} mục. Xem chi tiết trong cửa sổ tiến độ.|Áp dụng hoàn tất với {0} lỗi. Xem chi tiết trong cửa sổ tiến độ.|Khôi phục hoàn tất với {0} lỗi. Xem chi tiết trong cửa sổ tiến độ.|Đã xử lý {0}/{1}: {2}|Đã tải trạng thái hiện tại; {0} mục không khả dụng trên PC này và điều khiển chọn, BẬT/TẮT của chúng vẫn bị vô hiệu hóa.|Đang kiểm tra {0} cài đặt hiện tại... Bạn có thể xem và đổi kích thước cửa sổ này trong khi kiểm tra.|Đã áp dụng và xác minh {0} thay đổi. Khởi động lại Windows cho các cài đặt được đánh dấu yêu cầu khởi động lại.|Đã khôi phục và xác minh {0} mục.|Không thể tải trạng thái danh mục: {0}|Hoàn tất {0}%
zh-CN|实际状态：{0}|之前：{0}|之后：{0}|结果：{0}|部分|已应用 {0}/{1}|不适用 {0}|已为 {0} 个项目完成应用。请在进度窗口中查看详情。|已为 {0} 个项目完成还原。请在进度窗口中查看详情。|应用已结束，有 {0} 项失败。请在进度窗口中查看详情。|还原已结束，有 {0} 项失败。请在进度窗口中查看详情。|已处理 {0}/{1}：{2}|当前状态已加载；此电脑上有 {0} 个项目不可用，其选择和开关控件将保持禁用。|正在检查 {0} 项当前设置...检查过程中可以查看此窗口并调整其大小。|已应用并验证 {0} 项更改。请为标记为需要重新启动的设置重新启动 Windows。|已还原并验证 {0} 个项目。|无法加载目录状态：{0}|已完成 {0}%
zh-TW|實際狀態：{0}|之前：{0}|之後：{0}|結果：{0}|部分|已套用 {0}/{1}|不適用 {0}|已為 {0} 個項目完成套用。請在進度視窗中查看詳細資料。|已為 {0} 個項目完成還原。請在進度視窗中查看詳細資料。|套用已結束，有 {0} 項失敗。請在進度視窗中查看詳細資料。|還原已結束，有 {0} 項失敗。請在進度視窗中查看詳細資料。|已處理 {0}/{1}：{2}|目前狀態已載入；此電腦上有 {0} 個項目無法使用，其選取和開關控制項將保持停用。|正在檢查 {0} 項目前設定...檢查期間可以查看此視窗並調整大小。|已套用並驗證 {0} 項變更。請為標記為需要重新啟動的設定重新啟動 Windows。|已還原並驗證 {0} 個項目。|無法載入目錄狀態：{0}|已完成 {0}%
th|สถานะจริง: {0}|ก่อน: {0}|หลัง: {0}|ผลลัพธ์: {0}|บางส่วน|นำไปใช้แล้ว {0}/{1}|ใช้ไม่ได้ {0}|นำไปใช้เสร็จแล้ว {0} รายการ ดูรายละเอียดในหน้าต่างความคืบหน้า|กู้คืนเสร็จแล้ว {0} รายการ ดูรายละเอียดในหน้าต่างความคืบหน้า|นำไปใช้เสร็จแต่ล้มเหลว {0} รายการ ดูรายละเอียดในหน้าต่างความคืบหน้า|กู้คืนเสร็จแต่ล้มเหลว {0} รายการ ดูรายละเอียดในหน้าต่างความคืบหน้า|ประมวลผลแล้ว {0}/{1}: {2}|โหลดสถานะปัจจุบันแล้ว มี {0} รายการที่ใช้ไม่ได้บน PC นี้ และตัวเลือกกับสวิตช์เปิด/ปิดจะยังคงถูกปิดใช้งาน|กำลังตรวจสอบการตั้งค่าปัจจุบัน {0} รายการ... คุณสามารถดูและปรับขนาดหน้าต่างนี้ระหว่างการตรวจสอบได้|นำไปใช้และตรวจสอบแล้ว {0} การเปลี่ยนแปลง รีสตาร์ต Windows สำหรับการตั้งค่าที่ระบุว่าต้องรีสตาร์ต|กู้คืนและตรวจสอบแล้ว {0} รายการ|ไม่สามารถโหลดสถานะแค็ตตาล็อก: {0}|เสร็จสิ้น {0}%
ru|Фактически: {0}|До: {0}|После: {0}|Результат: {0}|ЧАСТИЧНО|Применено {0}/{1}|Неприменимо {0}|Применение завершено для {0} элементов. Подробности в окне выполнения.|Восстановление завершено для {0} элементов. Подробности в окне выполнения.|Применение завершено с ошибками: {0}. Подробности в окне выполнения.|Восстановление завершено с ошибками: {0}. Подробности в окне выполнения.|Обработано {0}/{1}: {2}|Текущие состояния загружены; {0} элементов недоступны на этом ПК, их выбор и переключатели ВКЛ/ВЫКЛ остаются отключёнными.|Проверка текущих настроек: {0}... Во время проверки можно просматривать и изменять размер этого окна.|Применено и проверено изменений: {0}. Перезапустите Windows для настроек, помеченных как требующие перезапуска.|Восстановлено и проверено элементов: {0}.|Не удалось загрузить состояние каталога: {0}|Выполнено {0}%
uk|Фактично: {0}|До: {0}|Після: {0}|Результат: {0}|ЧАСТКОВО|Застосовано {0}/{1}|Не застосовується {0}|Застосування завершено для {0} елементів. Докладніше у вікні перебігу.|Відновлення завершено для {0} елементів. Докладніше у вікні перебігу.|Застосування завершено з помилками: {0}. Докладніше у вікні перебігу.|Відновлення завершено з помилками: {0}. Докладніше у вікні перебігу.|Оброблено {0}/{1}: {2}|Поточні стани завантажено; {0} елементів недоступні на цьому ПК, їх вибір і перемикачі УВІМК/ВИМК залишаються вимкненими.|Перевірка поточних налаштувань: {0}... Під час перевірки можна переглядати й змінювати розмір цього вікна.|Застосовано й перевірено змін: {0}. Перезапустіть Windows для налаштувань, позначених як такі, що потребують перезапуску.|Відновлено й перевірено елементів: {0}.|Не вдалося завантажити стан каталогу: {0}|Виконано {0}%
pt|Estado real: {0}|Antes: {0}|Depois: {0}|Resultado: {0}|PARCIAL|Aplicado {0}/{1}|Não aplicável {0}|Aplicação concluída para {0} itens. Consulte os detalhes na janela de progresso.|Restauro concluído para {0} itens. Consulte os detalhes na janela de progresso.|Aplicação concluída com {0} falhas. Consulte os detalhes na janela de progresso.|Restauro concluído com {0} falhas. Consulte os detalhes na janela de progresso.|Processado {0}/{1}: {2}|Estados atuais carregados; {0} itens estão indisponíveis neste PC e os controlos de seleção e LIGADO/DESLIGADO continuam desativados.|A verificar {0} definições atuais... Pode consultar e redimensionar esta janela durante as verificações.|{0} alterações aplicadas e verificadas. Reinicie o Windows para definições assinaladas como dependentes de reinício.|{0} itens restaurados e verificados.|Não foi possível carregar o estado do catálogo: {0}|{0}% concluído
ja|実際の状態：{0}|変更前：{0}|変更後：{0}|結果：{0}|一部|適用済み {0}/{1}|適用対象外 {0}|{0} 項目への適用が完了しました。詳細は進行状況ウィンドウをご覧ください。|{0} 項目の復元が完了しました。詳細は進行状況ウィンドウをご覧ください。|適用は終了しましたが、{0} 件失敗しました。詳細は進行状況ウィンドウをご覧ください。|復元は終了しましたが、{0} 件失敗しました。詳細は進行状況ウィンドウをご覧ください。|処理済み {0}/{1}：{2}|現在の状態を読み込みました。この PC では {0} 項目を利用できず、その選択とオン／オフの操作は無効のままです。|現在の設定を {0} 件確認しています...確認中もこのウィンドウの閲覧やサイズ変更ができます。|{0} 件の変更を適用して検証しました。再起動が必要と記された設定については Windows を再起動してください。|{0} 項目を復元して検証しました。|カタログの状態を読み込めません：{0}|{0}% 完了
ko|실제 상태: {0}|이전: {0}|이후: {0}|결과: {0}|일부|적용됨 {0}/{1}|적용 대상 아님 {0}|{0}개 항목의 적용이 완료되었습니다. 자세한 내용은 진행 창을 확인하세요.|{0}개 항목의 복원이 완료되었습니다. 자세한 내용은 진행 창을 확인하세요.|적용이 끝났지만 {0}건 실패했습니다. 자세한 내용은 진행 창을 확인하세요.|복원이 끝났지만 {0}건 실패했습니다. 자세한 내용은 진행 창을 확인하세요.|처리됨 {0}/{1}: {2}|현재 상태를 불러왔습니다. 이 PC에서는 {0}개 항목을 사용할 수 없으며 해당 선택 및 켜기/끄기 컨트롤은 비활성 상태로 유지됩니다.|현재 설정 {0}개를 확인하는 중...확인 중에도 이 창을 살펴보고 크기를 바꿀 수 있습니다.|변경 {0}건을 적용하고 검증했습니다. 다시 시작이 필요한 것으로 표시된 설정은 Windows를 다시 시작하세요.|{0}개 항목을 복원하고 검증했습니다.|카탈로그 상태를 불러올 수 없음: {0}|{0}% 완료
ur|اصل حالت: {0}|پہلے: {0}|بعد: {0}|نتیجہ: {0}|جزوی|لاگو {0}/{1}|لاگو نہیں {0}|{0} اشیا پر اطلاق مکمل۔ تفصیل کے لیے پیش رفت کی کھڑکی دیکھیں۔|{0} اشیا کی بحالی مکمل۔ تفصیل کے لیے پیش رفت کی کھڑکی دیکھیں۔|اطلاق {0} ناکامیوں کے ساتھ مکمل۔ تفصیل کے لیے پیش رفت کی کھڑکی دیکھیں۔|بحالی {0} ناکامیوں کے ساتھ مکمل۔ تفصیل کے لیے پیش رفت کی کھڑکی دیکھیں۔|عمل مکمل {0}/{1}: {2}|موجودہ حالتیں لوڈ ہو گئیں؛ اس PC پر {0} اشیا دستیاب نہیں اور ان کے انتخاب اور چالو/بند کنٹرول غیر فعال رہیں گے۔|{0} موجودہ ترتیبات کی جانچ ہو رہی ہے... آپ جانچ کے دوران یہ کھڑکی دیکھ سکتے ہیں اور اس کا سائز بدل سکتے ہیں۔|{0} تبدیلیاں لاگو اور تصدیق شدہ۔ دوبارہ آغاز درکار والی ترتیبات کے لیے Windows دوبارہ شروع کریں۔|{0} اشیا بحال اور تصدیق شدہ۔|فہرست کی حالت لوڈ نہیں ہو سکی: {0}|{0}% مکمل
ta|உண்மை நிலை: {0}|முன்பு: {0}|பின்பு: {0}|முடிவு: {0}|பகுதி|பயன்படுத்தியது {0}/{1}|பொருந்தாதது {0}|{0} உருப்படிகளுக்குப் பயன்படுத்துதல் முடிந்தது. விவரங்களுக்கு முன்னேற்றச் சாளரத்தைப் பார்க்கவும்.|{0} உருப்படிகளின் மீட்டமைப்பு முடிந்தது. விவரங்களுக்கு முன்னேற்றச் சாளரத்தைப் பார்க்கவும்.|{0} தோல்விகளுடன் பயன்படுத்துதல் முடிந்தது. விவரங்களுக்கு முன்னேற்றச் சாளரத்தைப் பார்க்கவும்.|{0} தோல்விகளுடன் மீட்டமைப்பு முடிந்தது. விவரங்களுக்கு முன்னேற்றச் சாளரத்தைப் பார்க்கவும்.|செயலாக்கியது {0}/{1}: {2}|தற்போதைய நிலைகள் ஏற்றப்பட்டன; இந்த PC-இல் {0} உருப்படிகள் கிடைக்கவில்லை. அவற்றின் தேர்வு மற்றும் இயக்க/முடக்கக் கட்டுப்பாடுகள் முடக்கப்பட்டே இருக்கும்.|{0} தற்போதைய அமைப்புகளைச் சரிபார்க்கிறது... சரிபார்ப்பின்போது இந்தச் சாளரத்தைப் பார்க்கவும் அளவை மாற்றவும் முடியும்.|{0} மாற்றங்கள் பயன்படுத்தப்பட்டுச் சரிபார்க்கப்பட்டன. மறுதொடக்கம் தேவை எனக் குறிக்கப்பட்ட அமைப்புகளுக்கு Windows-ஐ மறுதொடக்கம் செய்யவும்.|{0} உருப்படிகள் மீட்டமைக்கப்பட்டுச் சரிபார்க்கப்பட்டன.|பட்டியலின் நிலையை ஏற்ற முடியவில்லை: {0}|{0}% முடிந்தது
hi|वास्तविक स्थिति: {0}|पहले: {0}|बाद में: {0}|परिणाम: {0}|आंशिक|लागू {0}/{1}|लागू नहीं {0}|{0} आइटम पर लागू करना पूरा हुआ। विवरण के लिए प्रगति विंडो देखें।|{0} आइटम का पुनर्स्थापन पूरा हुआ। विवरण के लिए प्रगति विंडो देखें।|लागू करना {0} विफलताओं के साथ पूरा हुआ। विवरण के लिए प्रगति विंडो देखें।|पुनर्स्थापन {0} विफलताओं के साथ पूरा हुआ। विवरण के लिए प्रगति विंडो देखें।|संसाधित {0}/{1}: {2}|वर्तमान स्थितियाँ लोड हुईं; इस PC पर {0} आइटम उपलब्ध नहीं हैं और उनके चयन तथा चालू/बंद नियंत्रण निष्क्रिय रहेंगे।|{0} वर्तमान सेटिंग की जाँच हो रही है... जाँच के दौरान आप इस विंडो को देख और इसका आकार बदल सकते हैं।|{0} बदलाव लागू और सत्यापित किए गए। पुनरारंभ आवश्यक चिह्नित सेटिंग के लिए Windows फिर से शुरू करें।|{0} आइटम पुनर्स्थापित और सत्यापित किए गए।|कैटलॉग की स्थिति लोड नहीं हो सकी: {0}|{0}% पूरा
ms|Keadaan sebenar: {0}|Sebelum: {0}|Selepas: {0}|Hasil: {0}|SEBAHAGIAN|Digunakan {0}/{1}|Tidak berkenaan {0}|Penggunaan selesai untuk {0} item. Lihat butiran dalam tetingkap kemajuan.|Pemulihan selesai untuk {0} item. Lihat butiran dalam tetingkap kemajuan.|Penggunaan selesai dengan {0} kegagalan. Lihat butiran dalam tetingkap kemajuan.|Pemulihan selesai dengan {0} kegagalan. Lihat butiran dalam tetingkap kemajuan.|Diproses {0}/{1}: {2}|Keadaan semasa dimuatkan; {0} item tidak tersedia pada PC ini dan kawalan Pilih serta HIDUP/MATI kekal dinyahdayakan.|Memeriksa {0} tetapan semasa... Anda boleh menyemak dan mengubah saiz tetingkap ini semasa pemeriksaan berjalan.|{0} perubahan digunakan dan disahkan. Mulakan semula Windows bagi tetapan yang ditandai memerlukan mula semula.|{0} item dipulihkan dan disahkan.|Tidak dapat memuatkan keadaan katalog: {0}|{0}% selesai
jv|Kahanan nyata: {0}|Sadurunge: {0}|Sawise: {0}|Asil: {0}|SAWETARA|Ditrapake {0}/{1}|Ora cocog {0}|Pangetrapan rampung kanggo {0} item. Delengen rincian ing jendhela kemajuan.|Pamulihan rampung kanggo {0} item. Delengen rincian ing jendhela kemajuan.|Pangetrapan rampung kanthi {0} kegagalan. Delengen rincian ing jendhela kemajuan.|Pamulihan rampung kanthi {0} kegagalan. Delengen rincian ing jendhela kemajuan.|Diproses {0}/{1}: {2}|Kahanan saiki dimuat; {0} item ora kasedhiya ing PC iki lan kontrol Pilih lan URIP/MATI tetep dipateni.|Lagi mriksa {0} setelan saiki... Sampeyan bisa ndeleng lan ngowahi ukuran jendhela iki nalika pamriksan mlaku.|{0} owah-owahan ditrapake lan diverifikasi. Wiwiti maneh Windows kanggo setelan sing ditandhani mbutuhake wiwit maneh.|{0} item dipulihake lan diverifikasi.|Ora bisa ngemot kahanan katalog: {0}|{0}% rampung
ban|Kawentenan nyata: {0}|Sadurung: {0}|Sasampun: {0}|Pikolehan: {0}|SAPALIH|Katerapang {0}/{1}|Nenten manut {0}|Pangetrapan puput antuk {0} item. Cingak rincian ring jendela kemajuan.|Pamulihan puput antuk {0} item. Cingak rincian ring jendela kemajuan.|Pangetrapan puput sareng {0} kegagalan. Cingak rincian ring jendela kemajuan.|Pamulihan puput sareng {0} kegagalan. Cingak rincian ring jendela kemajuan.|Kaproses {0}/{1}: {2}|Kawentenan mangkin kamuat; {0} item nenten wenten ring PC puniki miwah kontrol Pilih sareng URIP/PEJAH tetep kapejahang.|Sedek mriksa {0} setelan mangkin... Ragane prasida nyingakin miwah ngentos ukuran jendela puniki rikala pamriksaan mamargi.|{0} pangentosan katerapang miwah kaverifikasi. Wiwiti malih Windows antuk setelan sane katandain perlu wiwit malih.|{0} item kapulihang miwah kaverifikasi.|Nenten prasida ngemuat kawentenan katalog: {0}|{0}% puput
sv|Faktiskt: {0}|Före: {0}|Efter: {0}|Resultat: {0}|DELVIS|Tillämpat {0}/{1}|Inte tillämpligt {0}|Tillämpning klar för {0} objekt. Se detaljerna i förloppsfönstret.|Återställning klar för {0} objekt. Se detaljerna i förloppsfönstret.|Tillämpning klar med {0} fel. Se detaljerna i förloppsfönstret.|Återställning klar med {0} fel. Se detaljerna i förloppsfönstret.|Bearbetat {0}/{1}: {2}|Aktuella tillstånd hämtade; {0} objekt är inte tillgängliga på denna PC och deras val- och PÅ/AV-kontroller förblir inaktiverade.|Kontrollerar {0} aktuella inställningar... Du kan granska och ändra storlek på fönstret medan kontrollerna pågår.|{0} ändringar tillämpade och verifierade. Starta om Windows för inställningar markerade som omstartsberoende.|{0} objekt återställda och verifierade.|Kunde inte läsa in katalogens tillstånd: {0}|{0}% klart
es|Estado real: {0}|Antes: {0}|Después: {0}|Resultado: {0}|PARCIAL|Aplicado {0}/{1}|No aplicable {0}|Aplicación completada para {0} elementos. Consulte los detalles en la ventana de progreso.|Restauración completada para {0} elementos. Consulte los detalles en la ventana de progreso.|Aplicación completada con {0} fallos. Consulte los detalles en la ventana de progreso.|Restauración completada con {0} fallos. Consulte los detalles en la ventana de progreso.|Procesado {0}/{1}: {2}|Estados actuales cargados; {0} elementos no están disponibles en este PC y sus controles de selección y activación siguen deshabilitados.|Comprobando {0} ajustes actuales... Puede revisar y cambiar el tamaño de esta ventana durante las comprobaciones.|{0} cambios aplicados y verificados. Reinicie Windows para los ajustes marcados como dependientes del reinicio.|{0} elementos restaurados y verificados.|No se pudo cargar el estado del catálogo: {0}|{0}% completado
""";
}
