namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string BuiltInApps = """
en|Built-in Windows Apps|Select Windows apps to uninstall or restore.|Uninstalling may delete local app data and disable app features. Back up your files first.|Only this Windows account is changed. Classic desktop apps, other accounts and provisioned apps are unchanged.|Restore reinstalls apps, not deleted personal data. Internet, Store availability and a valid license may be required.|Continuing allows Microsoft Store downloads and accepts the Store and package agreements. No purchases will be made.|Review apps|Uninstall selected|Installed|Not installed|Needs repair|Removing|Microsoft Store could not be opened.
id|Aplikasi Bawaan Windows|Pilih aplikasi Windows untuk dihapus atau dipulihkan.|Menghapus aplikasi dapat menghapus data lokal dan menonaktifkan fiturnya. Cadangkan berkas Anda terlebih dahulu.|Hanya akun Windows ini yang diubah. Aplikasi desktop klasik, akun lain, dan aplikasi yang disiapkan untuk pengguna baru tidak diubah.|Pemulihan memasang ulang aplikasi, bukan data pribadi yang terhapus. Internet, ketersediaan Store, dan lisensi yang valid mungkin diperlukan.|Melanjutkan mengizinkan unduhan Microsoft Store dan menyetujui perjanjian Store serta paket. Tidak ada pembelian yang dilakukan.|Tinjau aplikasi|Hapus yang dipilih|Terpasang|Belum terpasang|Perlu diperbaiki|Menghapus|Microsoft Store tidak dapat dibuka.
de|Integrierte Windows-Apps|Windows-Apps zum Deinstallieren oder Wiederherstellen auswählen.|Beim Deinstallieren können lokale App-Daten gelöscht und Funktionen deaktiviert werden. Sichern Sie zuerst Ihre Dateien.|Nur dieses Windows-Konto wird geändert. Klassische Desktop-Apps, andere Konten und bereitgestellte Apps bleiben unverändert.|Die Wiederherstellung installiert Apps erneut, nicht gelöschte persönliche Daten. Internet, Store-Verfügbarkeit und eine gültige Lizenz können erforderlich sein.|Durch Fortfahren erlauben Sie Microsoft-Store-Downloads und akzeptieren die Store- und Paketvereinbarungen. Es werden keine Käufe getätigt.|Apps prüfen|Auswahl deinstallieren|Installiert|Nicht installiert|Reparatur erforderlich|Wird entfernt|Microsoft Store konnte nicht geöffnet werden.
fr|Applications Windows intégrées|Sélectionnez les applications Windows à désinstaller ou restaurer.|La désinstallation peut supprimer les données locales et désactiver des fonctions. Sauvegardez vos fichiers au préalable.|Seul ce compte Windows est modifié. Les applications de bureau classiques, les autres comptes et les applications provisionnées restent inchangés.|La restauration réinstalle les applications, pas les données personnelles supprimées. Internet, la disponibilité du Store et une licence valide peuvent être nécessaires.|Continuer autorise les téléchargements Microsoft Store et accepte les accords du Store et des packages. Aucun achat ne sera effectué.|Examiner les applications|Désinstaller la sélection|Installé|Non installé|Réparation nécessaire|Suppression|Impossible d’ouvrir Microsoft Store.
ar|تطبيقات Windows المضمنة|حدد تطبيقات Windows لإلغاء تثبيتها أو استعادتها.|قد يؤدي إلغاء التثبيت إلى حذف بيانات التطبيق المحلية وتعطيل ميزاته. انسخ ملفاتك احتياطيًا أولاً.|يتم تغيير حساب Windows هذا فقط. لن تتغير تطبيقات سطح المكتب التقليدية أو الحسابات الأخرى أو التطبيقات المعدة مسبقًا.|تعيد الاستعادة تثبيت التطبيقات وليس البيانات الشخصية المحذوفة. قد يلزم الإنترنت وتوفر التطبيق في Store وترخيص صالح.|بالمتابعة تسمح بتنزيلات Microsoft Store وتوافق على اتفاقيات المتجر والحزم. لن تُجرى أي عمليات شراء.|مراجعة التطبيقات|إلغاء تثبيت المحدد|مثبّت|غير مثبّت|يحتاج إلى إصلاح|جارٍ الإزالة|تعذر فتح Microsoft Store.
tl|Mga Built-in na App ng Windows|Pumili ng Windows apps na aalisin o ibabalik.|Maaaring mabura ang lokal na datos at hindi gumana ang ilang feature kapag nag-uninstall. I-back up muna ang iyong mga file.|Ang Windows account na ito lang ang babaguhin. Hindi gagalawin ang klasikong desktop apps, ibang account at mga provisioned app.|Muling ini-install ng Restore ang apps, hindi ang naburang personal na datos. Maaaring kailangan ang Internet, availability sa Store at wastong lisensya.|Ang pagpapatuloy ay nagpapahintulot ng Microsoft Store downloads at pagtanggap sa mga kasunduan ng Store at package. Walang bibilhin.|Suriin ang apps|I-uninstall ang pinili|Naka-install|Hindi naka-install|Kailangang ayusin|Inaalis|Hindi mabuksan ang Microsoft Store.
vi|Ứng dụng tích hợp của Windows|Chọn ứng dụng Windows để gỡ cài đặt hoặc khôi phục.|Gỡ cài đặt có thể xóa dữ liệu cục bộ và vô hiệu hóa tính năng. Hãy sao lưu tệp trước.|Chỉ thay đổi tài khoản Windows này. Ứng dụng máy tính cổ điển, tài khoản khác và ứng dụng được cấp sẵn không thay đổi.|Khôi phục cài lại ứng dụng, không khôi phục dữ liệu cá nhân đã xóa. Có thể cần Internet, ứng dụng còn trên Store và giấy phép hợp lệ.|Tiếp tục cho phép tải từ Microsoft Store và chấp nhận thỏa thuận của Store và gói. Không thực hiện mua hàng.|Xem xét ứng dụng|Gỡ mục đã chọn|Đã cài đặt|Chưa cài đặt|Cần sửa chữa|Đang gỡ bỏ|Không mở được Microsoft Store.
zh-CN|Windows 内置应用|选择要卸载或还原的 Windows 应用。|卸载可能删除本地应用数据并停用应用功能。请先备份文件。|仅更改此 Windows 账户。传统桌面应用、其他账户和预配应用保持不变。|还原会重新安装应用，不会恢复已删除的个人数据。可能需要网络、Store 中仍提供该应用及有效许可证。|继续即允许从 Microsoft Store 下载并接受商店及程序包协议。不会进行购买。|查看应用|卸载所选项|已安装|未安装|需要修复|正在移除|无法打开 Microsoft Store。
zh-TW|Windows 內建應用程式|選取要解除安裝或還原的 Windows 應用程式。|解除安裝可能刪除本機應用程式資料並停用功能。請先備份檔案。|僅變更此 Windows 帳戶。傳統桌面應用程式、其他帳戶與佈建應用程式保持不變。|還原會重新安裝應用程式，不會復原已刪除的個人資料。可能需要網路、Store 仍提供該應用程式及有效授權。|繼續即允許從 Microsoft Store 下載並接受商店及套件合約。不會進行購買。|檢視應用程式|解除安裝選取項目|已安裝|未安裝|需要修復|正在移除|無法開啟 Microsoft Store。
th|แอปที่มาพร้อม Windows|เลือกแอป Windows ที่จะถอนการติดตั้งหรือคืนค่า|การถอนการติดตั้งอาจลบข้อมูลแอปในเครื่องและปิดฟีเจอร์ โปรดสำรองไฟล์ก่อน|เปลี่ยนเฉพาะบัญชี Windows นี้ แอปเดสก์ท็อปแบบเดิม บัญชีอื่น และแอปที่จัดเตรียมไว้จะไม่เปลี่ยนแปลง|การคืนค่าจะติดตั้งแอปใหม่ ไม่กู้ข้อมูลส่วนตัวที่ลบไป อาจต้องใช้อินเทอร์เน็ต แอปที่ยังมีใน Store และสิทธิ์ใช้งานที่ถูกต้อง|การดำเนินการต่ออนุญาตให้ดาวน์โหลดจาก Microsoft Store และยอมรับข้อตกลงของ Store และแพ็กเกจ จะไม่มีการซื้อ|ตรวจสอบแอป|ถอนการติดตั้งที่เลือก|ติดตั้งแล้ว|ยังไม่ติดตั้ง|ต้องซ่อมแซม|กำลังนำออก|ไม่สามารถเปิด Microsoft Store ได้
ru|Встроенные приложения Windows|Выберите приложения Windows для удаления или восстановления.|Удаление может стереть локальные данные и отключить функции приложений. Сначала сохраните резервные копии файлов.|Изменяется только эта учётная запись Windows. Классические приложения, другие учётные записи и подготовленные приложения не изменяются.|Восстановление переустанавливает приложения, но не удалённые личные данные. Могут потребоваться Интернет, наличие в Store и действующая лицензия.|Продолжая, вы разрешаете загрузки из Microsoft Store и принимаете соглашения Store и пакетов. Покупки не выполняются.|Просмотреть приложения|Удалить выбранное|Установлено|Не установлено|Требуется восстановление|Удаление|Не удалось открыть Microsoft Store.
uk|Вбудовані програми Windows|Виберіть програми Windows для видалення або відновлення.|Видалення може стерти локальні дані та вимкнути функції програм. Спочатку створіть резервні копії файлів.|Змінюється лише цей обліковий запис Windows. Класичні програми, інші облікові записи та підготовлені програми не змінюються.|Відновлення перевстановлює програми, але не видалені особисті дані. Можуть знадобитися Інтернет, доступність у Store і чинна ліцензія.|Продовжуючи, ви дозволяєте завантаження з Microsoft Store і приймаєте угоди Store та пакетів. Покупки не виконуються.|Переглянути програми|Видалити вибране|Установлено|Не встановлено|Потрібне відновлення|Видалення|Не вдалося відкрити Microsoft Store.
pt|Aplicações integradas do Windows|Selecione aplicações Windows para desinstalar ou restaurar.|A desinstalação pode eliminar dados locais e desativar funcionalidades. Faça primeiro uma cópia de segurança dos ficheiros.|Só esta conta Windows é alterada. As aplicações clássicas, outras contas e aplicações aprovisionadas ficam inalteradas.|O restauro reinstala aplicações, não dados pessoais eliminados. Pode exigir Internet, disponibilidade na Store e uma licença válida.|Ao continuar, permite transferências da Microsoft Store e aceita os contratos da Store e dos pacotes. Não serão efetuadas compras.|Rever aplicações|Desinstalar selecionadas|Instalado|Não instalado|Requer reparação|A remover|Não foi possível abrir a Microsoft Store.
ja|Windows 標準アプリ|アンインストールまたは復元する Windows アプリを選択してください。|アンインストールでローカルデータが削除され、機能が使えなくなる場合があります。先にファイルをバックアップしてください。|この Windows アカウントのみを変更します。従来のデスクトップアプリ、他のアカウント、プロビジョニング済みアプリは変更しません。|復元はアプリの再インストールであり、削除された個人データは戻りません。インターネット、Store での提供、有効なライセンスが必要な場合があります。|続行すると Microsoft Store からのダウンロードを許可し、Store とパッケージの契約に同意します。購入は行いません。|アプリを確認|選択項目をアンインストール|インストール済み|未インストール|修復が必要|削除中|Microsoft Store を開けませんでした。
ko|Windows 기본 앱|제거하거나 복원할 Windows 앱을 선택하세요.|제거하면 로컬 앱 데이터가 삭제되고 기능이 비활성화될 수 있습니다. 먼저 파일을 백업하세요.|이 Windows 계정만 변경됩니다. 기존 데스크톱 앱, 다른 계정 및 프로비전된 앱은 변경하지 않습니다.|복원은 앱을 다시 설치하며 삭제된 개인 데이터는 복구하지 않습니다. 인터넷, Store 제공 여부 및 유효한 라이선스가 필요할 수 있습니다.|계속하면 Microsoft Store 다운로드를 허용하고 Store 및 패키지 계약에 동의합니다. 구매는 수행하지 않습니다.|앱 검토|선택 항목 제거|설치됨|설치되지 않음|복구 필요|제거 중|Microsoft Store를 열 수 없습니다.
ur|Windows کی شامل ایپس|ان انسٹال یا بحال کرنے کے لیے Windows ایپس منتخب کریں۔|ان انسٹال کرنے سے مقامی ایپ ڈیٹا حذف اور خصوصیات غیر فعال ہو سکتی ہیں۔ پہلے اپنی فائلوں کا بیک اپ بنائیں۔|صرف اس Windows اکاؤنٹ میں تبدیلی ہوگی۔ روایتی ڈیسک ٹاپ ایپس، دوسرے اکاؤنٹس اور پہلے سے فراہم کردہ ایپس تبدیل نہیں ہوں گی۔|بحالی ایپس دوبارہ انسٹال کرتی ہے، حذف شدہ ذاتی ڈیٹا واپس نہیں لاتی۔ انٹرنیٹ، Store میں دستیابی اور درست لائسنس درکار ہو سکتا ہے۔|جاری رکھنے سے Microsoft Store ڈاؤن لوڈز کی اجازت اور Store و پیکیج معاہدوں کی منظوری ملتی ہے۔ کوئی خریداری نہیں ہوگی۔|ایپس کا جائزہ لیں|منتخب ایپس ان انسٹال کریں|انسٹال ہے|انسٹال نہیں ہے|مرمت درکار ہے|ہٹایا جا رہا ہے|Microsoft Store نہیں کھولا جا سکا۔
ta|Windows உள்ளமைந்த பயன்பாடுகள்|நிறுவல் நீக்க அல்லது மீட்டமைக்க Windows பயன்பாடுகளைத் தேர்ந்தெடுக்கவும்.|நிறுவல் நீக்கம் உள்ளூர் தரவை அழித்து அம்சங்களை முடக்கலாம். முதலில் கோப்புகளை காப்புப் பிரதி எடுக்கவும்.|இந்த Windows கணக்கு மட்டுமே மாற்றப்படும். பழைய டெஸ்க்டாப் பயன்பாடுகள், பிற கணக்குகள் மற்றும் முன் ஒதுக்கப்பட்ட பயன்பாடுகள் மாற்றப்படாது.|மீட்டமைப்பு பயன்பாடுகளை மீண்டும் நிறுவும்; அழிக்கப்பட்ட தனிப்பட்ட தரவை மீட்காது. இணையம், Store கிடைக்கும் நிலை மற்றும் செல்லுபடியான உரிமம் தேவைப்படலாம்.|தொடர்வது Microsoft Store பதிவிறக்கங்களை அனுமதித்து Store மற்றும் தொகுப்பு ஒப்பந்தங்களை ஏற்கிறது. கொள்முதல் செய்யப்படாது.|பயன்பாடுகளை ஆய்வு செய்|தேர்ந்தவற்றை நீக்கு|நிறுவப்பட்டது|நிறுவப்படவில்லை|சரிசெய்ய வேண்டும்|நீக்கப்படுகிறது|Microsoft Store ஐத் திறக்க முடியவில்லை.
hi|Windows के अंतर्निहित ऐप|हटाने या बहाल करने के लिए Windows ऐप चुनें।|अनइंस्टॉल करने से स्थानीय ऐप डेटा मिट सकता है और सुविधाएँ बंद हो सकती हैं। पहले अपनी फ़ाइलों का बैकअप लें।|केवल यह Windows खाता बदलेगा। पुराने डेस्कटॉप ऐप, अन्य खाते और पहले से प्रावधान किए गए ऐप नहीं बदलेंगे।|बहाली ऐप फिर से इंस्टॉल करती है, मिटाया गया निजी डेटा वापस नहीं लाती। इंटरनेट, Store में उपलब्धता और मान्य लाइसेंस आवश्यक हो सकते हैं।|जारी रखने पर Microsoft Store डाउनलोड की अनुमति और Store व पैकेज समझौतों की स्वीकृति मिलती है। कोई खरीदारी नहीं होगी।|ऐप की समीक्षा करें|चुने हुए अनइंस्टॉल करें|इंस्टॉल है|इंस्टॉल नहीं है|मरम्मत आवश्यक|हटाया जा रहा है|Microsoft Store नहीं खुल सका।
ms|Aplikasi Terbina dalam Windows|Pilih aplikasi Windows untuk dinyahpasang atau dipulihkan.|Nyahpasang boleh memadam data setempat dan melumpuhkan ciri aplikasi. Sandarkan fail dahulu.|Hanya akaun Windows ini diubah. Aplikasi desktop klasik, akaun lain dan aplikasi yang diperuntukkan tidak diubah.|Pemulihan memasang semula aplikasi, bukan data peribadi yang dipadam. Internet, ketersediaan Store dan lesen sah mungkin diperlukan.|Meneruskan membenarkan muat turun Microsoft Store dan menerima perjanjian Store serta pakej. Tiada pembelian akan dibuat.|Semak aplikasi|Nyahpasang pilihan|Dipasang|Belum dipasang|Perlu dibaiki|Sedang membuang|Microsoft Store tidak dapat dibuka.
jv|Aplikasi Bawaan Windows|Pilih aplikasi Windows sing arep dibusak utawa dipulihake.|Mbusak aplikasi bisa mbusak data lokal lan mateni fiture. Gawe serep berkas dhisik.|Mung akun Windows iki sing diowahi. Aplikasi desktop klasik, akun liyane lan aplikasi kanggo pangguna anyar ora diowahi.|Pamulihaan masang maneh aplikasi, dudu mbalekake data pribadi sing wis dibusak. Bisa mbutuhake Internet, kasedhiyan Store lan lisensi sing sah.|Nerusake ngidini undhuhan Microsoft Store lan nyetujoni perjanjian Store lan paket. Ora ana tuku apa-apa.|Priksa aplikasi|Busak sing dipilih|Wis dipasang|Durung dipasang|Kudu didandani|Mbusak|Microsoft Store ora bisa dibukak.
ban|Aplikasi Bawaan Windows|Pilih aplikasi Windows sane jagi kaapus utawi kawaliang.|Ngapus aplikasi prasida ngapus data lokal miwah mateni fitur. Anggen cadangan berkas dumun.|Wantah akun Windows puniki sane kauah. Aplikasi desktop klasik, akun tiosan miwah aplikasi sane sampun kacumawisang tan kauah.|Pamulihan masang malih aplikasi, nenten ngawaliang data pribadi sane sampun kaapus. Prasida perlu Internet, kasayagian Store miwah lisensi sane sah.|Ngalantur ngicenin unduhan Microsoft Store miwah nyetujuin perjanjian Store lan paket. Nenten wenten pamesuan anggen numbas.|Priksa aplikasi|Apus sane kapilih|Sampun kapasang|Durung kapasang|Perlu kaapikin|Ngapus|Microsoft Store nenten prasida kabuka.
sv|Inbyggda Windows-appar|Välj Windows-appar att avinstallera eller återställa.|Avinstallation kan radera lokala appdata och stänga av funktioner. Säkerhetskopiera filerna först.|Endast detta Windows-konto ändras. Klassiska skrivbordsappar, andra konton och förberedda appar ändras inte.|Återställning installerar om appar, inte raderade personuppgifter. Internet, tillgänglighet i Store och en giltig licens kan krävas.|Om du fortsätter tillåter du hämtningar från Microsoft Store och accepterar Store- och paketavtalen. Inga köp görs.|Granska appar|Avinstallera valda|Installerat|Inte installerat|Behöver repareras|Tar bort|Microsoft Store kunde inte öppnas.
es|Aplicaciones integradas de Windows|Selecciona aplicaciones de Windows para desinstalar o restaurar.|La desinstalación puede borrar datos locales y desactivar funciones. Haz una copia de seguridad de tus archivos primero.|Solo se modifica esta cuenta de Windows. Las aplicaciones clásicas, otras cuentas y las aplicaciones aprovisionadas no cambian.|Restaurar reinstala aplicaciones, no datos personales eliminados. Puede requerir Internet, disponibilidad en Store y una licencia válida.|Al continuar permites descargas de Microsoft Store y aceptas los acuerdos de Store y de los paquetes. No se realizarán compras.|Revisar aplicaciones|Desinstalar selección|Instalado|No instalado|Necesita reparación|Eliminando|No se pudo abrir Microsoft Store.
""";
}
