namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string CatalogConfirmations = """
en|Apply {0} selected tweak(s)? {1} already-applied item(s) will be skipped.|Restore {0} applied item(s) to {1}|{0} already-restored item(s) will be skipped.|Windows-controlled/default behavior. This intentionally discards saved pre-tweak snapshots for these items.|their captured pre-tweak state; when no snapshot exists, a documented Windows default is used instead.
id|Terapkan {0} penyesuaian yang dipilih? {1} item yang sudah diterapkan akan dilewati.|Pulihkan {0} item yang telah diterapkan ke {1}|{0} item yang sudah dipulihkan akan dilewati.|perilaku yang dikendalikan Windows/default. Tindakan ini sengaja menghapus rekaman keadaan sebelum penyesuaian yang tersimpan untuk item ini.|keadaan sebelum penyesuaian yang direkam; jika tidak ada rekaman, nilai default Windows yang terdokumentasi digunakan sebagai gantinya.
de|{0} ausgewählte Anpassung(en) anwenden? {1} bereits angewendete Einträge werden übersprungen.|{0} angewendete Einträge zurücksetzen auf {1}|{0} bereits zurückgesetzte Einträge werden übersprungen.|das von Windows gesteuerte Verhalten bzw. Standardverhalten. Dabei werden gespeicherte Zustände vor der Anpassung für diese Einträge bewusst verworfen.|ihren erfassten Zustand vor der Anpassung; ist kein gespeicherter Zustand vorhanden, wird stattdessen ein dokumentierter Windows-Standard verwendet.
fr|Appliquer les {0} réglages sélectionnés ? Les {1} éléments déjà appliqués seront ignorés.|Rétablir les {0} éléments appliqués selon {1}|Les {0} éléments déjà restaurés seront ignorés.|le comportement géré par Windows/par défaut. Cette action supprime volontairement les instantanés enregistrés avant modification pour ces éléments.|leur état enregistré avant modification ; en l’absence d’instantané, une valeur par défaut documentée de Windows est utilisée à la place.
ar|هل تريد تطبيق {0} من التعديلات المحددة؟ سيتم تخطي {1} من العناصر المطبّقة بالفعل.|استعادة {0} من العناصر المطبّقة إلى {1}|سيتم تخطي {0} من العناصر المستعادة بالفعل.|السلوك الافتراضي أو الذي يتحكم فيه Windows. يؤدي هذا الإجراء عمدًا إلى حذف لقطات الحالة المحفوظة لهذه العناصر قبل التعديل.|حالتها المسجّلة قبل التعديل؛ وعند عدم وجود لقطة محفوظة، تُستخدم بدلًا منها قيمة افتراضية موثّقة من Windows.
tl|Ilapat ang {0} napiling pagsasaayos? Lalaktawan ang {1} aytem na nailapat na.|Ibalik ang {0} nailapat na aytem sa {1}|Lalaktawan ang {0} aytem na naibalik na.|asal na kontrolado ng Windows o paunang itinakdang asal. Sadyang binubura nito ang mga naka-save na kopya ng kalagayan bago ang pagsasaayos para sa mga aytem na ito.|kanilang naitalang kalagayan bago ang pagsasaayos; kung walang naka-save na kopya, gagamitin sa halip ang dokumentadong paunang itinakdang halaga ng Windows.
vi|Áp dụng {0} tinh chỉnh đã chọn? Sẽ bỏ qua {1} mục đã được áp dụng.|Khôi phục {0} mục đã áp dụng về {1}|Sẽ bỏ qua {0} mục đã được khôi phục.|hành vi do Windows kiểm soát/mặc định. Thao tác này chủ động xóa các bản chụp trạng thái đã lưu trước khi tinh chỉnh của những mục này.|trạng thái đã ghi lại trước khi tinh chỉnh; nếu không có bản chụp, giá trị mặc định của Windows được ghi trong tài liệu sẽ được dùng thay thế.
zh-CN|应用所选的 {0} 项调整？将跳过已应用的 {1} 个项目。|将已应用的 {0} 个项目还原为{1}|将跳过已还原的 {0} 个项目。|由 Windows 控制的行为或默认行为。此操作会有意丢弃这些项目已保存的调整前状态快照。|已记录的调整前状态；如果没有快照，则改用文档中记载的 Windows 默认值。
zh-TW|套用所選的 {0} 項調整？將略過已套用的 {1} 個項目。|將已套用的 {0} 個項目還原為{1}|將略過已還原的 {0} 個項目。|由 Windows 控制的行為或預設行為。此操作會刻意捨棄這些項目已儲存的調整前狀態快照。|已記錄的調整前狀態；若沒有快照，則改用文件記載的 Windows 預設值。
th|ใช้การปรับแต่งที่เลือก {0} รายการหรือไม่? จะข้าม {1} รายการที่ใช้แล้ว|คืนค่า {0} รายการที่ใช้แล้วเป็น{1}|จะข้าม {0} รายการที่คืนค่าแล้ว|ลักษณะการทำงานที่ Windows ควบคุมหรือค่าเริ่มต้น การดำเนินการนี้จะลบภาพบันทึกสถานะก่อนปรับแต่งที่เก็บไว้ของรายการเหล่านี้โดยเจตนา|สถานะก่อนปรับแต่งที่บันทึกไว้ หากไม่มีภาพบันทึกสถานะ จะใช้ค่าเริ่มต้นของ Windows ที่ระบุไว้ในเอกสารแทน
ru|Применить выбранные настройки ({0})? Уже применённые элементы ({1}) будут пропущены.|Восстановить применённые элементы ({0}), используя {1}|Уже восстановленные элементы ({0}) будут пропущены.|поведение под управлением Windows или по умолчанию. При этом сохранённые снимки состояния этих элементов до изменения будут намеренно удалены.|их зафиксированное состояние до изменения; если снимка нет, вместо него используется документированное значение Windows по умолчанию.
uk|Застосувати вибрані налаштування ({0})? Уже застосовані елементи ({1}) буде пропущено.|Відновити застосовані елементи ({0}), використовуючи {1}|Уже відновлені елементи ({0}) буде пропущено.|поведінку під керуванням Windows або за замовчуванням. При цьому збережені знімки стану цих елементів до зміни буде навмисно видалено.|їхній зафіксований стан до зміни; якщо знімка немає, натомість використовується задокументоване значення Windows за замовчуванням.
pt|Aplicar os {0} ajustes selecionados? Os {1} itens já aplicados serão ignorados.|Restaurar os {0} itens aplicados para {1}|Os {0} itens já restaurados serão ignorados.|o comportamento controlado pelo Windows ou padrão. Isso descarta intencionalmente os registros salvos do estado anterior ao ajuste desses itens.|o estado registrado antes do ajuste; se não houver registro, será usado um valor padrão documentado do Windows.
ja|選択した {0} 件の調整を適用しますか？適用済みの {1} 件はスキップされます。|適用済みの {0} 件を次の状態に復元します：{1}|復元済みの {0} 件はスキップされます。|Windows が制御する動作または既定の動作。この操作では、これらの項目について保存された調整前の状態のスナップショットを意図的に破棄します。|記録された調整前の状態。スナップショットがない場合は、文書化された Windows の既定値を代わりに使用します。
ko|선택한 조정 {0}개를 적용하시겠습니까? 이미 적용된 항목 {1}개는 건너뜁니다.|적용된 항목 {0}개를 다음 상태로 복원합니다: {1}|이미 복원된 항목 {0}개는 건너뜁니다.|Windows가 제어하는 동작 또는 기본 동작. 이 작업은 해당 항목의 저장된 조정 전 상태 스냅샷을 의도적으로 삭제합니다.|기록된 조정 전 상태. 스냅샷이 없으면 문서에 명시된 Windows 기본값을 대신 사용합니다.
ur|کیا منتخب کردہ {0} تبدیلیاں لاگو کریں؟ پہلے سے لاگو {1} آئٹمز چھوڑ دیے جائیں گے۔|لاگو کردہ {0} آئٹمز کو اس حالت پر بحال کریں: {1}|پہلے سے بحال شدہ {0} آئٹمز چھوڑ دیے جائیں گے۔|Windows کے زیرِ کنٹرول یا طے شدہ رویہ۔ یہ کارروائی ان آئٹمز کی تبدیلی سے پہلے کی محفوظ شدہ حالت کی نقول کو دانستہ طور پر حذف کرتی ہے۔|تبدیلی سے پہلے کی ریکارڈ شدہ حالت؛ اگر کوئی محفوظ نقل موجود نہ ہو تو اس کی جگہ Windows کی دستاویزی طے شدہ قدر استعمال کی جاتی ہے۔
ta|தேர்ந்தெடுத்த {0} மாற்றங்களைப் பயன்படுத்தவா? ஏற்கெனவே பயன்படுத்தப்பட்ட {1} உருப்படிகள் தவிர்க்கப்படும்.|பயன்படுத்தப்பட்ட {0} உருப்படிகளைப் பின்வரும் நிலைக்கு மீட்டமைக்கவும்: {1}|ஏற்கெனவே மீட்டமைக்கப்பட்ட {0} உருப்படிகள் தவிர்க்கப்படும்.|Windows கட்டுப்படுத்தும் அல்லது இயல்புநிலைச் செயல்பாடு. இச்செயல் இந்த உருப்படிகளின் மாற்றத்திற்கு முந்தைய சேமித்த நிலைப்பதிவுகளை வேண்டுமென்றே நீக்குகிறது.|மாற்றத்திற்கு முன்பு பதிவுசெய்த நிலை; நிலைப்பதிவு இல்லாவிட்டால், ஆவணப்படுத்தப்பட்ட Windows இயல்புநிலை மதிப்பு அதற்குப் பதிலாகப் பயன்படுத்தப்படும்.
hi|चुने गए {0} बदलाव लागू करें? पहले से लागू {1} आइटम छोड़ दिए जाएँगे।|लागू किए गए {0} आइटम को इस स्थिति में बहाल करें: {1}|पहले से बहाल किए गए {0} आइटम छोड़ दिए जाएँगे।|Windows द्वारा नियंत्रित या डिफ़ॉल्ट व्यवहार। यह कार्रवाई इन आइटम के बदलाव से पहले की स्थिति के सहेजे गए स्नैपशॉट जानबूझकर हटा देती है।|बदलाव से पहले की दर्ज स्थिति; स्नैपशॉट न होने पर उसकी जगह Windows का दस्तावेज़ में दिया गया डिफ़ॉल्ट मान इस्तेमाल किया जाता है।
ms|Gunakan {0} pelarasan yang dipilih? {1} item yang sudah digunakan akan dilangkau.|Pulihkan {0} item yang telah digunakan kepada {1}|{0} item yang sudah dipulihkan akan dilangkau.|tingkah laku yang dikawal Windows atau lalai. Tindakan ini sengaja membuang petikan keadaan sebelum pelarasan yang disimpan untuk item ini.|keadaan sebelum pelarasan yang direkodkan; jika tiada petikan keadaan, nilai lalai Windows yang didokumenkan digunakan sebagai ganti.
jv|Terapake {0} pangaturan sing dipilih? {1} item sing wis diterapake bakal diliwati.|Pulihake {0} item sing wis diterapake menyang {1}|{0} item sing wis dipulihake bakal diliwati.|tumindak sing dikendhaleni Windows utawa gawan. Tumindak iki kanthi sengaja mbusak rekaman kahanan sadurunge pangaturan sing disimpen kanggo item iki.|kahanan sadurunge pangaturan sing wis direkam; yen ora ana rekaman, nilai gawan Windows sing didokumentasikake digunakake minangka gantine.
ban|Terapang {0} pangaturan sane kapilih? {1} item sane sampun katerapang pacang kalintangin.|Waliang {0} item sane sampun katerapang nuju {1}|{0} item sane sampun kawaliang pacang kalintangin.|parilaksana sane kakendaliang olih Windows utawi bawaan. Tindakan puniki nganggen sengaja ngapus rekaman kaanan sadurung pangaturan sane kasimpen antuk item puniki.|kaanan sadurung pangaturan sane sampun karekam; yening nénten wenten rekaman, nilai bawaan Windows sane kadokumentasiang kaanggen pinaka pangentos.
sv|Tillämpa {0} valda justeringar? {1} redan tillämpade objekt hoppas över.|Återställ {0} tillämpade objekt till {1}|{0} redan återställda objekt hoppas över.|Windows-styrt beteende eller standardbeteende. Detta raderar avsiktligt sparade ögonblicksbilder av dessa objekts tillstånd före justeringen.|deras registrerade tillstånd före justeringen; om ingen ögonblicksbild finns används i stället ett dokumenterat standardvärde för Windows.
es|¿Aplicar los {0} ajustes seleccionados? Se omitirán los {1} elementos ya aplicados.|Restaurar los {0} elementos aplicados a {1}|Se omitirán los {0} elementos ya restaurados.|el comportamiento controlado por Windows o predeterminado. Esta acción descarta intencionadamente las instantáneas guardadas del estado anterior al ajuste de estos elementos.|su estado registrado antes del ajuste; si no existe una instantánea, se utilizará en su lugar un valor predeterminado documentado de Windows.
""";
}
