namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string RestoreResults = """
en|No original backup was found. {0}|No original backup is available, and no verified Windows default is registered for this option. No values were changed.|No original-state snapshot exists for this tweak. Apply it once through this control before using Restore.|No original BCD snapshot exists. Apply this option once before using Restore.|Applied {0}/{1}. {2}|Restored {0}/{1}. {2}|saved restore state
id|Backup asli tidak ditemukan. {0}|Backup asli tidak tersedia dan belum ada nilai bawaan Windows terverifikasi untuk opsi ini. Tidak ada nilai yang diubah.|Snapshot kondisi asli untuk tweak ini belum ada. Terapkan sekali melalui kontrol ini sebelum menggunakan Pulihkan.|Snapshot BCD asli belum ada. Terapkan opsi ini sekali sebelum menggunakan Pulihkan.|Diterapkan {0}/{1}. {2}|Dipulihkan {0}/{1}. {2}|kondisi pemulihan tersimpan
de|Es wurde keine ursprüngliche Sicherung gefunden. {0}|Es ist keine ursprüngliche Sicherung verfügbar und für diese Option ist kein überprüfter Windows-Standardwert hinterlegt. Es wurden keine Werte geändert.|Für diese Anpassung existiert keine Momentaufnahme des ursprünglichen Zustands. Wenden Sie sie einmal über dieses Steuerelement an, bevor Sie Wiederherstellen verwenden.|Es existiert keine ursprüngliche BCD-Momentaufnahme. Wenden Sie diese Option einmal an, bevor Sie Wiederherstellen verwenden.|Angewendet: {0}/{1}. {2}|Wiederhergestellt: {0}/{1}. {2}|gespeicherter Wiederherstellungszustand
fr|Aucune sauvegarde d’origine n’a été trouvée. {0}|Aucune sauvegarde d’origine n’est disponible et aucune valeur Windows par défaut vérifiée n’est enregistrée pour cette option. Aucune valeur n’a été modifiée.|Aucun instantané de l’état d’origine n’existe pour ce réglage. Appliquez-le une fois via cette commande avant d’utiliser Restaurer.|Aucun instantané BCD d’origine n’existe. Appliquez cette option une fois avant d’utiliser Restaurer.|Appliqué : {0}/{1}. {2}|Restauré : {0}/{1}. {2}|état de restauration enregistré
ar|لم يُعثر على نسخة احتياطية أصلية. {0}|لا تتوفر نسخة احتياطية أصلية، ولم تُسجل قيمة Windows افتراضية تم التحقق منها لهذا الخيار. لم تتغير أي قيم.|لا توجد لقطة للحالة الأصلية لهذا التعديل. طبّقه مرة واحدة من خلال عنصر التحكم هذا قبل استخدام الاستعادة.|لا توجد لقطة BCD أصلية. طبّق هذا الخيار مرة واحدة قبل استخدام الاستعادة.|تم تطبيق {0}/{1}. {2}|تمت استعادة {0}/{1}. {2}|حالة استعادة محفوظة
tl|Walang natagpuang orihinal na backup. {0}|Walang available na orihinal na backup at walang nakatalang beripikadong default ng Windows para sa opsyong ito. Walang binagong halaga.|Walang snapshot ng orihinal na estado para sa pagbabagong ito. Ilapat ito nang isang beses gamit ang kontrol na ito bago gamitin ang Ibalik.|Walang orihinal na BCD snapshot. Ilapat ang opsyong ito nang isang beses bago gamitin ang Ibalik.|Nailapat ang {0}/{1}. {2}|Naibalik ang {0}/{1}. {2}|naka-save na estado para sa pagbabalik
vi|Không tìm thấy bản sao lưu gốc. {0}|Không có bản sao lưu gốc và chưa có giá trị mặc định Windows đã xác minh cho tùy chọn này. Không có giá trị nào bị thay đổi.|Chưa có bản chụp trạng thái gốc cho tinh chỉnh này. Hãy áp dụng một lần qua điều khiển này trước khi dùng Khôi phục.|Chưa có bản chụp BCD gốc. Hãy áp dụng tùy chọn này một lần trước khi dùng Khôi phục.|Đã áp dụng {0}/{1}. {2}|Đã khôi phục {0}/{1}. {2}|trạng thái khôi phục đã lưu
zh-CN|未找到原始备份。{0}|没有可用的原始备份，也没有为此选项记录经过验证的 Windows 默认值。未更改任何值。|此调整没有原始状态快照。请先通过此控件应用一次，再使用还原。|没有原始 BCD 快照。请先应用此选项一次，再使用还原。|已应用 {0}/{1}。{2}|已还原 {0}/{1}。{2}|已保存的还原状态
zh-TW|找不到原始備份。{0}|沒有可用的原始備份，也沒有為此選項記錄經過驗證的 Windows 預設值。未變更任何值。|此調整沒有原始狀態快照。請先透過此控制項套用一次，再使用還原。|沒有原始 BCD 快照。請先套用此選項一次，再使用還原。|已套用 {0}/{1}。{2}|已還原 {0}/{1}。{2}|已儲存的還原狀態
th|ไม่พบข้อมูลสำรองต้นฉบับ {0}|ไม่มีข้อมูลสำรองต้นฉบับ และไม่มีค่าเริ่มต้นของ Windows ที่ผ่านการตรวจสอบบันทึกไว้สำหรับตัวเลือกนี้ ไม่มีการเปลี่ยนแปลงค่าใด|ไม่มีสแนปช็อตสถานะเดิมสำหรับการปรับแต่งนี้ ใช้การปรับแต่งผ่านตัวควบคุมนี้หนึ่งครั้งก่อนใช้การคืนค่า|ไม่มีสแนปช็อต BCD เดิม ใช้ตัวเลือกนี้หนึ่งครั้งก่อนใช้การคืนค่า|นำไปใช้แล้ว {0}/{1} {2}|คืนค่าแล้ว {0}/{1} {2}|สถานะการคืนค่าที่บันทึกไว้
ru|Исходная резервная копия не найдена. {0}|Исходная резервная копия недоступна, и для этого параметра не зарегистрировано проверенное значение Windows по умолчанию. Значения не изменены.|Для этой настройки нет снимка исходного состояния. Примените её один раз с помощью этого элемента управления перед восстановлением.|Исходный снимок BCD отсутствует. Примените этот параметр один раз перед восстановлением.|Применено: {0}/{1}. {2}|Восстановлено: {0}/{1}. {2}|сохранённое состояние восстановления
uk|Початкову резервну копію не знайдено. {0}|Початкова резервна копія недоступна, і для цього параметра не зареєстровано перевірене типове значення Windows. Значення не змінено.|Для цього налаштування немає знімка початкового стану. Застосуйте його один раз через цей елемент керування перед відновленням.|Початкового знімка BCD немає. Застосуйте цей параметр один раз перед відновленням.|Застосовано: {0}/{1}. {2}|Відновлено: {0}/{1}. {2}|збережений стан відновлення
pt|Não foi encontrada uma cópia de segurança original. {0}|Não existe uma cópia de segurança original nem um valor predefinido do Windows verificado para esta opção. Nenhum valor foi alterado.|Não existe um instantâneo do estado original deste ajuste. Aplique-o uma vez através deste controlo antes de usar Restaurar.|Não existe um instantâneo BCD original. Aplique esta opção uma vez antes de usar Restaurar.|Aplicado: {0}/{1}. {2}|Restaurado: {0}/{1}. {2}|estado de restauro guardado
ja|元のバックアップが見つかりませんでした。{0}|元のバックアップがなく、このオプションには検証済みの Windows 既定値も登録されていません。値は変更されていません。|この調整には元の状態のスナップショットがありません。還元操作を行う前に、このコントロールから一度適用してください。|元の BCD スナップショットがありません。復元を使用する前に、このオプションを一度適用してください。|適用済み：{0}/{1}。{2}|復元済み：{0}/{1}。{2}|保存された復元状態
ko|원본 백업을 찾지 못했습니다. {0}|원본 백업이 없고 이 옵션에 대해 검증된 Windows 기본값도 등록되어 있지 않습니다. 변경된 값은 없습니다.|이 조정의 원래 상태 스냅샷이 없습니다. 복원을 사용하기 전에 이 컨트롤을 통해 한 번 적용하세요.|원본 BCD 스냅샷이 없습니다. 복원을 사용하기 전에 이 옵션을 한 번 적용하세요.|적용됨: {0}/{1}. {2}|복원됨: {0}/{1}. {2}|저장된 복원 상태
ur|اصل بیک اپ نہیں ملا۔ {0}|اصل بیک اپ دستیاب نہیں اور اس اختیار کے لیے Windows کی کوئی تصدیق شدہ طے شدہ قدر درج نہیں۔ کوئی قدر تبدیل نہیں کی گئی۔|اس ترمیم کی اصل حالت کا اسنیپ شاٹ موجود نہیں۔ بحال کرنے سے پہلے اس کنٹرول کے ذریعے اسے ایک بار لاگو کریں۔|اصل BCD اسنیپ شاٹ موجود نہیں۔ بحال کرنے سے پہلے اس اختیار کو ایک بار لاگو کریں۔|لاگو کیا گیا: {0}/{1}۔ {2}|بحال کیا گیا: {0}/{1}۔ {2}|محفوظ کردہ بحالی کی حالت
ta|அசல் காப்புப்பிரதி கிடைக்கவில்லை. {0}|அசல் காப்புப்பிரதி இல்லை; இந்த விருப்பத்திற்குச் சரிபார்க்கப்பட்ட Windows இயல்புநிலை மதிப்பும் பதிவு செய்யப்படவில்லை. எந்த மதிப்பும் மாற்றப்படவில்லை.|இந்த மாற்றத்திற்கான அசல் நிலையின் நகல் இல்லை. மீட்டமைப்பைப் பயன்படுத்தும் முன் இந்தக் கட்டுப்பாட்டின் மூலம் ஒருமுறை பயன்படுத்தவும்.|அசல் BCD நிலையின் நகல் இல்லை. மீட்டமைப்பைப் பயன்படுத்தும் முன் இந்த விருப்பத்தை ஒருமுறை பயன்படுத்தவும்.|பயன்படுத்தப்பட்டது: {0}/{1}. {2}|மீட்டமைக்கப்பட்டது: {0}/{1}. {2}|சேமித்த மீட்டமைப்பு நிலை
hi|मूल बैकअप नहीं मिला। {0}|मूल बैकअप उपलब्ध नहीं है और इस विकल्प के लिए कोई सत्यापित Windows डिफ़ॉल्ट मान दर्ज नहीं है। कोई मान नहीं बदला गया।|इस बदलाव की मूल स्थिति का स्नैपशॉट नहीं है। पुनर्स्थापित करने से पहले इस नियंत्रण से इसे एक बार लागू करें।|मूल BCD स्नैपशॉट नहीं है। पुनर्स्थापित करने से पहले इस विकल्प को एक बार लागू करें।|लागू किए गए: {0}/{1}। {2}|पुनर्स्थापित किए गए: {0}/{1}। {2}|सहेजी गई पुनर्स्थापना स्थिति
ms|Sandaran asal tidak ditemui. {0}|Sandaran asal tidak tersedia dan tiada nilai lalai Windows yang disahkan didaftarkan untuk pilihan ini. Tiada nilai diubah.|Tiada petikan keadaan asal untuk pelarasan ini. Gunakannya sekali melalui kawalan ini sebelum menggunakan Pulihkan.|Tiada petikan BCD asal. Gunakan pilihan ini sekali sebelum menggunakan Pulihkan.|Digunakan: {0}/{1}. {2}|Dipulihkan: {0}/{1}. {2}|keadaan pemulihan tersimpan
jv|Serep asli ora ditemokake. {0}|Serep asli ora kasedhiya lan durung ana nilai gawan Windows sing wis diverifikasi kanggo pilihan iki. Ora ana nilai sing diganti.|Durung ana salinan kahanan asli kanggo pangaturan iki. Terapna sepisan liwat kontrol iki sadurunge nggunakake Pulihake.|Durung ana salinan BCD asli. Terapna pilihan iki sepisan sadurunge nggunakake Pulihake.|Diterapake {0}/{1}. {2}|Dipulihake {0}/{1}. {2}|kahanan pamulihan sing disimpen
ban|Cadangan asli nénten kapanggihin. {0}|Cadangan asli nénten kasayagayang lan durung wenten nilai bawaan Windows sane sampun kapariksa kanggo pilihan puniki. Nénten wenten nilai sane kaubah.|Durung wenten salinan kawéntenan asli kanggo pangaturan puniki. Terapang sapisan antuk kontrol puniki sadurung nganggén Pulihang.|Durung wenten salinan BCD asli. Terapang pilihan puniki sapisan sadurung nganggén Pulihang.|Katerapang {0}/{1}. {2}|Kapulihang {0}/{1}. {2}|kawéntenan pamulihan sane kasimpen
sv|Ingen ursprunglig säkerhetskopia hittades. {0}|Ingen ursprunglig säkerhetskopia är tillgänglig och inget verifierat Windows-standardvärde finns registrerat för detta alternativ. Inga värden ändrades.|Det finns ingen ögonblicksbild av ursprungstillståndet för denna justering. Tillämpa den en gång via denna kontroll innan du använder Återställ.|Det finns ingen ursprunglig BCD-ögonblicksbild. Tillämpa detta alternativ en gång innan du använder Återställ.|Tillämpat: {0}/{1}. {2}|Återställt: {0}/{1}. {2}|sparat återställningstillstånd
es|No se encontró una copia de seguridad original. {0}|No hay una copia de seguridad original disponible ni un valor predeterminado de Windows verificado para esta opción. No se cambió ningún valor.|No existe una instantánea del estado original de este ajuste. Aplíquelo una vez mediante este control antes de usar Restaurar.|No existe una instantánea BCD original. Aplique esta opción una vez antes de usar Restaurar.|Aplicado: {0}/{1}. {2}|Restaurado: {0}/{1}. {2}|estado de restauración guardado
""";
}
