namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string Status = """
en|{0}% complete — {1}|Analyzed {0}/{1}|Optimized {0}|Selected {0}|Pending changes {0}|Waiting for: {0}|Pending|Legacy Windows Panels|Process Manager|CPU LIVE|RAM LIVE|GPU 3D LIVE|NETWORK RX / TX|Install / Update WinGet + App Installer|Install WMIC via DISM|Verify Windows Servicing / WMI / AppX|Administrator / environment preflight|Verify System Restore|Verify WinGet|Verify WMIC|Save first-run setup state|Log copied to Clipboard.|Operation is starting...|Administrator rights and an Internet connection are required.
id|{0}% selesai — {1}|Dianalisis {0}/{1}|Dioptimalkan {0}|Dipilih {0}|Perubahan tertunda {0}|Menunggu: {0}|Tertunda|Panel Windows Lawas|Pengelola Proses|CPU LANGSUNG|RAM LANGSUNG|GPU 3D LANGSUNG|JARINGAN TERIMA / KIRIM|Instal / Perbarui WinGet + App Installer|Instal WMIC melalui DISM|Verifikasi Windows Servicing / WMI / AppX|Pemeriksaan awal Administrator / lingkungan|Verifikasi Pemulihan Sistem|Verifikasi WinGet|Verifikasi WMIC|Simpan status persiapan awal|Log disalin ke Clipboard.|Operasi sedang dimulai...|Diperlukan hak Administrator dan koneksi Internet.
de|{0}% abgeschlossen — {1}|Analysiert {0}/{1}|Optimiert {0}|Ausgewählt {0}|Ausstehende Änderungen {0}|Warten auf: {0}|Ausstehend|Klassische Windows-Systemsteuerungen|Prozessverwaltung|CPU LIVE|RAM LIVE|GPU 3D LIVE|NETZWERK EMPFANG / SENDEN|WinGet + App Installer installieren / aktualisieren|WMIC über DISM installieren|Windows-Wartung / WMI / AppX überprüfen|Administrator- / Umgebungsprüfung|Systemwiederherstellung überprüfen|WinGet überprüfen|WMIC überprüfen|Status der Ersteinrichtung speichern|Protokoll in die Zwischenablage kopiert.|Vorgang wird gestartet...|Administratorrechte und eine Internetverbindung sind erforderlich.
fr|{0}% terminé — {1}|Analysés {0}/{1}|Optimisés {0}|Sélectionnés {0}|Modifications en attente {0}|En attente de : {0}|En attente|Panneaux Windows classiques|Gestionnaire de processus|CPU EN DIRECT|RAM EN DIRECT|GPU 3D EN DIRECT|RÉSEAU RÉCEPTION / ENVOI|Installer / Mettre à jour WinGet + App Installer|Installer WMIC via DISM|Vérifier la maintenance Windows / WMI / AppX|Vérification préalable des droits administrateur / de l'environnement|Vérifier la restauration du système|Vérifier WinGet|Vérifier WMIC|Enregistrer l'état de la configuration initiale|Journal copié dans le Presse-papiers.|Démarrage de l'opération...|Des droits administrateur et une connexion Internet sont nécessaires.
ar|اكتمل {0}% — {1}|تم تحليل {0}/{1}|تم تحسين {0}|تم تحديد {0}|التغييرات المعلقة {0}|بانتظار: {0}|معلق|لوحات Windows التقليدية|مدير العمليات|CPU مباشر|RAM مباشر|GPU 3D مباشر|الشبكة استقبال / إرسال|تثبيت / تحديث WinGet + App Installer|تثبيت WMIC عبر DISM|التحقق من صيانة Windows / WMI / AppX|فحص أولي لصلاحيات المسؤول / البيئة|التحقق من استعادة النظام|التحقق من WinGet|التحقق من WMIC|حفظ حالة الإعداد الأولي|تم نسخ السجل إلى الحافظة.|جارٍ بدء العملية...|يلزم توفر صلاحيات المسؤول واتصال بالإنترنت.
tl|{0}% tapos — {1}|Nasuri {0}/{1}|Na-optimize {0}|Napili {0}|Nakabinbing pagbabago {0}|Naghihintay sa: {0}|Nakabinbin|Mga Lumang Panel ng Windows|Tagapamahala ng Proseso|CPU LIVE|RAM LIVE|GPU 3D LIVE|NETWORK TANGGAP / PADALA|I-install / I-update ang WinGet + App Installer|I-install ang WMIC gamit ang DISM|Beripikahin ang Windows Servicing / WMI / AppX|Paunang pagsusuri ng Administrator / environment|Beripikahin ang System Restore|Beripikahin ang WinGet|Beripikahin ang WMIC|I-save ang kalagayan ng paunang setup|Nakopya ang log sa Clipboard.|Nagsisimula ang operasyon...|Kailangan ang mga karapatan ng Administrator at koneksyon sa Internet.
vi|Hoàn tất {0}% — {1}|Đã phân tích {0}/{1}|Đã tối ưu {0}|Đã chọn {0}|Thay đổi đang chờ {0}|Đang chờ: {0}|Đang chờ|Bảng điều khiển Windows cũ|Trình quản lý tiến trình|CPU TRỰC TIẾP|RAM TRỰC TIẾP|GPU 3D TRỰC TIẾP|MẠNG NHẬN / GỬI|Cài đặt / Cập nhật WinGet + App Installer|Cài đặt WMIC qua DISM|Xác minh Windows Servicing / WMI / AppX|Kiểm tra trước quyền quản trị / môi trường|Xác minh Khôi phục Hệ thống|Xác minh WinGet|Xác minh WMIC|Lưu trạng thái thiết lập ban đầu|Đã sao chép nhật ký vào Clipboard.|Đang bắt đầu thao tác...|Cần quyền quản trị viên và kết nối Internet.
zh-CN|已完成 {0}% — {1}|已分析 {0}/{1}|已优化 {0}|已选择 {0}|待处理更改 {0}|正在等待：{0}|待处理|传统 Windows 控制面板|进程管理器|CPU 实时|RAM 实时|GPU 3D 实时|网络接收 / 发送|安装 / 更新 WinGet + App Installer|通过 DISM 安装 WMIC|验证 Windows 维护 / WMI / AppX|管理员权限 / 环境预检|验证系统还原|验证 WinGet|验证 WMIC|保存初始设置状态|日志已复制到剪贴板。|正在开始操作...|需要管理员权限和 Internet 连接。
zh-TW|已完成 {0}% — {1}|已分析 {0}/{1}|已最佳化 {0}|已選取 {0}|待處理變更 {0}|正在等待：{0}|待處理|傳統 Windows 控制台|處理程序管理員|CPU 即時|RAM 即時|GPU 3D 即時|網路接收 / 傳送|安裝 / 更新 WinGet + App Installer|透過 DISM 安裝 WMIC|驗證 Windows 維護 / WMI / AppX|系統管理員權限 / 環境預先檢查|驗證系統還原|驗證 WinGet|驗證 WMIC|儲存初始設定狀態|已將記錄複製到剪貼簿。|正在開始作業...|需要系統管理員權限及網際網路連線。
th|เสร็จแล้ว {0}% — {1}|วิเคราะห์แล้ว {0}/{1}|ปรับให้เหมาะสมแล้ว {0}|เลือกแล้ว {0}|การเปลี่ยนแปลงที่รออยู่ {0}|กำลังรอ: {0}|รอดำเนินการ|แผง Windows แบบเดิม|ตัวจัดการกระบวนการ|CPU แบบสด|RAM แบบสด|GPU 3D แบบสด|เครือข่ายรับ / ส่ง|ติดตั้ง / อัปเดต WinGet + App Installer|ติดตั้ง WMIC ผ่าน DISM|ตรวจสอบ Windows Servicing / WMI / AppX|ตรวจสอบสิทธิ์ผู้ดูแลระบบ / สภาพแวดล้อมก่อนเริ่ม|ตรวจสอบการคืนค่าระบบ|ตรวจสอบ WinGet|ตรวจสอบ WMIC|บันทึกสถานะการตั้งค่าครั้งแรก|คัดลอกบันทึกไปยังคลิปบอร์ดแล้ว|กำลังเริ่มการทำงาน...|ต้องมีสิทธิ์ผู้ดูแลระบบและการเชื่อมต่ออินเทอร์เน็ต
ru|Выполнено {0}% — {1}|Проанализировано {0}/{1}|Оптимизировано {0}|Выбрано {0}|Ожидающие изменения {0}|Ожидание: {0}|Ожидает|Классические панели Windows|Диспетчер процессов|ЦП В РЕАЛЬНОМ ВРЕМЕНИ|ОЗУ В РЕАЛЬНОМ ВРЕМЕНИ|GPU 3D В РЕАЛЬНОМ ВРЕМЕНИ|СЕТЬ ПРИЁМ / ПЕРЕДАЧА|Установить / Обновить WinGet + App Installer|Установить WMIC через DISM|Проверить обслуживание Windows / WMI / AppX|Предварительная проверка прав администратора / среды|Проверить восстановление системы|Проверить WinGet|Проверить WMIC|Сохранить состояние первоначальной настройки|Журнал скопирован в буфер обмена.|Операция запускается...|Необходимы права администратора и подключение к Интернету.
uk|Виконано {0}% — {1}|Проаналізовано {0}/{1}|Оптимізовано {0}|Вибрано {0}|Зміни в очікуванні {0}|Очікування: {0}|Очікує|Класичні панелі Windows|Диспетчер процесів|ЦП НАЖИВО|ОЗП НАЖИВО|GPU 3D НАЖИВО|МЕРЕЖА ОТРИМАННЯ / НАДСИЛАННЯ|Установити / Оновити WinGet + App Installer|Установити WMIC через DISM|Перевірити обслуговування Windows / WMI / AppX|Попередня перевірка прав адміністратора / середовища|Перевірити відновлення системи|Перевірити WinGet|Перевірити WMIC|Зберегти стан початкового налаштування|Журнал скопійовано до буфера обміну.|Операція починається...|Потрібні права адміністратора та підключення до Інтернету.
pt|{0}% concluído — {1}|Analisados {0}/{1}|Otimizados {0}|Selecionados {0}|Alterações pendentes {0}|A aguardar: {0}|Pendente|Painéis clássicos do Windows|Gestor de processos|CPU EM DIRETO|RAM EM DIRETO|GPU 3D EM DIRETO|REDE RECEÇÃO / ENVIO|Instalar / Atualizar WinGet + App Installer|Instalar WMIC via DISM|Verificar manutenção do Windows / WMI / AppX|Verificação prévia de administrador / ambiente|Verificar o Restauro do Sistema|Verificar WinGet|Verificar WMIC|Guardar o estado da configuração inicial|Registo copiado para a Área de Transferência.|A iniciar a operação...|São necessários direitos de administrador e uma ligação à Internet.
ja|{0}% 完了 — {1}|分析済み {0}/{1}|最適化済み {0}|選択済み {0}|保留中の変更 {0}|待機中：{0}|保留中|従来の Windows コントロールパネル|プロセス マネージャー|CPU リアルタイム|RAM リアルタイム|GPU 3D リアルタイム|ネットワーク受信 / 送信|WinGet + App Installer のインストール / 更新|DISM による WMIC のインストール|Windows サービス機構 / WMI / AppX の検証|管理者権限 / 環境の事前確認|システムの復元の検証|WinGet の検証|WMIC の検証|初期設定の状態を保存|ログをクリップボードにコピーしました。|操作を開始しています...|管理者権限とインターネット接続が必要です。
ko|{0}% 완료 — {1}|분석됨 {0}/{1}|최적화됨 {0}|선택됨 {0}|보류 중인 변경 {0}|대기 중: {0}|보류 중|기존 Windows 제어판|프로세스 관리자|CPU 실시간|RAM 실시간|GPU 3D 실시간|네트워크 수신 / 송신|WinGet + App Installer 설치 / 업데이트|DISM을 통해 WMIC 설치|Windows 서비스 기능 / WMI / AppX 검증|관리자 권한 / 환경 사전 점검|시스템 복원 검증|WinGet 검증|WMIC 검증|초기 설정 상태 저장|로그를 클립보드에 복사했습니다.|작업을 시작하는 중...|관리자 권한과 인터넷 연결이 필요합니다.
ur|{0}% مکمل — {1}|تجزیہ شدہ {0}/{1}|بہتر کیے گئے {0}|منتخب {0}|زیر التوا تبدیلیاں {0}|انتظار ہے: {0}|زیر التوا|Windows کے پرانے پینل|عمل کا منتظم|CPU براہ راست|RAM براہ راست|GPU 3D براہ راست|نیٹ ورک وصول / ارسال|WinGet + App Installer نصب / اپ ڈیٹ کریں|DISM کے ذریعے WMIC نصب کریں|Windows Servicing / WMI / AppX کی تصدیق کریں|منتظم / ماحول کی ابتدائی جانچ|System Restore کی تصدیق کریں|WinGet کی تصدیق کریں|WMIC کی تصدیق کریں|ابتدائی ترتیب کی حالت محفوظ کریں|لاگ کلپ بورڈ پر نقل کر دیا گیا۔|عمل شروع ہو رہا ہے...|منتظم کے حقوق اور انٹرنیٹ کنکشن درکار ہیں۔
ta|{0}% முடிந்தது — {1}|ஆய்வு செய்தவை {0}/{1}|மேம்படுத்தியவை {0}|தேர்ந்தெடுத்தவை {0}|நிலுவை மாற்றங்கள் {0}|இதற்காகக் காத்திருக்கிறது: {0}|நிலுவையில்|பழைய Windows கட்டுப்பாட்டுப் பலகங்கள்|செயல்முறை மேலாளர்|CPU நேரலை|RAM நேரலை|GPU 3D நேரலை|வலைப்பின்னல் பெறுதல் / அனுப்புதல்|WinGet + App Installer நிறுவு / புதுப்பி|DISM மூலம் WMIC நிறுவு|Windows Servicing / WMI / AppX சரிபார்|நிர்வாகி உரிமைகள் / சூழல் முன்சோதனை|கணினி மீட்டமைப்பைச் சரிபார்|WinGet சரிபார்|WMIC சரிபார்|முதல் அமைப்பின் நிலையைச் சேமி|பதிவு கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது.|செயல்பாடு தொடங்குகிறது...|நிர்வாகி உரிமைகளும் இணைய இணைப்பும் தேவை.
hi|{0}% पूरा — {1}|विश्लेषित {0}/{1}|अनुकूलित {0}|चयनित {0}|लंबित बदलाव {0}|प्रतीक्षा है: {0}|लंबित|पुराने Windows नियंत्रण पैनल|प्रक्रिया प्रबंधक|CPU लाइव|RAM लाइव|GPU 3D लाइव|नेटवर्क प्राप्त / भेजा|WinGet + App Installer इंस्टॉल / अपडेट करें|DISM से WMIC इंस्टॉल करें|Windows Servicing / WMI / AppX सत्यापित करें|व्यवस्थापक अधिकार / परिवेश की प्रारंभिक जाँच|सिस्टम रिस्टोर सत्यापित करें|WinGet सत्यापित करें|WMIC सत्यापित करें|प्रारंभिक सेटअप की स्थिति सहेजें|लॉग क्लिपबोर्ड पर कॉपी किया गया।|कार्रवाई शुरू हो रही है...|व्यवस्थापक अधिकार और इंटरनेट कनेक्शन आवश्यक हैं।
ms|{0}% selesai — {1}|Dianalisis {0}/{1}|Dioptimumkan {0}|Dipilih {0}|Perubahan tertunda {0}|Menunggu: {0}|Tertunda|Panel Windows Legasi|Pengurus Proses|CPU LANGSUNG|RAM LANGSUNG|GPU 3D LANGSUNG|RANGKAIAN TERIMA / HANTAR|Pasang / Kemas kini WinGet + App Installer|Pasang WMIC melalui DISM|Sahkan Windows Servicing / WMI / AppX|Semakan awal pentadbir / persekitaran|Sahkan Pemulihan Sistem|Sahkan WinGet|Sahkan WMIC|Simpan status persediaan awal|Log disalin ke Papan Klip.|Operasi sedang bermula...|Hak pentadbir dan sambungan Internet diperlukan.
jv|{0}% rampung — {1}|Dianalisis {0}/{1}|Dioptimalake {0}|Dipilih {0}|Owah-owahan ditundha {0}|Ngenteni: {0}|Ditundha|Panel Windows Lawas|Pangatur Proses|CPU LANGSUNG|RAM LANGSUNG|GPU 3D LANGSUNG|JARINGAN NAMPA / NGIRIM|Instal / Nganyari WinGet + App Installer|Instal WMIC nganggo DISM|Priksa Windows Servicing / WMI / AppX|Pamriksan wiwitan Administrator / lingkungan|Priksa Pamulihan Sistem|Priksa WinGet|Priksa WMIC|Simpen status persiyapan wiwitan|Log wis disalin menyang Clipboard.|Operasi lagi diwiwiti...|Mbutuhake hak Administrator lan sambungan Internet.
ban|{0}% puput — {1}|Sampun kaanalisis {0}/{1}|Sampun kaoptimalang {0}|Kapilih {0}|Owah-owahan katunda {0}|Ngantos: {0}|Katunda|Panel Windows Lawas|Pangatur Proses|CPU LANGSUNG|RAM LANGSUNG|GPU 3D LANGSUNG|JARINGAN NAMPÉN / NGIRIM|Instal / Anyarin WinGet + App Installer|Instal WMIC nganggen DISM|Priksa Windows Servicing / WMI / AppX|Pamariksaan kawitan Administrator / lingkungan|Priksa Pamulihan Sistem|Priksa WinGet|Priksa WMIC|Simpen status persiapan kawitan|Log sampun kasalin ka Clipboard.|Operasi sedeng kawitin...|Mabuat hak Administrator miwah sambungan Internet.
sv|{0}% klart — {1}|Analyserade {0}/{1}|Optimerade {0}|Valda {0}|Väntande ändringar {0}|Väntar på: {0}|Väntande|Klassiska Windows-paneler|Processhanterare|CPU LIVE|RAM LIVE|GPU 3D LIVE|NÄTVERK MOTTAGNING / SÄNDNING|Installera / Uppdatera WinGet + App Installer|Installera WMIC via DISM|Verifiera Windows-underhåll / WMI / AppX|Förkontroll av administratörsbehörighet / miljö|Verifiera Systemåterställning|Verifiera WinGet|Verifiera WMIC|Spara status för första konfigurationen|Loggen kopierades till Urklipp.|Åtgärden startar...|Administratörsbehörighet och internetanslutning krävs.
es|{0}% completado — {1}|Analizados {0}/{1}|Optimizados {0}|Seleccionados {0}|Cambios pendientes {0}|Esperando a: {0}|Pendiente|Paneles clásicos de Windows|Administrador de procesos|CPU EN DIRECTO|RAM EN DIRECTO|GPU 3D EN DIRECTO|RED RECEPCIÓN / ENVÍO|Instalar / Actualizar WinGet + App Installer|Instalar WMIC mediante DISM|Verificar mantenimiento de Windows / WMI / AppX|Comprobación previa de administrador / entorno|Verificar Restaurar sistema|Verificar WinGet|Verificar WMIC|Guardar el estado de la configuración inicial|Registro copiado al Portapapeles.|La operación está comenzando...|Se requieren permisos de administrador y conexión a Internet.
""";
}
