namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string WmiWizard = """
en|WinGet setup requires Internet access. WMI verification works offline.|Verify WMI system and memory access|Reads operating-system and RAM data directly through WMI on Windows 10 and 11. WMIC is not required and will not be installed or removed.|Verify WMI system access|Verify WMI memory access
id|Penyiapan WinGet memerlukan akses Internet. Verifikasi WMI dapat dilakukan secara offline.|Verifikasi akses sistem dan memori melalui WMI|Membaca data sistem operasi dan RAM langsung melalui WMI pada Windows 10 dan 11. WMIC tidak diperlukan dan tidak akan diinstal atau dihapus.|Verifikasi akses sistem melalui WMI|Verifikasi akses memori melalui WMI
de|Die WinGet-Einrichtung benötigt Internetzugang. Die WMI-Prüfung funktioniert offline.|WMI-Zugriff auf System und Arbeitsspeicher prüfen|Liest Betriebssystem- und RAM-Daten unter Windows 10 und 11 direkt über WMI. WMIC ist nicht erforderlich und wird weder installiert noch entfernt.|WMI-Systemzugriff prüfen|WMI-Arbeitsspeicherzugriff prüfen
fr|La configuration de WinGet nécessite Internet. La vérification WMI fonctionne hors ligne.|Vérifier l’accès WMI au système et à la mémoire|Lit les données du système et de la RAM directement via WMI sous Windows 10 et 11. WMIC n’est pas nécessaire et ne sera ni installé ni supprimé.|Vérifier l’accès WMI au système|Vérifier l’accès WMI à la mémoire
ar|يتطلب إعداد WinGet اتصالاً بالإنترنت. يعمل التحقق من WMI دون اتصال.|التحقق من وصول WMI إلى النظام والذاكرة|يقرأ بيانات نظام التشغيل وذاكرة RAM مباشرة عبر WMI على Windows 10 و11. لا يلزم WMIC ولن يتم تثبيته أو إزالته.|التحقق من وصول WMI إلى النظام|التحقق من وصول WMI إلى الذاكرة
tl|Kailangan ng Internet para sa pag-setup ng WinGet. Gumagana offline ang pagberipika ng WMI.|Beripikahin ang access ng WMI sa system at memory|Direktang binabasa ang datos ng operating system at RAM gamit ang WMI sa Windows 10 at 11. Hindi kailangan ang WMIC at hindi ito i-install o aalisin.|Beripikahin ang access ng WMI sa system|Beripikahin ang access ng WMI sa memory
vi|Thiết lập WinGet cần Internet. Xác minh WMI hoạt động ngoại tuyến.|Xác minh quyền truy cập hệ thống và bộ nhớ qua WMI|Đọc dữ liệu hệ điều hành và RAM trực tiếp qua WMI trên Windows 10 và 11. Không cần WMIC và sẽ không cài đặt hay gỡ bỏ WMIC.|Xác minh truy cập hệ thống qua WMI|Xác minh truy cập bộ nhớ qua WMI
zh-CN|设置 WinGet 需要 Internet 连接。WMI 验证可离线进行。|验证 WMI 系统和内存访问|在 Windows 10 和 11 上直接通过 WMI 读取操作系统和 RAM 数据。无需 WMIC，也不会安装或删除 WMIC。|验证 WMI 系统访问|验证 WMI 内存访问
zh-TW|設定 WinGet 需要網際網路連線。WMI 驗證可離線進行。|驗證 WMI 系統和記憶體存取|在 Windows 10 和 11 上直接透過 WMI 讀取作業系統和 RAM 資料。無需 WMIC，也不會安裝或移除 WMIC。|驗證 WMI 系統存取|驗證 WMI 記憶體存取
th|การตั้งค่า WinGet ต้องใช้อินเทอร์เน็ต การตรวจสอบ WMI ทำงานแบบออฟไลน์ได้|ตรวจสอบการเข้าถึงระบบและหน่วยความจำผ่าน WMI|อ่านข้อมูลระบบปฏิบัติการและ RAM โดยตรงผ่าน WMI บน Windows 10 และ 11 ไม่จำเป็นต้องใช้ WMIC และจะไม่มีการติดตั้งหรือลบ WMIC|ตรวจสอบการเข้าถึงระบบผ่าน WMI|ตรวจสอบการเข้าถึงหน่วยความจำผ่าน WMI
ru|Для настройки WinGet нужен Интернет. Проверка WMI работает без сети.|Проверить доступ WMI к системе и памяти|Читает данные ОС и оперативной памяти напрямую через WMI в Windows 10 и 11. WMIC не требуется и не будет установлен или удалён.|Проверить доступ WMI к системе|Проверить доступ WMI к памяти
uk|Для налаштування WinGet потрібен Інтернет. Перевірка WMI працює без мережі.|Перевірити доступ WMI до системи та пам’яті|Читає дані ОС та оперативної пам’яті безпосередньо через WMI у Windows 10 і 11. WMIC не потрібен і не буде встановлений або видалений.|Перевірити доступ WMI до системи|Перевірити доступ WMI до пам’яті
pt|A configuração do WinGet requer Internet. A verificação WMI funciona offline.|Verificar o acesso WMI ao sistema e à memória|Lê dados do sistema operativo e da RAM diretamente através de WMI no Windows 10 e 11. O WMIC não é necessário e não será instalado nem removido.|Verificar o acesso WMI ao sistema|Verificar o acesso WMI à memória
ja|WinGet のセットアップにはインターネット接続が必要です。WMI の検証はオフラインで行えます。|WMI によるシステムとメモリへのアクセスを検証|Windows 10 と 11 で WMI を通じて OS と RAM のデータを直接読み取ります。WMIC は不要で、インストールも削除も行いません。|WMI によるシステムアクセスを検証|WMI によるメモリアクセスを検証
ko|WinGet 설정에는 인터넷 연결이 필요합니다. WMI 검증은 오프라인으로 가능합니다.|WMI 시스템 및 메모리 접근 검증|Windows 10과 11에서 WMI를 통해 운영 체제와 RAM 데이터를 직접 읽습니다. WMIC는 필요하지 않으며 설치하거나 제거하지 않습니다.|WMI 시스템 접근 검증|WMI 메모리 접근 검증
ur|WinGet کی ترتیب کے لیے انٹرنیٹ درکار ہے۔ WMI کی تصدیق آف لائن ہو سکتی ہے۔|WMI کے ذریعے سسٹم اور میموری تک رسائی کی تصدیق کریں|Windows 10 اور 11 پر WMI کے ذریعے آپریٹنگ سسٹم اور RAM کا ڈیٹا براہ راست پڑھتا ہے۔ WMIC درکار نہیں اور اسے نصب یا حذف نہیں کیا جائے گا۔|WMI کے ذریعے سسٹم تک رسائی کی تصدیق کریں|WMI کے ذریعے میموری تک رسائی کی تصدیق کریں
ta|WinGet அமைப்புக்கு இணையம் தேவை. WMI சரிபார்ப்பு இணையமின்றி செயல்படும்.|WMI வழியாக கணினி மற்றும் நினைவக அணுகலைச் சரிபார்|Windows 10 மற்றும் 11இல் WMI வழியாக இயங்குதளம் மற்றும் RAM தரவை நேரடியாகப் படிக்கிறது. WMIC தேவையில்லை; அது நிறுவப்படவோ அகற்றப்படவோ மாட்டாது.|WMI கணினி அணுகலைச் சரிபார்|WMI நினைவக அணுகலைச் சரிபார்
hi|WinGet सेटअप के लिए इंटरनेट चाहिए। WMI सत्यापन ऑफ़लाइन काम करता है।|WMI से सिस्टम और मेमोरी तक पहुँच सत्यापित करें|Windows 10 और 11 पर WMI से ऑपरेटिंग सिस्टम और RAM का डेटा सीधे पढ़ता है। WMIC आवश्यक नहीं है और इसे स्थापित या हटाया नहीं जाएगा।|WMI से सिस्टम तक पहुँच सत्यापित करें|WMI से मेमोरी तक पहुँच सत्यापित करें
ms|Persediaan WinGet memerlukan Internet. Pengesahan WMI berfungsi di luar talian.|Sahkan akses sistem dan memori melalui WMI|Membaca data sistem pengendalian dan RAM terus melalui WMI pada Windows 10 dan 11. WMIC tidak diperlukan dan tidak akan dipasang atau dibuang.|Sahkan akses sistem melalui WMI|Sahkan akses memori melalui WMI
jv|Persiyapan WinGet mbutuhake Internet. Verifikasi WMI bisa ditindakake offline.|Priksa akses sistem lan memori liwat WMI|Maca data sistem operasi lan RAM langsung liwat WMI ing Windows 10 lan 11. WMIC ora dibutuhake lan ora bakal diinstal utawa dibusak.|Priksa akses sistem liwat WMI|Priksa akses memori liwat WMI
ban|Persiapan WinGet merluang Internet. Verifikasi WMI prasida kalaksanayang offline.|Priksa akses sistem lan memori liwat WMI|Maca data sistem operasi lan RAM langsung liwat WMI ring Windows 10 lan 11. WMIC nenten kaaptiang lan nenten pacang ka instal utawi kaicalang.|Priksa akses sistem liwat WMI|Priksa akses memori liwat WMI
sv|WinGet-installationen kräver internet. WMI-verifiering fungerar offline.|Verifiera WMI-åtkomst till system och minne|Läser operativsystems- och RAM-data direkt via WMI i Windows 10 och 11. WMIC krävs inte och kommer inte att installeras eller tas bort.|Verifiera WMI-systemåtkomst|Verifiera WMI-minnesåtkomst
es|La configuración de WinGet requiere Internet. La verificación WMI funciona sin conexión.|Verificar el acceso WMI al sistema y a la memoria|Lee datos del sistema operativo y de la RAM directamente mediante WMI en Windows 10 y 11. WMIC no es necesario y no se instalará ni eliminará.|Verificar el acceso WMI al sistema|Verificar el acceso WMI a la memoria
""";
}
