namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string RuntimeCompositions = """
en|{0}  [RUNNING x{1}]|{0}  [not running]|{0} optional process group(s) currently running.|Invalid limit for {0}. Use an empty value or 1-2048.|{0} active PCI device(s) loaded. Edit MSI, Limit, or Interrupt Priority, then press Apply changes.|{0} device(s) loaded in read-only mode. Run the app as Administrator to apply changes.|Save failed: {0}|Saved: {0}
id|{0}  [BERJALAN x{1}]|{0}  [tidak berjalan]|{0} grup proses opsional sedang berjalan.|Batas untuk {0} tidak valid. Kosongkan nilainya atau gunakan 1-2048.|{0} perangkat PCI aktif dimuat. Ubah MSI, Batas, atau Prioritas Interupsi, lalu tekan Terapkan perubahan.|{0} perangkat dimuat dalam mode hanya baca. Jalankan aplikasi sebagai Administrator untuk menerapkan perubahan.|Gagal menyimpan: {0}|Disimpan: {0}
de|{0}  [LÄUFT x{1}]|{0}  [läuft nicht]|{0} optionale Prozessgruppe(n) werden derzeit ausgeführt.|Ungültiger Grenzwert für {0}. Lassen Sie den Wert leer oder verwenden Sie 1-2048.|{0} aktive PCI-Geräte geladen. Ändern Sie MSI, Grenzwert oder Interruptpriorität und klicken Sie dann auf Änderungen anwenden.|{0} Geräte im schreibgeschützten Modus geladen. Führen Sie die App als Administrator aus, um Änderungen anzuwenden.|Speichern fehlgeschlagen: {0}|Gespeichert: {0}
fr|{0}  [EN COURS x{1}]|{0}  [arrêté]|{0} groupe(s) de processus facultatifs sont actuellement en cours d’exécution.|Limite incorrecte pour {0}. Laissez la valeur vide ou utilisez 1-2048.|{0} périphérique(s) PCI actifs chargés. Modifiez MSI, Limite ou Priorité des interruptions, puis cliquez sur Appliquer les modifications.|{0} périphérique(s) chargés en lecture seule. Exécutez l’application en tant qu’administrateur pour appliquer les modifications.|Échec de l’enregistrement : {0}|Enregistré : {0}
ar|{0}  [قيد التشغيل x{1}]|{0}  [غير مشغّل]|هناك {0} مجموعة من العمليات الاختيارية قيد التشغيل حاليًا.|الحد غير صالح لـ {0}. اترك القيمة فارغة أو استخدم 1-2048.|تم تحميل {0} من أجهزة PCI النشطة. عدّل MSI أو الحد أو أولوية المقاطعة، ثم اضغط على تطبيق التغييرات.|تم تحميل {0} من الأجهزة في وضع القراءة فقط. شغّل التطبيق كمسؤول لتطبيق التغييرات.|تعذّر الحفظ: {0}|تم الحفظ: {0}
tl|{0}  [TUMATAKBO x{1}]|{0}  [hindi tumatakbo]|Kasalukuyang tumatakbo ang {0} opsyonal na pangkat ng proseso.|Hindi wastong limitasyon para sa {0}. Iwanang walang laman ang halaga o gumamit ng 1-2048.|Na-load ang {0} aktibong PCI device. Baguhin ang MSI, Limitasyon, o Priyoridad ng Interrupt, pagkatapos ay pindutin ang Ilapat ang mga pagbabago.|Na-load ang {0} device sa mode na para sa pagbasa lamang. Patakbuhin ang app bilang Administrator upang ilapat ang mga pagbabago.|Hindi nai-save: {0}|Na-save: {0}
vi|{0}  [ĐANG CHẠY x{1}]|{0}  [không chạy]|Hiện có {0} nhóm tiến trình tùy chọn đang chạy.|Giới hạn không hợp lệ cho {0}. Để trống giá trị hoặc dùng 1-2048.|Đã tải {0} thiết bị PCI đang hoạt động. Chỉnh sửa MSI, Giới hạn hoặc Mức ưu tiên ngắt, rồi nhấn Áp dụng thay đổi.|Đã tải {0} thiết bị ở chế độ chỉ đọc. Chạy ứng dụng với quyền quản trị viên để áp dụng thay đổi.|Lưu thất bại: {0}|Đã lưu: {0}
zh-CN|{0}  [运行中 x{1}]|{0}  [未运行]|当前有 {0} 个可选进程组正在运行。|{0} 的限制值无效。请留空或使用 1-2048。|已加载 {0} 个活动 PCI 设备。修改 MSI、限制值或中断优先级，然后点击“应用更改”。|已以只读模式加载 {0} 个设备。请以管理员身份运行应用以应用更改。|保存失败：{0}|已保存：{0}
zh-TW|{0}  [執行中 x{1}]|{0}  [未執行]|目前有 {0} 個選用處理程序群組正在執行。|{0} 的限制值無效。請留空或使用 1-2048。|已載入 {0} 個作用中的 PCI 裝置。修改 MSI、限制值或中斷優先順序，然後按下「套用變更」。|已以唯讀模式載入 {0} 個裝置。請以系統管理員身分執行應用程式以套用變更。|儲存失敗：{0}|已儲存：{0}
th|{0}  [กำลังทำงาน x{1}]|{0}  [ไม่ได้ทำงาน]|ขณะนี้มีกลุ่มกระบวนการเสริม {0} กลุ่มกำลังทำงาน|ค่าขีดจำกัดสำหรับ {0} ไม่ถูกต้อง เว้นค่าว่างไว้หรือใช้ 1-2048|โหลดอุปกรณ์ PCI ที่ใช้งานอยู่ {0} เครื่องแล้ว แก้ไข MSI ขีดจำกัด หรือลำดับความสำคัญของอินเทอร์รัปต์ แล้วกดนำการเปลี่ยนแปลงไปใช้|โหลดอุปกรณ์ {0} เครื่องในโหมดอ่านอย่างเดียวแล้ว เรียกใช้แอปในฐานะผู้ดูแลระบบเพื่อนำการเปลี่ยนแปลงไปใช้|บันทึกไม่สำเร็จ: {0}|บันทึกแล้ว: {0}
ru|{0}  [РАБОТАЕТ x{1}]|{0}  [не работает]|Сейчас работают необязательные группы процессов: {0}.|Недопустимый предел для {0}. Оставьте значение пустым или укажите 1-2048.|Загружено активных устройств PCI: {0}. Измените MSI, предел или приоритет прерываний, затем нажмите «Применить изменения».|Загружено устройств в режиме только для чтения: {0}. Запустите приложение от имени администратора, чтобы применить изменения.|Не удалось сохранить: {0}|Сохранено: {0}
uk|{0}  [ПРАЦЮЄ x{1}]|{0}  [не працює]|Зараз працюють необов’язкові групи процесів: {0}.|Недійсна межа для {0}. Залиште значення порожнім або вкажіть 1-2048.|Завантажено активних пристроїв PCI: {0}. Змініть MSI, межу або пріоритет переривань, а потім натисніть «Застосувати зміни».|Завантажено пристроїв у режимі лише для читання: {0}. Запустіть застосунок від імені адміністратора, щоб застосувати зміни.|Не вдалося зберегти: {0}|Збережено: {0}
pt|{0}  [EM EXECUÇÃO x{1}]|{0}  [não está em execução]|{0} grupo(s) de processos opcionais em execução no momento.|Limite inválido para {0}. Deixe o valor vazio ou use 1-2048.|{0} dispositivo(s) PCI ativos carregados. Edite MSI, Limite ou Prioridade de interrupção e pressione Aplicar alterações.|{0} dispositivo(s) carregados em modo somente leitura. Execute o aplicativo como administrador para aplicar alterações.|Falha ao salvar: {0}|Salvo: {0}
ja|{0}  [実行中 x{1}]|{0}  [停止中]|現在、{0} 個のオプションのプロセスグループが実行中です。|{0} の上限が無効です。空欄にするか、1-2048 を指定してください。|{0} 台のアクティブな PCI デバイスを読み込みました。MSI、上限、または割り込み優先度を編集し、「変更を適用」を押してください。|{0} 台のデバイスを読み取り専用モードで読み込みました。変更を適用するには、管理者としてアプリを実行してください。|保存に失敗しました: {0}|保存しました: {0}
ko|{0}  [실행 중 x{1}]|{0}  [실행 중 아님]|현재 선택적 프로세스 그룹 {0}개가 실행 중입니다.|{0}의 제한값이 올바르지 않습니다. 값을 비워 두거나 1-2048을 사용하세요.|활성 PCI 장치 {0}개를 불러왔습니다. MSI, 제한 또는 인터럽트 우선순위를 수정한 다음 변경 사항 적용을 누르세요.|장치 {0}개를 읽기 전용 모드로 불러왔습니다. 변경 사항을 적용하려면 관리자 권한으로 앱을 실행하세요.|저장 실패: {0}|저장됨: {0}
ur|{0}  [چل رہا ہے x{1}]|{0}  [نہیں چل رہا]|اس وقت {0} اختیاری پروسیس گروپ چل رہے ہیں۔|{0} کے لیے حد درست نہیں ہے۔ قدر خالی چھوڑیں یا 1-2048 استعمال کریں۔|{0} فعال PCI آلات لوڈ ہو گئے ہیں۔ MSI، حد یا انٹرپٹ کی ترجیح میں ترمیم کریں، پھر تبدیلیاں لاگو کریں دبائیں۔|{0} آلات صرف پڑھنے کے موڈ میں لوڈ ہو گئے ہیں۔ تبدیلیاں لاگو کرنے کے لیے ایپ کو منتظم کے طور پر چلائیں۔|محفوظ کرنا ناکام ہوا: {0}|محفوظ ہو گیا: {0}
ta|{0}  [இயங்குகிறது x{1}]|{0}  [இயங்கவில்லை]|தற்போது {0} விருப்பச் செயல்முறைக் குழுக்கள் இயங்குகின்றன.|{0} என்பதற்கான வரம்பு செல்லாது. மதிப்பைக் காலியாக விடவும் அல்லது 1-2048 ஐப் பயன்படுத்தவும்.|செயலில் உள்ள {0} PCI சாதனங்கள் ஏற்றப்பட்டன. MSI, வரம்பு அல்லது குறுக்கீட்டு முன்னுரிமையைத் திருத்தி, பின்னர் மாற்றங்களைப் பயன்படுத்து என்பதை அழுத்தவும்.|{0} சாதனங்கள் படிக்க மட்டும் பயன்முறையில் ஏற்றப்பட்டன. மாற்றங்களைப் பயன்படுத்த, செயலியை நிர்வாகியாக இயக்கவும்.|சேமிக்க முடியவில்லை: {0}|சேமிக்கப்பட்டது: {0}
hi|{0}  [चल रहा है x{1}]|{0}  [नहीं चल रहा]|फ़िलहाल {0} वैकल्पिक प्रक्रिया समूह चल रहे हैं।|{0} के लिए सीमा अमान्य है। मान खाली छोड़ें या 1-2048 का उपयोग करें।|{0} सक्रिय PCI डिवाइस लोड किए गए। MSI, सीमा या इंटरप्ट प्राथमिकता संपादित करें, फिर परिवर्तन लागू करें दबाएँ।|{0} डिवाइस केवल पढ़ने के मोड में लोड किए गए। परिवर्तन लागू करने के लिए ऐप को व्यवस्थापक के रूप में चलाएँ।|सहेजना विफल: {0}|सहेजा गया: {0}
ms|{0}  [SEDANG BERJALAN x{1}]|{0}  [tidak berjalan]|{0} kumpulan proses pilihan sedang berjalan.|Had untuk {0} tidak sah. Biarkan nilai kosong atau gunakan 1-2048.|{0} peranti PCI aktif dimuatkan. Ubah MSI, Had atau Keutamaan Sampukan, kemudian tekan Gunakan perubahan.|{0} peranti dimuatkan dalam mod baca sahaja. Jalankan aplikasi sebagai pentadbir untuk menggunakan perubahan.|Gagal menyimpan: {0}|Disimpan: {0}
jv|{0}  [MLAKU x{1}]|{0}  [ora mlaku]|Saiki ana {0} klompok proses opsional sing mlaku.|Wates kanggo {0} ora sah. Kosongna nilaine utawa gunakna 1-2048.|{0} piranti PCI aktif wis dimuat. Owahana MSI, Wates, utawa Prioritas Interupsi, banjur pencet Terapake owah-owahan.|{0} piranti dimuat ing mode mung diwaca. Lakokna aplikasi minangka administrator kanggo ngetrapake owah-owahan.|Gagal nyimpen: {0}|Disimpen: {0}
ban|{0}  [MAJALAN x{1}]|{0}  [nenten majalan]|Mangkin wenten {0} kelompok proses opsional sane majalan.|Wates antuk {0} nenten sah. Kosingang nilainé utawi anggén 1-2048.|{0} piranti PCI aktif sampun kamuat. Ubah MSI, Wates, utawi Prioritas Interupsi, raris pencét Terapang pangubahan.|{0} piranti kamuat ring mode wantah kabaca. Jalanang aplikasi dados administrator mangda prasida nerapang pangubahan.|Nenten kasil nyimpen: {0}|Sampun kasimpen: {0}
sv|{0}  [KÖRS x{1}]|{0}  [körs inte]|{0} valfria processgrupper körs för närvarande.|Ogiltig gräns för {0}. Lämna värdet tomt eller använd 1-2048.|{0} aktiva PCI-enheter har lästs in. Ändra MSI, Gräns eller Avbrottsprioritet och tryck sedan på Tillämpa ändringar.|{0} enheter har lästs in i skrivskyddat läge. Kör appen som administratör för att tillämpa ändringar.|Det gick inte att spara: {0}|Sparat: {0}
es|{0}  [EN EJECUCIÓN x{1}]|{0}  [no está en ejecución]|Actualmente hay {0} grupo(s) de procesos opcionales en ejecución.|Límite no válido para {0}. Deje el valor vacío o use 1-2048.|Se cargaron {0} dispositivos PCI activos. Edite MSI, Límite o Prioridad de interrupción y pulse Aplicar cambios.|Se cargaron {0} dispositivos en modo de solo lectura. Ejecute la aplicación como administrador para aplicar cambios.|Error al guardar: {0}|Guardado: {0}
""";
}
