namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string Safety = """
en|WARNING: Disabling BITS can break Windows Update downloads and Microsoft Store background transfers. Restore BITS before repairing or installing Windows updates.|WARNING: Applying this option disables Print Spooler and Fax. You will not be able to print to local or network printers, process queued print jobs, discover printers, or use Windows Fax until the services are restored.|I understand that selected HIGH IMPACT / HIGH RISK items can disable Windows or hardware workflows.|Tick the HIGH IMPACT / HIGH RISK acknowledgement before applying the selected risky item(s).
id|PERINGATAN: Menonaktifkan BITS dapat mengganggu unduhan Windows Update dan transfer latar belakang Microsoft Store. Pulihkan BITS sebelum memperbaiki atau menginstal pembaruan Windows.|PERINGATAN: Menerapkan opsi ini menonaktifkan Print Spooler dan Fax. Anda tidak dapat mencetak ke printer lokal atau jaringan, memproses antrean cetak, menemukan printer, atau menggunakan Windows Fax sampai layanan dipulihkan.|Saya memahami bahwa item DAMPAK BESAR / RISIKO TINGGI yang dipilih dapat menonaktifkan fungsi Windows atau perangkat keras.|Centang persetujuan DAMPAK BESAR / RISIKO TINGGI sebelum menerapkan item berisiko yang dipilih.
de|WARNUNG: Das Deaktivieren von BITS kann Windows-Update-Downloads und Hintergrundübertragungen des Microsoft Store beeinträchtigen. Stellen Sie BITS vor dem Reparieren oder Installieren von Windows-Updates wieder her.|WARNUNG: Diese Option deaktiviert Print Spooler und Fax. Bis die Dienste wiederhergestellt sind, können Sie weder auf lokalen oder Netzwerkdruckern drucken noch Druckaufträge in der Warteschlange verarbeiten, Drucker suchen oder Windows-Fax verwenden.|Ich verstehe, dass ausgewählte Elemente mit GROSSEN AUSWIRKUNGEN / HOHEM RISIKO Windows- oder Hardwarefunktionen deaktivieren können.|Bestätigen Sie GROSSE AUSWIRKUNGEN / HOHES RISIKO, bevor Sie die ausgewählten riskanten Elemente anwenden.
fr|AVERTISSEMENT : désactiver BITS peut perturber les téléchargements Windows Update et les transferts en arrière-plan du Microsoft Store. Restaurez BITS avant de réparer ou d'installer les mises à jour Windows.|AVERTISSEMENT : cette option désactive Print Spooler et Fax. Vous ne pourrez plus imprimer sur des imprimantes locales ou réseau, traiter les travaux en attente, rechercher des imprimantes ou utiliser Windows Fax tant que les services ne seront pas restaurés.|Je comprends que les éléments sélectionnés à IMPACT IMPORTANT / RISQUE ÉLEVÉ peuvent désactiver des fonctions Windows ou matérielles.|Cochez la confirmation IMPACT IMPORTANT / RISQUE ÉLEVÉ avant d'appliquer les éléments risqués sélectionnés.
ar|تحذير: قد يؤدي تعطيل BITS إلى تعطّل تنزيلات Windows Update وعمليات النقل في الخلفية في Microsoft Store. استعد BITS قبل إصلاح تحديثات Windows أو تثبيتها.|تحذير: يؤدي تطبيق هذا الخيار إلى تعطيل Print Spooler وFax. لن تتمكن من الطباعة على الطابعات المحلية أو الشبكية، أو معالجة مهام الطباعة المنتظرة، أو اكتشاف الطابعات، أو استخدام Windows Fax حتى تتم استعادة الخدمات.|أفهم أن العناصر المحددة ذات التأثير الكبير / المخاطر العالية قد تعطل وظائف Windows أو الأجهزة.|حدد إقرار التأثير الكبير / المخاطر العالية قبل تطبيق العناصر الخطرة المحددة.
tl|BABALA: Maaaring masira ng pag-disable sa BITS ang mga download ng Windows Update at paglilipat sa background ng Microsoft Store. Ibalik ang BITS bago ayusin o mag-install ng mga update ng Windows.|BABALA: Dini-disable ng opsyong ito ang Print Spooler at Fax. Hindi ka makakapag-print sa lokal o network na printer, makakaproseso ng nakapilang print job, makakahanap ng printer, o makakagamit ng Windows Fax hanggang maibalik ang mga serbisyo.|Nauunawaan kong maaaring i-disable ng napiling mga item na may MALAKING EPEKTO / MATAAS NA PANGANIB ang mga gawain ng Windows o hardware.|Lagyan ng tsek ang pagkilala sa MALAKING EPEKTO / MATAAS NA PANGANIB bago ilapat ang napiling mapanganib na mga item.
vi|CẢNH BÁO: Vô hiệu hóa BITS có thể làm gián đoạn tải xuống Windows Update và truyền nền của Microsoft Store. Khôi phục BITS trước khi sửa chữa hoặc cài đặt bản cập nhật Windows.|CẢNH BÁO: Áp dụng tùy chọn này sẽ vô hiệu hóa Print Spooler và Fax. Bạn sẽ không thể in qua máy in cục bộ hoặc mạng, xử lý hàng đợi in, tìm máy in hoặc dùng Windows Fax cho đến khi các dịch vụ được khôi phục.|Tôi hiểu rằng các mục TÁC ĐỘNG LỚN / RỦI RO CAO được chọn có thể vô hiệu hóa chức năng của Windows hoặc phần cứng.|Đánh dấu xác nhận TÁC ĐỘNG LỚN / RỦI RO CAO trước khi áp dụng các mục rủi ro đã chọn.
zh-CN|警告：禁用 BITS 可能导致 Windows Update 下载和 Microsoft Store 后台传输无法正常工作。请在修复或安装 Windows 更新前还原 BITS。|警告：应用此选项会禁用 Print Spooler 和 Fax。在还原这些服务之前，您将无法使用本地或网络打印机打印、处理排队的打印作业、发现打印机或使用 Windows Fax。|我理解所选的高影响 / 高风险项目可能会禁用 Windows 或硬件功能。|应用所选高风险项目之前，请勾选高影响 / 高风险确认框。
zh-TW|警告：停用 BITS 可能導致 Windows Update 下載和 Microsoft Store 背景傳輸無法正常運作。請在修復或安裝 Windows 更新前還原 BITS。|警告：套用此選項會停用 Print Spooler 和 Fax。在還原這些服務之前，您將無法使用本機或網路印表機列印、處理佇列中的列印工作、探索印表機或使用 Windows Fax。|我了解所選的高影響 / 高風險項目可能會停用 Windows 或硬體功能。|套用所選高風險項目之前，請勾選高影響 / 高風險確認方塊。
th|คำเตือน: การปิด BITS อาจทำให้การดาวน์โหลด Windows Update และการถ่ายโอนเบื้องหลังของ Microsoft Store ใช้งานไม่ได้ คืนค่า BITS ก่อนซ่อมแซมหรือติดตั้งการอัปเดต Windows|คำเตือน: การใช้ตัวเลือกนี้จะปิด Print Spooler และ Fax คุณจะไม่สามารถพิมพ์ผ่านเครื่องพิมพ์ในเครื่องหรือเครือข่าย ประมวลผลงานพิมพ์ที่รออยู่ ค้นหาเครื่องพิมพ์ หรือใช้ Windows Fax ได้จนกว่าจะคืนค่าบริการ|ฉันเข้าใจว่ารายการที่เลือกซึ่งมีผลกระทบสูง / ความเสี่ยงสูงอาจปิดการทำงานของ Windows หรือฮาร์ดแวร์|ทำเครื่องหมายยอมรับผลกระทบสูง / ความเสี่ยงสูงก่อนใช้รายการเสี่ยงที่เลือก
ru|ПРЕДУПРЕЖДЕНИЕ: отключение BITS может нарушить загрузку обновлений Windows Update и фоновые передачи Microsoft Store. Восстановите BITS перед исправлением или установкой обновлений Windows.|ПРЕДУПРЕЖДЕНИЕ: применение этого параметра отключает Print Spooler и Fax. До восстановления служб вы не сможете печатать на локальных или сетевых принтерах, обрабатывать задания в очереди печати, обнаруживать принтеры или использовать Windows Fax.|Я понимаю, что выбранные элементы с СИЛЬНЫМ ВЛИЯНИЕМ / ВЫСОКИМ РИСКОМ могут отключить функции Windows или оборудования.|Подтвердите СИЛЬНОЕ ВЛИЯНИЕ / ВЫСОКИЙ РИСК перед применением выбранных рискованных элементов.
uk|ПОПЕРЕДЖЕННЯ: вимкнення BITS може порушити завантаження Windows Update і фонові передавання Microsoft Store. Відновіть BITS перед виправленням або встановленням оновлень Windows.|ПОПЕРЕДЖЕННЯ: застосування цього параметра вимикає Print Spooler і Fax. До відновлення служб ви не зможете друкувати на локальних або мережевих принтерах, обробляти завдання в черзі друку, виявляти принтери або використовувати Windows Fax.|Я розумію, що вибрані елементи зі ЗНАЧНИМ ВПЛИВОМ / ВИСОКИМ РИЗИКОМ можуть вимкнути функції Windows або обладнання.|Підтвердьте ЗНАЧНИЙ ВПЛИВ / ВИСОКИЙ РИЗИК перед застосуванням вибраних ризикованих елементів.
pt|AVISO: desativar o BITS pode impedir as transferências do Windows Update e as transferências em segundo plano da Microsoft Store. Restaure o BITS antes de reparar ou instalar atualizações do Windows.|AVISO: aplicar esta opção desativa Print Spooler e Fax. Não poderá imprimir em impressoras locais ou de rede, processar trabalhos de impressão em fila, detetar impressoras ou utilizar o Windows Fax até que os serviços sejam restaurados.|Compreendo que os itens selecionados de ALTO IMPACTO / ALTO RISCO podem desativar funções do Windows ou do hardware.|Marque a confirmação de ALTO IMPACTO / ALTO RISCO antes de aplicar os itens de risco selecionados.
ja|警告：BITS を無効にすると、Windows Update のダウンロードや Microsoft Store のバックグラウンド転送が機能しなくなる可能性があります。Windows 更新の修復またはインストール前に BITS を復元してください。|警告：このオプションを適用すると Print Spooler と Fax が無効になります。サービスが復元されるまで、ローカルまたはネットワーク プリンターでの印刷、印刷待ちジョブの処理、プリンターの検出、Windows Fax の使用ができなくなります。|選択した「影響が大きい / 高リスク」の項目により、Windows またはハードウェアの機能が無効になる可能性があることを理解しています。|選択した危険な項目を適用する前に、「影響が大きい / 高リスク」の確認欄にチェックしてください。
ko|경고: BITS를 비활성화하면 Windows Update 다운로드와 Microsoft Store 백그라운드 전송이 작동하지 않을 수 있습니다. Windows 업데이트를 복구하거나 설치하기 전에 BITS를 복원하세요.|경고: 이 옵션을 적용하면 Print Spooler와 Fax가 비활성화됩니다. 서비스를 복원할 때까지 로컬 또는 네트워크 프린터로 인쇄하거나, 대기 중인 인쇄 작업을 처리하거나, 프린터를 검색하거나, Windows Fax를 사용할 수 없습니다.|선택한 큰 영향 / 높은 위험 항목이 Windows 또는 하드웨어 기능을 비활성화할 수 있음을 이해합니다.|선택한 위험 항목을 적용하기 전에 큰 영향 / 높은 위험 확인란을 선택하세요.
ur|انتباہ: BITS کو غیر فعال کرنے سے Windows Update کے ڈاؤن لوڈ اور Microsoft Store کی پس منظر میں منتقلی متاثر ہو سکتی ہے۔ Windows اپ ڈیٹس کی مرمت یا تنصیب سے پہلے BITS بحال کریں۔|انتباہ: یہ اختیار لاگو کرنے سے Print Spooler اور Fax غیر فعال ہو جاتے ہیں۔ خدمات بحال ہونے تک آپ مقامی یا نیٹ ورک پرنٹر پر پرنٹ، قطار میں موجود پرنٹ کاموں پر کارروائی، پرنٹر تلاش، یا Windows Fax استعمال نہیں کر سکیں گے۔|میں سمجھتا ہوں کہ منتخب زیادہ اثر / زیادہ خطرے والے عناصر Windows یا ہارڈویئر کی فعالیت کو غیر فعال کر سکتے ہیں۔|منتخب خطرناک عناصر لاگو کرنے سے پہلے زیادہ اثر / زیادہ خطرے کی تصدیق پر نشان لگائیں۔
ta|எச்சரிக்கை: BITS-ஐ முடக்குவது Windows Update பதிவிறக்கங்களையும் Microsoft Store பின்னணிப் பரிமாற்றங்களையும் பாதிக்கலாம். Windows புதுப்பிப்புகளைப் பழுதுபார்க்கும் அல்லது நிறுவும் முன் BITS-ஐ மீட்டமைக்கவும்.|எச்சரிக்கை: இந்த விருப்பத்தைப் பயன்படுத்துவது Print Spooler மற்றும் Fax-ஐ முடக்கும். சேவைகள் மீட்டமைக்கப்படும் வரை உள்ளூர் அல்லது வலைப்பின்னல் அச்சுப்பொறிகளில் அச்சிடுதல், வரிசையில் உள்ள அச்சுப் பணிகளைச் செயலாக்குதல், அச்சுப்பொறிகளைக் கண்டறிதல் அல்லது Windows Fax பயன்படுத்துதல் முடியாது.|தேர்ந்தெடுத்த அதிக தாக்கம் / அதிக ஆபத்துள்ள உருப்படிகள் Windows அல்லது வன்பொருள் செயல்பாடுகளை முடக்கக்கூடும் என்பதைப் புரிந்துகொள்கிறேன்.|தேர்ந்தெடுத்த ஆபத்துள்ள உருப்படிகளைப் பயன்படுத்தும் முன் அதிக தாக்கம் / அதிக ஆபத்துக்கான ஒப்புதல் பெட்டியைத் தேர்வு செய்யவும்.
hi|चेतावनी: BITS अक्षम करने से Windows Update डाउनलोड और Microsoft Store के बैकग्राउंड ट्रांसफ़र बाधित हो सकते हैं। Windows अपडेट की मरम्मत या स्थापना से पहले BITS बहाल करें।|चेतावनी: यह विकल्प लागू करने से Print Spooler और Fax अक्षम हो जाते हैं। सेवाएँ बहाल होने तक आप स्थानीय या नेटवर्क प्रिंटर पर प्रिंट नहीं कर पाएँगे, कतार के प्रिंट कार्य संसाधित नहीं कर पाएँगे, प्रिंटर खोज नहीं पाएँगे या Windows Fax का उपयोग नहीं कर पाएँगे।|मैं समझता हूँ कि चयनित अधिक प्रभाव / अधिक जोखिम वाले आइटम Windows या हार्डवेयर की कार्यक्षमताएँ अक्षम कर सकते हैं।|चयनित जोखिम वाले आइटम लागू करने से पहले अधिक प्रभाव / अधिक जोखिम की स्वीकृति पर टिक करें।
ms|AMARAN: Melumpuhkan BITS boleh mengganggu muat turun Windows Update dan pemindahan latar belakang Microsoft Store. Pulihkan BITS sebelum membaiki atau memasang kemas kini Windows.|AMARAN: Menggunakan pilihan ini melumpuhkan Print Spooler dan Fax. Anda tidak boleh mencetak melalui pencetak setempat atau rangkaian, memproses tugas cetakan beratur, mengesan pencetak atau menggunakan Windows Fax sehingga perkhidmatan dipulihkan.|Saya memahami bahawa item IMPAK TINGGI / RISIKO TINGGI yang dipilih boleh melumpuhkan fungsi Windows atau perkakasan.|Tandakan pengakuan IMPAK TINGGI / RISIKO TINGGI sebelum menggunakan item berisiko yang dipilih.
jv|PÈNGET: Mateni BITS bisa ngganggu undhuhan Windows Update lan transfer latar mburi Microsoft Store. Pulihake BITS sadurunge ndandani utawa nginstal pembaruan Windows.|PÈNGET: Nerapake pilihan iki mateni Print Spooler lan Fax. Sampeyan ora bisa nyithak menyang printer lokal utawa jaringan, ngolah antrean cetak, nemokake printer, utawa nggunakake Windows Fax nganti layanane dipulihake.|Aku ngerti yen item DAMPAK GEDHÉ / RISIKO DHUWUR sing dipilih bisa mateni fungsi Windows utawa piranti keras.|Centhang pangakuan DAMPAK GEDHÉ / RISIKO DHUWUR sadurunge nerapake item bebaya sing dipilih.
ban|PANGELING: Matiang BITS prasida ngusak unduhan Windows Update miwah transfer latar belakang Microsoft Store. Pulihang BITS sadurung ngaryanin becik utawi nginstal pembaruan Windows.|PANGELING: Nerapang pilihan puniki matiang Print Spooler miwah Fax. Ragane nenten prasida nyetak ka printer lokal utawi jaringan, ngolah antrean cetak, ngrereh printer, utawi nganggen Windows Fax ngantos layanan kapulihang.|Tiang uning item DAMPAK AGENG / RISIKO TEGEH sane kapilih prasida matiang fungsi Windows utawi piranti keras.|Centang persetujuan DAMPAK AGENG / RISIKO TEGEH sadurung nerapang item marisiko sane kapilih.
sv|VARNING: Om BITS inaktiveras kan hämtningar via Windows Update och bakgrundsöverföringar i Microsoft Store sluta fungera. Återställ BITS innan du reparerar eller installerar Windows-uppdateringar.|VARNING: Det här alternativet inaktiverar Print Spooler och Fax. Du kan inte skriva ut på lokala skrivare eller nätverksskrivare, behandla köade utskriftsjobb, hitta skrivare eller använda Windows Fax förrän tjänsterna har återställts.|Jag förstår att valda objekt med STOR PÅVERKAN / HÖG RISK kan inaktivera funktioner i Windows eller maskinvaran.|Markera bekräftelsen för STOR PÅVERKAN / HÖG RISK innan du tillämpar de valda riskfyllda objekten.
es|ADVERTENCIA: desactivar BITS puede impedir las descargas de Windows Update y las transferencias en segundo plano de Microsoft Store. Restaure BITS antes de reparar o instalar actualizaciones de Windows.|ADVERTENCIA: aplicar esta opción desactiva Print Spooler y Fax. No podrá imprimir en impresoras locales o de red, procesar trabajos de impresión en cola, detectar impresoras ni usar Windows Fax hasta que se restauren los servicios.|Entiendo que los elementos seleccionados de ALTO IMPACTO / ALTO RIESGO pueden desactivar funciones de Windows o del hardware.|Marque la confirmación de ALTO IMPACTO / ALTO RIESGO antes de aplicar los elementos arriesgados seleccionados.
""";
}
