namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string WorkflowDialogs = """
en|Task already active|Profile operation failed|Windows De-bloat failed|Windows restart required|Restart now|Restart failed|Task is still running|Wait until the active or queued task is complete before closing the application.|All open applications will be closed. Save your work before continuing. Restart Windows now?|Administrator rights are required for this BitLocker operation.|Parsing active PCI registry keys and IRQ resources...|Select rows, then Apply selected to apply their tweaks or Restore selected to replay saved state/documented Windows service defaults. Toggle switches change one item after confirmation.
id|Tugas sudah aktif|Operasi profil gagal|Pembersihan Windows gagal|Windows perlu dimulai ulang|Mulai ulang sekarang|Gagal memulai ulang|Tugas masih berjalan|Tunggu sampai tugas aktif atau dalam antrean selesai sebelum menutup aplikasi.|Semua aplikasi yang terbuka akan ditutup. Simpan pekerjaan Anda sebelum melanjutkan. Mulai ulang Windows sekarang?|Hak Administrator diperlukan untuk operasi BitLocker ini.|Membaca kunci registri PCI aktif dan sumber daya IRQ...|Pilih baris, lalu gunakan Terapkan pilihan untuk menerapkan penyesuaiannya atau Pulihkan pilihan untuk memulihkan keadaan tersimpan/nilai bawaan layanan Windows yang terdokumentasi. Sakelar mengubah satu item setelah konfirmasi.
de|Aufgabe bereits aktiv|Profilvorgang fehlgeschlagen|Windows-Bereinigung fehlgeschlagen|Windows-Neustart erforderlich|Jetzt neu starten|Neustart fehlgeschlagen|Aufgabe wird noch ausgeführt|Warten Sie vor dem Schließen der Anwendung, bis die aktive oder eingereihte Aufgabe abgeschlossen ist.|Alle geöffneten Anwendungen werden geschlossen. Speichern Sie Ihre Arbeit, bevor Sie fortfahren. Windows jetzt neu starten?|Für diesen BitLocker-Vorgang sind Administratorrechte erforderlich.|Aktive PCI-Registrierungsschlüssel und IRQ-Ressourcen werden ausgewertet...|Wählen Sie Zeilen und anschließend Auswahl anwenden, um deren Anpassungen anzuwenden, oder Auswahl wiederherstellen, um den gespeicherten Zustand/dokumentierte Windows-Dienststandards wiederherzustellen. Schalter ändern nach Bestätigung jeweils ein Element.
fr|Tâche déjà active|Échec de l’opération sur le profil|Échec du nettoyage de Windows|Redémarrage de Windows requis|Redémarrer maintenant|Échec du redémarrage|La tâche est toujours en cours|Attendez la fin de la tâche active ou en attente avant de fermer l’application.|Toutes les applications ouvertes seront fermées. Enregistrez votre travail avant de continuer. Redémarrer Windows maintenant ?|Des droits d’administrateur sont nécessaires pour cette opération BitLocker.|Analyse des clés de registre PCI actives et des ressources IRQ...|Sélectionnez des lignes, puis Appliquer la sélection pour appliquer leurs réglages ou Restaurer la sélection pour rétablir l’état enregistré/les valeurs par défaut documentées des services Windows. Les interrupteurs modifient un élément après confirmation.
ar|المهمة نشطة بالفعل|فشلت عملية ملف الأداء|فشل تنظيف Windows|يلزم إعادة تشغيل Windows|إعادة التشغيل الآن|فشلت إعادة التشغيل|المهمة ما زالت قيد التشغيل|انتظر حتى تكتمل المهمة النشطة أو الموجودة في قائمة الانتظار قبل إغلاق التطبيق.|ستُغلق جميع التطبيقات المفتوحة. احفظ عملك قبل المتابعة. هل تريد إعادة تشغيل Windows الآن؟|تتطلب عملية BitLocker هذه صلاحيات المسؤول.|جارٍ تحليل مفاتيح سجل PCI النشطة وموارد IRQ...|حدد الصفوف، ثم اختر تطبيق المحدد لتطبيق تعديلاتها أو استعادة المحدد لاستعادة الحالة المحفوظة أو القيم الافتراضية الموثقة لخدمات Windows. يغيّر كل مفتاح تبديل عنصرًا واحدًا بعد التأكيد.
tl|Aktibo na ang gawain|Nabigo ang operasyon sa profile|Nabigo ang paglilinis ng Windows|Kailangang i-restart ang Windows|I-restart ngayon|Nabigo ang pag-restart|Tumatakbo pa ang gawain|Hintaying matapos ang aktibo o nakapilang gawain bago isara ang aplikasyon.|Isasara ang lahat ng bukas na aplikasyon. I-save ang iyong ginagawa bago magpatuloy. I-restart ang Windows ngayon?|Kailangan ang mga karapatan ng Administrator para sa operasyong ito ng BitLocker.|Sinusuri ang mga aktibong PCI registry key at IRQ resource...|Pumili ng mga hilera, pagkatapos ay Ilapat ang pinili para ilapat ang mga pagsasaayos o Ibalik ang pinili para ibalik ang naka-save na estado/dokumentadong mga default ng serbisyo ng Windows. Binabago ng mga switch ang isang item pagkatapos ng kumpirmasyon.
vi|Tác vụ đã hoạt động|Thao tác cấu hình thất bại|Dọn dẹp Windows thất bại|Cần khởi động lại Windows|Khởi động lại ngay|Khởi động lại thất bại|Tác vụ vẫn đang chạy|Đợi tác vụ đang hoạt động hoặc đang xếp hàng hoàn tất trước khi đóng ứng dụng.|Tất cả ứng dụng đang mở sẽ bị đóng. Lưu công việc trước khi tiếp tục. Khởi động lại Windows ngay?|Thao tác BitLocker này yêu cầu quyền quản trị viên.|Đang phân tích khóa đăng ký PCI đang hoạt động và tài nguyên IRQ...|Chọn các hàng, rồi chọn Áp dụng mục đã chọn để áp dụng tinh chỉnh hoặc Khôi phục mục đã chọn để khôi phục trạng thái đã lưu/giá trị mặc định dịch vụ Windows theo tài liệu. Công tắc thay đổi một mục sau khi xác nhận.
zh-CN|任务已在运行|配置操作失败|Windows 清理失败|需要重启 Windows|立即重启|重启失败|任务仍在运行|请等待正在运行或排队的任务完成后再关闭应用。|所有打开的应用都将关闭。请先保存工作再继续。现在重启 Windows 吗？|此 BitLocker 操作需要管理员权限。|正在分析活动 PCI 注册表项和 IRQ 资源...|选择行，然后使用“应用所选项”应用其调整，或使用“还原所选项”恢复保存的状态或文档记载的 Windows 服务默认值。开关在确认后更改单个项目。
zh-TW|工作已在執行|設定檔操作失敗|Windows 清理失敗|需要重新啟動 Windows|立即重新啟動|重新啟動失敗|工作仍在執行|請等候執行中或佇列中的工作完成後再關閉應用程式。|所有開啟的應用程式都將關閉。請先儲存工作再繼續。現在重新啟動 Windows 嗎？|此 BitLocker 操作需要系統管理員權限。|正在分析作用中的 PCI 登錄機碼和 IRQ 資源...|選取資料列，再使用「套用選取項目」套用其調整，或使用「還原選取項目」恢復已儲存的狀態或文件記載的 Windows 服務預設值。切換開關會在確認後變更單一項目。
th|งานกำลังทำงานอยู่แล้ว|การดำเนินการกับโปรไฟล์ล้มเหลว|การล้างแอปที่ไม่จำเป็นของ Windows ล้มเหลว|ต้องรีสตาร์ต Windows|รีสตาร์ตตอนนี้|รีสตาร์ตไม่สำเร็จ|งานยังคงทำงานอยู่|รอให้งานที่กำลังทำงานหรืออยู่ในคิวเสร็จสิ้นก่อนปิดแอปพลิเคชัน|แอปพลิเคชันที่เปิดอยู่ทั้งหมดจะถูกปิด บันทึกงานก่อนดำเนินการต่อ ต้องการรีสตาร์ต Windows ตอนนี้หรือไม่?|ต้องมีสิทธิ์ผู้ดูแลระบบสำหรับการดำเนินการ BitLocker นี้|กำลังวิเคราะห์คีย์รีจิสทรี PCI ที่ใช้งานและทรัพยากร IRQ...|เลือกแถว แล้วเลือกนำรายการที่เลือกไปใช้เพื่อใช้การปรับแต่ง หรือกู้คืนรายการที่เลือกเพื่อคืนสถานะที่บันทึกไว้/ค่าเริ่มต้นบริการ Windows ตามเอกสาร สวิตช์จะเปลี่ยนทีละรายการหลังจากยืนยัน
ru|Задача уже активна|Ошибка операции с профилем|Не удалось очистить Windows|Требуется перезапуск Windows|Перезапустить сейчас|Не удалось перезапустить|Задача ещё выполняется|Перед закрытием приложения дождитесь завершения активной задачи или задачи в очереди.|Все открытые приложения будут закрыты. Сохраните работу перед продолжением. Перезапустить Windows сейчас?|Для этой операции BitLocker требуются права администратора.|Анализ активных разделов реестра PCI и ресурсов IRQ...|Выберите строки, затем Применить выбранное для применения настроек или Восстановить выбранное для возврата сохранённого состояния/документированных значений служб Windows по умолчанию. Переключатели изменяют один элемент после подтверждения.
uk|Завдання вже активне|Помилка операції з профілем|Не вдалося очистити Windows|Потрібен перезапуск Windows|Перезапустити зараз|Не вдалося перезапустити|Завдання ще виконується|Перед закриттям програми дочекайтеся завершення активного завдання або завдання в черзі.|Усі відкриті програми буде закрито. Збережіть роботу, перш ніж продовжити. Перезапустити Windows зараз?|Для цієї операції BitLocker потрібні права адміністратора.|Аналіз активних розділів реєстру PCI та ресурсів IRQ...|Виберіть рядки, потім Застосувати вибране для застосування налаштувань або Відновити вибране для повернення збереженого стану/документованих стандартних значень служб Windows. Перемикачі змінюють один елемент після підтвердження.
pt|Tarefa já ativa|Falha na operação do perfil|Falha na limpeza do Windows|É necessário reiniciar o Windows|Reiniciar agora|Falha ao reiniciar|A tarefa ainda está em execução|Aguarde a conclusão da tarefa ativa ou em fila antes de fechar a aplicação.|Todas as aplicações abertas serão fechadas. Guarde o seu trabalho antes de continuar. Reiniciar o Windows agora?|São necessários direitos de administrador para esta operação do BitLocker.|A analisar chaves de registo PCI ativas e recursos IRQ...|Selecione linhas e depois Aplicar seleção para aplicar os ajustes ou Restaurar seleção para repor o estado guardado/as predefinições documentadas dos serviços Windows. Os interruptores alteram um elemento após confirmação.
ja|タスクは既に実行中です|プロファイル操作に失敗しました|Windows の不要項目の削除に失敗しました|Windows の再起動が必要です|今すぐ再起動|再起動に失敗しました|タスクはまだ実行中です|アクティブなタスクまたは待機列のタスクが完了してからアプリを閉じてください。|開いているアプリはすべて閉じられます。続行する前に作業を保存してください。今すぐ Windows を再起動しますか？|この BitLocker 操作には管理者権限が必要です。|アクティブな PCI レジストリキーと IRQ リソースを解析しています...|行を選択し、「選択項目を適用」で調整を適用するか、「選択項目を復元」で保存された状態または文書化された Windows サービスの既定値に戻します。切り替えスイッチは確認後に個別の項目を変更します。
ko|작업이 이미 활성 상태입니다|프로필 작업 실패|Windows 정리 실패|Windows를 다시 시작해야 합니다|지금 다시 시작|다시 시작 실패|작업이 아직 실행 중입니다|활성 작업이나 대기열의 작업이 완료될 때까지 기다린 후 앱을 닫으세요.|열려 있는 모든 앱이 닫힙니다. 계속하기 전에 작업을 저장하세요. 지금 Windows를 다시 시작할까요?|이 BitLocker 작업에는 관리자 권한이 필요합니다.|활성 PCI 레지스트리 키와 IRQ 리소스를 분석하는 중...|행을 선택한 뒤 선택 항목 적용으로 조정을 적용하거나 선택 항목 복원으로 저장된 상태/문서화된 Windows 서비스 기본값을 복원하세요. 토글 스위치는 확인 후 한 항목을 변경합니다.
ur|کام پہلے سے فعال ہے|پروفائل کی کارروائی ناکام ہوئی|Windows کی صفائی ناکام ہوئی|Windows کو دوبارہ شروع کرنا ضروری ہے|ابھی دوبارہ شروع کریں|دوبارہ شروع کرنا ناکام ہوا|کام ابھی چل رہا ہے|ایپ بند کرنے سے پہلے فعال یا قطار میں موجود کام کے مکمل ہونے کا انتظار کریں۔|تمام کھلی ایپس بند ہو جائیں گی۔ جاری رکھنے سے پہلے اپنا کام محفوظ کریں۔ کیا ابھی Windows دوبارہ شروع کریں؟|BitLocker کی اس کارروائی کے لیے منتظم کے اختیارات درکار ہیں۔|فعال PCI رجسٹری کلیدوں اور IRQ وسائل کا تجزیہ جاری ہے...|قطاریں منتخب کریں، پھر ان کی تبدیلیاں لاگو کرنے کے لیے منتخب پر لاگو کریں یا محفوظ حالت/دستاویزی Windows سروس کی طے شدہ اقدار بحال کرنے کے لیے منتخب بحال کریں استعمال کریں۔ ٹوگل سوئچ تصدیق کے بعد ایک آئٹم تبدیل کرتے ہیں۔
ta|பணி ஏற்கனவே செயலில் உள்ளது|செயல்திறன் சுயவிவரச் செயல் தோல்வியடைந்தது|Windows தேவையற்ற கூறுகளை அகற்றுதல் தோல்வியடைந்தது|Windows-ஐ மறுதொடக்கம் செய்ய வேண்டும்|இப்போது மறுதொடக்கம் செய்|மறுதொடக்கம் தோல்வியடைந்தது|பணி இன்னும் இயங்குகிறது|பயன்பாட்டை மூடும் முன் செயலில் உள்ள அல்லது வரிசையில் உள்ள பணி முடியும் வரை காத்திருக்கவும்.|திறந்திருக்கும் அனைத்துப் பயன்பாடுகளும் மூடப்படும். தொடர்வதற்கு முன் உங்கள் வேலையைச் சேமிக்கவும். இப்போது Windows-ஐ மறுதொடக்கம் செய்யவா?|இந்த BitLocker செயலுக்கு நிர்வாகி உரிமைகள் தேவை.|செயலில் உள்ள PCI பதிவக விசைகள் மற்றும் IRQ வளங்கள் பகுப்பாய்வு செய்யப்படுகின்றன...|வரிசைகளைத் தேர்ந்தெடுத்து, அவற்றின் மாற்றங்களைப் பயன்படுத்த தேர்ந்தெடுத்தவற்றைப் பயன்படுத்து அல்லது சேமித்த நிலை/ஆவணப்படுத்தப்பட்ட Windows சேவை இயல்புநிலைகளை மீட்டமைக்க தேர்ந்தெடுத்தவற்றை மீட்டமை என்பதைப் பயன்படுத்தவும். உறுதிப்படுத்திய பின் மாற்றுச் சுவிட்ச் ஒரு உருப்படியை மாற்றும்.
hi|कार्य पहले से सक्रिय है|प्रोफ़ाइल कार्रवाई विफल|Windows की सफ़ाई विफल|Windows को पुनः प्रारंभ करना आवश्यक है|अभी पुनः प्रारंभ करें|पुनः प्रारंभ करना विफल|कार्य अभी चल रहा है|ऐप बंद करने से पहले सक्रिय या कतार में मौजूद कार्य पूरा होने की प्रतीक्षा करें।|सभी खुले ऐप बंद हो जाएंगे। आगे बढ़ने से पहले अपना काम सहेजें। क्या अभी Windows पुनः प्रारंभ करें?|इस BitLocker कार्रवाई के लिए व्यवस्थापक अधिकार आवश्यक हैं।|सक्रिय PCI रजिस्ट्री कुंजियों और IRQ संसाधनों का विश्लेषण हो रहा है...|पंक्तियाँ चुनें, फिर उनके बदलाव लागू करने के लिए चयनित लागू करें या सहेजी गई स्थिति/दस्तावेज़ित Windows सेवा डिफ़ॉल्ट बहाल करने के लिए चयनित पुनर्स्थापित करें इस्तेमाल करें। टॉगल स्विच पुष्टि के बाद एक आइटम बदलते हैं।
ms|Tugas sudah aktif|Operasi profil gagal|Pembersihan Windows gagal|Windows perlu dimulakan semula|Mulakan semula sekarang|Gagal memulakan semula|Tugas masih berjalan|Tunggu sehingga tugas aktif atau dalam giliran selesai sebelum menutup aplikasi.|Semua aplikasi terbuka akan ditutup. Simpan kerja anda sebelum meneruskan. Mulakan semula Windows sekarang?|Hak Pentadbir diperlukan untuk operasi BitLocker ini.|Menganalisis kekunci pendaftaran PCI aktif dan sumber IRQ...|Pilih baris, kemudian Gunakan pilihan untuk menggunakan pelarasannya atau Pulihkan pilihan untuk mengembalikan keadaan tersimpan/nilai lalai perkhidmatan Windows yang didokumenkan. Suis togol menukar satu item selepas pengesahan.
jv|Tugas wis aktif|Operasi profil gagal|Reresik Windows gagal|Windows kudu diwiwiti maneh|Wiwiti maneh saiki|Gagal miwiti maneh|Tugas isih mlaku|Enteni nganti tugas aktif utawa sing ana ing antrean rampung sadurunge nutup aplikasi.|Kabeh aplikasi sing mbukak bakal ditutup. Simpen gaweyan panjenengan sadurunge nerusake. Wiwiti maneh Windows saiki?|Operasi BitLocker iki mbutuhake hak Administrator.|Maca kunci registri PCI aktif lan sumber daya IRQ...|Pilih larik, banjur gunakake Terapake pilihan kanggo ngetrapake pangowahane utawa Pulihake pilihan kanggo mbalekake kahanan sing disimpen/nilai gawan layanan Windows sing didokumentasikake. Sakelar ngowahi siji item sawise konfirmasi.
ban|Tugas sampun aktif|Operasi profil gagal|Pangresikan Windows gagal|Windows patut kawiwitin malih|Wiwitin malih mangkin|Gagal ngawitin malih|Tugas kantun majalan|Antos kantos tugas aktif utawi ring antrean puput sadurung nutup aplikasi.|Sakancan aplikasi sane kabuka pacang katutup. Simpen pakaryan sadurung nglanturang. Wiwitin malih Windows mangkin?|Operasi BitLocker puniki merluang hak Administrator.|Maca kunci registri PCI aktif miwah sumber daya IRQ...|Pilih baris, raris anggen Terapang pilihan anggen nerapang pangubahan utawi Pulihang pilihan anggen ngwaliang kawentenan kasimpen/nilai bawaan layanan Windows sane kadokumentasiang. Sakelar ngubah asiki item sasampun konfirmasi.
sv|Uppgiften är redan aktiv|Profilåtgärden misslyckades|Windows-rensningen misslyckades|Windows måste startas om|Starta om nu|Omstarten misslyckades|Uppgiften körs fortfarande|Vänta tills den aktiva eller köade uppgiften är klar innan du stänger programmet.|Alla öppna program kommer att stängas. Spara ditt arbete innan du fortsätter. Starta om Windows nu?|Administratörsbehörighet krävs för den här BitLocker-åtgärden.|Analyserar aktiva PCI-registernycklar och IRQ-resurser...|Välj rader och sedan Tillämpa valda för att tillämpa deras justeringar eller Återställ valda för att återställa sparat tillstånd/dokumenterade standardvärden för Windows-tjänster. Växlingsknappar ändrar ett objekt efter bekräftelse.
es|La tarea ya está activa|Error en la operación del perfil|Error en la limpieza de Windows|Es necesario reiniciar Windows|Reiniciar ahora|Error al reiniciar|La tarea sigue en ejecución|Espere a que termine la tarea activa o en cola antes de cerrar la aplicación.|Se cerrarán todas las aplicaciones abiertas. Guarde su trabajo antes de continuar. ¿Reiniciar Windows ahora?|Se requieren permisos de administrador para esta operación de BitLocker.|Analizando claves de registro PCI activas y recursos IRQ...|Seleccione filas y luego Aplicar selección para aplicar sus ajustes o Restaurar selección para recuperar el estado guardado/los valores predeterminados documentados de los servicios de Windows. Los interruptores cambian un elemento tras confirmarlo.
""";
}
