namespace Naufal_Windows_Tech_s_Powertoys;

internal static partial class NativeUiCatalog
{
    private const string PhotoViewerMessages = """
en|Registration={0}/{1}. {2}|Ready in Open with; choose Windows Photo Viewer in Default Apps for PNG/JPG and other image types.|Registration is incomplete. Apply to repair image handlers; ON does not mean the default app was changed.|The Photo Viewer registration snapshot version is unsupported. Backup retained.|Windows Photo Viewer DLL was not found.|PhotoViewer.dll is missing|This Windows installation does not contain the legacy Photo Viewer DLL.|View pictures with Windows Photo Viewer.
id|Pendaftaran={0}/{1}. {2}|Siap di Open with; pilih Windows Photo Viewer di Default Apps untuk PNG/JPG dan jenis gambar lainnya.|Pendaftaran belum lengkap. Terapkan untuk memperbaiki penangan gambar; AKTIF tidak berarti aplikasi bawaan telah diubah.|Versi rekaman pendaftaran Photo Viewer tidak didukung. Cadangan dipertahankan.|DLL Windows Photo Viewer tidak ditemukan.|PhotoViewer.dll tidak ada|Instalasi Windows ini tidak memiliki DLL Photo Viewer klasik.|Lihat gambar dengan Windows Photo Viewer.
ms|Pendaftaran={0}/{1}. {2}|Sedia dalam Open with; pilih Windows Photo Viewer dalam Default Apps untuk PNG/JPG dan jenis imej lain.|Pendaftaran tidak lengkap. Terapkan untuk membaiki pengendali imej; HIDUP tidak bermakna aplikasi lalai telah ditukar.|Versi petikan pendaftaran Photo Viewer tidak disokong. Sandaran dikekalkan.|DLL Windows Photo Viewer tidak ditemui.|PhotoViewer.dll tiada|Pemasangan Windows ini tidak mengandungi DLL Photo Viewer klasik.|Lihat gambar dengan Windows Photo Viewer.
tl|Pagpaparehistro={0}/{1}. {2}|Handa sa Open with; piliin ang Windows Photo Viewer sa Default Apps para sa PNG/JPG at iba pang uri ng larawan.|Hindi kumpleto ang pagpaparehistro. Ilapat upang ayusin ang mga tagahawak ng larawan; ang BUKAS ay hindi nangangahulugang nabago na ang default na app.|Hindi suportado ang bersiyon ng naka-save na pagpaparehistro ng Photo Viewer. Napanatili ang backup.|Hindi nakita ang DLL ng Windows Photo Viewer.|Nawawala ang PhotoViewer.dll|Wala sa instalasyong ito ng Windows ang DLL ng klasikong Photo Viewer.|Tingnan ang mga larawan gamit ang Windows Photo Viewer.
jv|Pendaftaran={0}/{1}. {2}|Siap ing Open with; pilih Windows Photo Viewer ing Default Apps kanggo PNG/JPG lan jinis gambar liyane.|Pendaftaran durung pepak. Terapake kanggo ndandani panangan gambar; AKTIF ora ateges aplikasi gawan wis diganti.|Versi rekaman pendaftaran Photo Viewer ora didhukung. Cadangan tetep disimpen.|DLL Windows Photo Viewer ora ditemokake.|PhotoViewer.dll ora ana|Instalasi Windows iki ora ngemot DLL Photo Viewer klasik.|Deleng gambar nganggo Windows Photo Viewer.
ban|Pendaftaran={0}/{1}. {2}|Sampun sayaga ring Open with; pilih Windows Photo Viewer ring Default Apps antuk PNG/JPG miwah soroh gambar tiosan.|Pendaftaran durung jangkep. Terapang antuk ngaptiang panangan gambar; AKTIF nénten mateges aplikasi baku sampun kagentos.|Versi rekaman pendaftaran Photo Viewer nénten kasangga. Cadangan tetep kasimpen.|DLL Windows Photo Viewer nénten kapanggihin.|PhotoViewer.dll nénten wénten|Instalasi Windows puniki nénten madaging DLL Photo Viewer klasik.|Cingak gambar nganggen Windows Photo Viewer.
de|Registrierung={0}/{1}. {2}|In Open with verfügbar; wählen Sie Windows Photo Viewer in Default Apps für PNG/JPG und andere Bildtypen.|Die Registrierung ist unvollständig. Wenden Sie die Option an, um Bildhandler zu reparieren; EIN bedeutet nicht, dass die Standard-App geändert wurde.|Die Version der gespeicherten Photo-Viewer-Registrierung wird nicht unterstützt. Die Sicherung bleibt erhalten.|Die Windows-Photo-Viewer-DLL wurde nicht gefunden.|PhotoViewer.dll fehlt|Diese Windows-Installation enthält die DLL des klassischen Photo Viewer nicht.|Bilder mit Windows Photo Viewer anzeigen.
fr|Enregistrement={0}/{1}. {2}|Disponible dans Open with ; choisissez Windows Photo Viewer dans Default Apps pour PNG/JPG et les autres types d'image.|L'enregistrement est incomplet. Appliquez l'option pour réparer les gestionnaires d'images ; ACTIVÉ ne signifie pas que l'application par défaut a été modifiée.|La version de l'instantané d'enregistrement de Photo Viewer n'est pas prise en charge. La sauvegarde est conservée.|La DLL de Windows Photo Viewer est introuvable.|PhotoViewer.dll est manquant|Cette installation de Windows ne contient pas la DLL du Photo Viewer classique.|Afficher les images avec Windows Photo Viewer.
es|Registro={0}/{1}. {2}|Disponible en Open with; elija Windows Photo Viewer en Default Apps para PNG/JPG y otros tipos de imagen.|El registro está incompleto. Aplique la opción para reparar los controladores de imágenes; ACTIVADO no significa que se haya cambiado la aplicación predeterminada.|La versión de la instantánea del registro de Photo Viewer no es compatible. Se conserva la copia de seguridad.|No se encontró la DLL de Windows Photo Viewer.|Falta PhotoViewer.dll|Esta instalación de Windows no contiene la DLL del Photo Viewer clásico.|Ver imágenes con Windows Photo Viewer.
pt|Registo={0}/{1}. {2}|Disponível em Open with; escolha Windows Photo Viewer em Default Apps para PNG/JPG e outros tipos de imagem.|O registo está incompleto. Aplique a opção para reparar os manipuladores de imagens; ATIVADO não significa que a aplicação predefinida tenha sido alterada.|A versão do estado guardado do registo de Photo Viewer não é suportada. A cópia de segurança foi mantida.|A DLL de Windows Photo Viewer não foi encontrada.|PhotoViewer.dll está em falta|Esta instalação de Windows não contém a DLL do Photo Viewer clássico.|Ver imagens com Windows Photo Viewer.
sv|Registrering={0}/{1}. {2}|Tillgänglig i Open with; välj Windows Photo Viewer i Default Apps för PNG/JPG och andra bildtyper.|Registreringen är ofullständig. Tillämpa alternativet för att reparera bildhanterare; PÅ betyder inte att standardappen har ändrats.|Versionen av den sparade Photo Viewer-registreringen stöds inte. Säkerhetskopian behålls.|DLL-filen för Windows Photo Viewer hittades inte.|PhotoViewer.dll saknas|Denna Windows-installation innehåller inte DLL-filen för klassiska Photo Viewer.|Visa bilder med Windows Photo Viewer.
ru|Регистрация={0}/{1}. {2}|Доступно в Open with; выберите Windows Photo Viewer в Default Apps для PNG/JPG и других типов изображений.|Регистрация неполная. Примените настройку для исправления обработчиков изображений; ВКЛ не означает, что приложение по умолчанию изменено.|Версия снимка регистрации Photo Viewer не поддерживается. Резервная копия сохранена.|DLL Windows Photo Viewer не найдена.|PhotoViewer.dll отсутствует|В этой установке Windows отсутствует DLL классического Photo Viewer.|Просмотр изображений с помощью Windows Photo Viewer.
uk|Реєстрація={0}/{1}. {2}|Доступно в Open with; виберіть Windows Photo Viewer у Default Apps для PNG/JPG та інших типів зображень.|Реєстрація неповна. Застосуйте налаштування для виправлення обробників зображень; УВІМК не означає, що типову програму змінено.|Версія знімка реєстрації Photo Viewer не підтримується. Резервну копію збережено.|DLL Windows Photo Viewer не знайдено.|PhotoViewer.dll відсутня|Ця інсталяція Windows не містить DLL класичного Photo Viewer.|Перегляд зображень за допомогою Windows Photo Viewer.
vi|Đăng ký={0}/{1}. {2}|Sẵn dùng trong Open with; chọn Windows Photo Viewer trong Default Apps cho PNG/JPG và các loại ảnh khác.|Đăng ký chưa đầy đủ. Áp dụng để sửa trình xử lý ảnh; BẬT không có nghĩa là ứng dụng mặc định đã thay đổi.|Phiên bản bản chụp đăng ký Photo Viewer không được hỗ trợ. Bản sao lưu được giữ lại.|Không tìm thấy DLL của Windows Photo Viewer.|Thiếu PhotoViewer.dll|Bản cài đặt Windows này không chứa DLL của Photo Viewer cổ điển.|Xem ảnh bằng Windows Photo Viewer.
zh-CN|注册={0}/{1}。{2}|已可在 Open with 中使用；请在 Default Apps 中为 PNG/JPG 和其他图像类型选择 Windows Photo Viewer。|注册不完整。请应用此选项以修复图像处理程序；开启不表示默认应用已更改。|不支持此 Photo Viewer 注册快照版本。备份已保留。|未找到 Windows Photo Viewer DLL。|缺少 PhotoViewer.dll|此 Windows 安装不包含经典 Photo Viewer 的 DLL。|使用 Windows Photo Viewer 查看图片。
zh-TW|註冊={0}/{1}。{2}|已可在 Open with 中使用；請在 Default Apps 中為 PNG/JPG 和其他影像類型選取 Windows Photo Viewer。|註冊不完整。請套用此選項以修復影像處理常式；開啟不代表預設應用程式已變更。|不支援此 Photo Viewer 註冊快照版本。備份已保留。|找不到 Windows Photo Viewer DLL。|缺少 PhotoViewer.dll|此 Windows 安裝不包含傳統 Photo Viewer 的 DLL。|使用 Windows Photo Viewer 檢視圖片。
ja|登録={0}/{1}。{2}|Open with で利用できます。PNG/JPG などの画像形式には Default Apps で Windows Photo Viewer を選択してください。|登録が不完全です。適用して画像ハンドラーを修復してください。オンは既定のアプリが変更されたことを意味しません。|Photo Viewer の登録スナップショットのバージョンはサポートされていません。バックアップは保持されています。|Windows Photo Viewer の DLL が見つかりません。|PhotoViewer.dll がありません|この Windows インストールには従来の Photo Viewer の DLL がありません。|Windows Photo Viewer で画像を表示します。
ko|등록={0}/{1}. {2}|Open with에서 사용할 수 있습니다. PNG/JPG 및 기타 이미지 형식에 대해 Default Apps에서 Windows Photo Viewer를 선택하세요.|등록이 불완전합니다. 적용하여 이미지 처리기를 복구하세요. 켜짐은 기본 앱이 변경되었다는 뜻이 아닙니다.|Photo Viewer 등록 스냅샷 버전이 지원되지 않습니다. 백업은 유지됩니다.|Windows Photo Viewer DLL을 찾을 수 없습니다.|PhotoViewer.dll이 없습니다|이 Windows 설치에는 기존 Photo Viewer DLL이 없습니다.|Windows Photo Viewer로 사진을 봅니다.
th|การลงทะเบียน={0}/{1} {2}|พร้อมใช้งานใน Open with; เลือก Windows Photo Viewer ใน Default Apps สำหรับ PNG/JPG และรูปภาพประเภทอื่น|การลงทะเบียนไม่สมบูรณ์ ใช้ตัวเลือกนี้เพื่อซ่อมตัวจัดการรูปภาพ; เปิดไม่ได้หมายความว่าเปลี่ยนแอปเริ่มต้นแล้ว|ไม่รองรับเวอร์ชันสำเนาสถานะการลงทะเบียน Photo Viewer เก็บข้อมูลสำรองไว้แล้ว|ไม่พบ DLL ของ Windows Photo Viewer|ไม่มี PhotoViewer.dll|การติดตั้ง Windows นี้ไม่มี DLL ของ Photo Viewer แบบดั้งเดิม|ดูรูปภาพด้วย Windows Photo Viewer
ar|التسجيل={0}/{1}. {2}|متاح في Open with؛ اختر Windows Photo Viewer في Default Apps لملفات PNG/JPG وأنواع الصور الأخرى.|التسجيل غير مكتمل. طبّق الخيار لإصلاح معالجات الصور؛ التفعيل لا يعني تغيير التطبيق الافتراضي.|إصدار لقطة تسجيل Photo Viewer غير مدعوم. تم الاحتفاظ بالنسخة الاحتياطية.|لم يتم العثور على DLL الخاص بـ Windows Photo Viewer.|ملف PhotoViewer.dll مفقود|لا يحتوي تثبيت Windows هذا على DLL الخاص بـ Photo Viewer التقليدي.|عرض الصور باستخدام Windows Photo Viewer.
ur|اندراج={0}/{1}۔ {2}|Open with میں دستیاب ہے؛ PNG/JPG اور دیگر تصویری اقسام کے لیے Default Apps میں Windows Photo Viewer منتخب کریں۔|اندراج نامکمل ہے۔ تصویروں کے ہینڈلرز کی مرمت کے لیے اختیار لاگو کریں؛ فعال ہونے کا مطلب یہ نہیں کہ طے شدہ ایپ بدل گئی ہے۔|Photo Viewer کے اندراج کے محفوظ عکس کا ورژن معاون نہیں ہے۔ بیک اپ برقرار ہے۔|Windows Photo Viewer کی DLL نہیں ملی۔|PhotoViewer.dll موجود نہیں|Windows کی اس تنصیب میں پرانے Photo Viewer کی DLL موجود نہیں ہے۔|Windows Photo Viewer سے تصاویر دیکھیں۔
hi|पंजीकरण={0}/{1}। {2}|Open with में उपलब्ध है; PNG/JPG और अन्य चित्र प्रकारों के लिए Default Apps में Windows Photo Viewer चुनें।|पंजीकरण अधूरा है। चित्र हैंडलर की मरम्मत के लिए विकल्प लागू करें; चालू होने का अर्थ यह नहीं कि डिफ़ॉल्ट ऐप बदल गया है।|Photo Viewer के पंजीकरण स्नैपशॉट का संस्करण समर्थित नहीं है। बैकअप सुरक्षित रखा गया है।|Windows Photo Viewer की DLL नहीं मिली।|PhotoViewer.dll मौजूद नहीं है|इस Windows इंस्टॉलेशन में पुराने Photo Viewer की DLL नहीं है।|Windows Photo Viewer से चित्र देखें।
ta|பதிவு={0}/{1}. {2}|Open with இல் தயாராக உள்ளது; PNG/JPG மற்றும் பிற பட வகைகளுக்கு Default Apps இல் Windows Photo Viewer ஐத் தேர்ந்தெடுக்கவும்.|பதிவு முழுமையடையவில்லை. படக் கையாளிகளைச் சரிசெய்ய இந்தத் தேர்வைப் பயன்படுத்தவும்; இயக்கத்தில் இருப்பது இயல்புநிலைப் பயன்பாடு மாற்றப்பட்டதைக் குறிக்காது.|Photo Viewer பதிவின் சேமித்த நிலைப் பிரதியின் பதிப்பு ஆதரிக்கப்படவில்லை. காப்புப்பிரதி பாதுகாக்கப்பட்டுள்ளது.|Windows Photo Viewer DLL கண்டறியப்படவில்லை.|PhotoViewer.dll இல்லை|இந்த Windows நிறுவலில் பழைய Photo Viewer DLL இல்லை.|Windows Photo Viewer மூலம் படங்களைப் பார்க்கவும்.
""";
}
