#ifndef SourceDir
  #error SourceDir is required. Build using build-installer.ps1 to select a complete publish stage.
#endif

#ifndef OutputDir
  #define OutputDir "..\artifacts\installer"
#endif

#ifndef AppVersion
  #error AppVersion must be supplied by build-installer.ps1 from the project version.
#endif

#define AppName "Naufal Windows Utility"
#define AppExeName "Naufal Windows Utility.exe"
#define AppPublisher "Muhammad Naufal Alauddin"
#define AppUserModelId "NaufalTechs.WindowsPowertoys"
#define AppIconFile "{app}\Assets\NaufalWindowsPowertoys.ico"

#ifndef ProgramInfoFile
  #error ProgramInfoFile must be generated by build-installer.ps1.
#endif

[Setup]
AppId={{A75F9775-AC15-4F03-8931-43D04EA6B032}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} v{#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL=https://github.com/mnaufalalauddin/Naufal-Windows-Utility
AppSupportURL=https://github.com/mnaufalalauddin/Naufal-Windows-Utility/issues
LicenseFile=..\LICENSE
DefaultDirName={autopf}\Naufal Tech's Limited\Naufal Windows Utility
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
SetupArchitecture=x64
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0.17763
OutputDir={#OutputDir}
OutputBaseFilename=Naufal-Windows-Utility-Setup-{#AppVersion}-x64
SetupIconFile=..\Assets\NaufalWindowsPowertoys.ico
UninstallDisplayIcon={#AppIconFile}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
DisableWelcomePage=no
CloseApplications=yes
RestartApplications=no
; Do not reuse the legacy Powertoys folder or an older flat Program Files path.
UsePreviousAppDir=no
UsePreviousGroup=yes
VersionInfoVersion={#AppVersion}
VersionInfoProductVersion={#AppVersion}
VersionInfoProductName={#AppName}
VersionInfoCompany={#AppPublisher}
VersionInfoDescription={#AppName} Installer

[Files]
Source: "{#SourceDir}\*"; DestDir: "{app}"; Excludes: "*.pdb"; Flags: ignoreversion recursesubdirs createallsubdirs

[InstallDelete]
; Preserve AppId, AppData and registry snapshots; relocation is guarded below.
; Remove only the superseded owned launcher/resources and legacy shortcuts.
Type: files; Name: "{app}\Naufal Windows Powertoys.exe"
Type: files; Name: "{app}\Naufal Windows Powertoys.pri"
Type: files; Name: "{autoprograms}\Naufal Windows Powertoys.lnk"
Type: files; Name: "{autodesktop}\Naufal Windows Powertoys.lnk"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Icons]
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\{#AppExeName}"; WorkingDir: "{app}"; IconFilename: "{#AppIconFile}"; IconIndex: 0; AppUserModelID: "{#AppUserModelId}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; WorkingDir: "{app}"; IconFilename: "{#AppIconFile}"; IconIndex: 0; AppUserModelID: "{#AppUserModelId}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExeName}"; WorkingDir: "{app}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  ProgramInfoPage: TWizardPage;
  ProgramInfoText: TNewMemo;

#include ProgramInfoFile


procedure InitializeWizard;
begin
  ProgramInfoPage := CreateCustomPage(wpWelcome, 'Naufal Windows Utility', '');
  ProgramInfoText := TNewMemo.Create(WizardForm);
  ProgramInfoText.Parent := ProgramInfoPage.Surface;
  ProgramInfoText.SetBounds(0, 0, ProgramInfoPage.SurfaceWidth, ProgramInfoPage.SurfaceHeight);
  ProgramInfoText.Anchors := [akLeft, akTop, akRight, akBottom];
  ProgramInfoText.ReadOnly := True;
  ProgramInfoText.ScrollBars := ssVertical;
  ProgramInfoText.WordWrap := True;
  LoadProgramInformation;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  PreviousInstallDir: String;
begin
  Result := '';
  { Moving an existing AppId to a different directory would leave its old
    files/uninstall log behind while replacing its uninstall registration.
    Require a normal uninstall first; never delete or run an uninstaller here. }
  if RegQueryStringValue(HKLM64,
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{A75F9775-AC15-4F03-8931-43D04EA6B032}_is1',
    'Inno Setup: App Path', PreviousInstallDir) then
  begin
    if (PreviousInstallDir <> '') and
      (CompareText(RemoveBackslash(ExpandFileName(PreviousInstallDir)),
        RemoveBackslash(ExpandFileName(ExpandConstant('{app}')))) <> 0) then
      Result := 'An existing installation is registered at:' + #13#10 +
        PreviousInstallDir + #13#10#13#10 +
        'Wait for all running tasks to finish, close the application, then uninstall ' +
        'the existing version from Windows Settings > Apps before installing in the new folder.' + #13#10#13#10 +
        'Setup has not moved or deleted the old installation.';
  end;
end;
